site/admin-guide.xml, site/documentation.xml, site/install-selinux-ports.xml.inc, site/install-windows-ports.xml.inc, site/networking.xml, site/pages.xml.dat, site/production-checklist.xml
This introduces two new documentation guides:
* Everything related to networking
* Production check list
The goal is not to make the guides as extensive as possible but to offer a starting point. We will expand both guides over time based on user feedback and what support questions we get most often.
=> Networking and Production Checklist guides

site/tutorials/tutorial-one-java.md
fixed typo reported in https://groups.google.com/forum/#!topic/rabbitmq-users/7N4KgPVerhc
=> fixed typo

site/tutorials/tutorial-five-java.md, site/tutorials/tutorial-four-java.md, site/tutorials/tutorial-one-java.md, site/tutorials/tutorial-three-java.md, site/tutorials/tutorial-two-java.md
=> Use DefaultConsumer in Java tutorials

site/web-stomp.md
Part of rabbitmq/rabbitmq-web-stomp#17.
=> Update Web-Stomp docs with the new /ws path

site/tutorials/tutorial-five-php.md, site/tutorials/tutorial-four-php.md, site/tutorials/tutorial-one-php.md, site/tutorials/tutorial-six-php.md, site/tutorials/tutorial-three-php.md, site/tutorials/tutorial-two-php.md
Replaces deprecated Connection class name by current one, plus minor cosmetic changes.
=> Rabbitmq website 54

site/web-stomp.md
For https://github.com/rabbitmq/rabbitmq-web-stomp/issues/22
=> Add docs about new options tcp_config and cowboy_opts

site/web-stomp.md
Part of a series of PRs for rabbitmq/rabbitmq-web-stomp#4
=> Document the sockjs_opts configuration option

site/tutorials/tutorial-five-python.md, site/tutorials/tutorial-four-python.md, site/tutorials/tutorial-one-python.md, site/tutorials/tutorial-six-python.md, site/tutorials/tutorial-three-python.md, site/tutorials/tutorial-two-python.md
fix https://github.com/rabbitmq/rabbitmq-website/issues/68
=> updated pika version to 0.10.0

site/build-erlang-prerequisites.xml.inc
Add missing zip and unzip requirements and specify Python version. Fixes #81
=> Add missing prerequisites

site/mqtt.md
Fixes https://github.com/rabbitmq/rabbitmq-website/issues/84.
=> Clarify how to disable subscription TTL for the MQTT plugin

site/stomp.md
should be merged with https://github.com/rabbitmq/rabbitmq-stomp/pull/44
=> updated STOMP docs for x-queue-name

site/e2e.xml
@videlalvaro, I think it is good this time ^^' sorry for the other PR.
=> Fix one little mistyping on a .NET Client Example

site/ha.xml
See https://github.com/rabbitmq/rabbitmq-server/issues/336
=> Documents new ha-sync-batch-size policy

site/memory.xml
Documentation for https://github.com/rabbitmq/rabbitmq-server/issues/207
=> Document absolute values in memory high watermark

site/ha.xml
Part of https://github.com/rabbitmq/rabbitmq-server/issues/369.
=> Correct docs per rabbitmq/rabbitmq-server#369

site/dotnet-api-guide.xml
This is the .NET/C# client, and not Java client.
=> Fix client name

site/lazy-queues.xml, site/pages.xml.dat
related to https://github.com/rabbitmq/rabbitmq-server/pull/377
=> lazy queues documentation

site/ttl.xml
To make it clear that server resources will be freed, and not to require
anybody to dive into the source to confirm this )
=> Clarify what happens after setting TTL policy

site/configure.xml, site/mqtt.md, site/networking.xml
https://github.com/rabbitmq/rabbitmq-server/issues/453
=> Remove unneeded TCP options from documentation

site/tutorials/tutorial-five-php.md, site/tutorials/tutorial-four-php.md
Related to this pull request
https://github.com/rabbitmq/rabbitmq-tutorials/pull/81
=> Sync source changes with tutorials

site/configure.xml, site/ha.xml
Solves [#460](https://github.com/rabbitmq/rabbitmq-server/issues/460).
=> Documentation for using rabbit.config to define queue-master-locator strategies

site/configure.xml, site/disk-alarms.xml, site/memory.xml
A bit of documentation for https://github.com/rabbitmq/rabbitmq-server/issues/448
https://github.com/rabbitmq/rabbitmq-server/issues/461
=> Documentation for set_disk_free_limit and set_vm_memory_high_watermark

site/amqp-0-9-1-errata.xml
Related to https://github.com/rabbitmq/rabbitmq-common/pull/32
Issue https://github.com/rabbitmq/rabbitmq-server/issues/20
=> Mention unsigned types in doc

site/api-guide.xml
Rewording of the address list algorithm explanation to better reflect reality. Fixes #73.
NB: I see that I've accidentally replaced all tabs with spaces (as I've set up in [Atom](https://atom.io/)); please let me know if I should revert that and create a new PR without it.
=> Rewording of the address list algorithm explanation to better reflect reality

site/build-erlang-client.xml
=> Update build client docs

site/plugin-development.xml
=> Update the plugin development guide after the switch to erlang.mk

site/configure.xml, site/management.xml, site/pages.xml.dat, site/web-dispatch.md
Part of https://github.com/rabbitmq/rabbitmq-management/issues/63
Little changes because it should basically be compatible.
=> Update the web dispatch documentation

site/shovel-dynamic.xml, site/shovel-static.xml
Doc for https://github.com/rabbitmq/rabbitmq-shovel/pull/9
=> Doc for add-forward-headers config to add shovelled timestamp header

site/configure.xml
Part of https://github.com/rabbitmq/rabbitmq-server/issues/528
=> Make number of Ranch acceptors configurable

site/confirms.xml, site/mqtt.md
Related to https://github.com/rabbitmq/rabbitmq-mqtt/issues/21
=> Docs for downgrading QoS2 to QoS1

site/tutorials/tutorial-five-elixir.md, site/tutorials/tutorial-four-elixir.md, site/tutorials/tutorial-one-elixir.md, site/tutorials/tutorial-three-elixir.md, site/tutorials/tutorial-two-elixir.md
Fixing some small typos in the Elixir tutorials.
=> Elixir tutorial fixups

site/devtools.xml, site/tutorials/tutorial-five-php.md, site/tutorials/tutorial-four-php.md, site/tutorials/tutorial-one-php.md, site/tutorials/tutorial-six-php.md, site/tutorials/tutorial-three-php.md, site/tutorials/tutorial-two-php.md
See: https://packagist.org/packages/videlalvaro/php-amqplib
=> php-amqplib changed ownership to the php-amqplib organization from videlalvaro

site/web-dispatch.md, site/web-stomp.md
Also includes a small typo fix in web-stomp.md.
Part of https://github.com/rabbitmq/rabbitmq-management/issues/138
=> Document cowboy_opts in dispatch

site/web-stomp.md
Part of https://github.com/rabbitmq/rabbitmq-web-stomp/issues/43
=> Document the RabbitMQ-Web-STOMP use_http_auth option

site/configure.xml
from 8f1d5b0deefbd1c8b3b30ef3d538032e92948fda
Docs for https://github.com/rabbitmq/rabbitmq-server/pull/728
=> Copied documentation for RABBITMQ_CONF_ENV_FILE 

site/plugin-development.xml
Documentation for https://github.com/rabbitmq/rabbitmq-server/pull/642
https://github.com/rabbitmq/rabbitmq-server/issues/591
=> Documentation for plugin version constraints

site/management.xml
Also applies as-is to master, once https://github.com/rabbitmq/rabbitmq-management/pull/176 is merged.
Final part of https://github.com/rabbitmq/rabbitmq-management/issues/157
=> Add CORS to the management plugin docs

site/tutorials/tutorial-one-objectivec.md
=> Update objc tutorial1 copy for async API

site/tutorials/tutorial-one-objectivec.md, site/tutorials/tutorial-two-objectivec.md, site/tutorials/tutorials-menu.xml.inc
This builds on [the last tutorial 1 PR](https://github.com/rabbitmq/rabbitmq-website/pull/187).
=> Objective-C tutorial 2

site/tutorials/tutorial-four-objectivec.md, site/tutorials/tutorial-one-objectivec.md, site/tutorials/tutorial-three-objectivec.md, site/tutorials/tutorial-two-objectivec.md, site/tutorials/tutorials-menu.xml.inc
This is a superset of the [PR for tutorial 3](https://github.com/rabbitmq/rabbitmq-website/pull/193)
=> Objective-C tutorials 3 and 4, updates to older tutorials.

site/tutorials/tutorial-four-objectivec.md
=> Fix link to source of objc tutorial 4

site/css/tutorial.css, site/tutorials/tutorial-five-dotnet.md, site/tutorials/tutorial-five-elixir.md, site/tutorials/tutorial-five-go.md, site/tutorials/tutorial-five-java.md, site/tutorials/tutorial-five-javascript.md, site/tutorials/tutorial-five-php.md, site/tutorials/tutorial-five-python.md, site/tutorials/tutorial-five-ruby.md
Uses CSS targets to avoid JS maintenance.
Issue #52
=> Teasers can open and close in tutorial 5

site/tutorials/tutorial-five-objectivec.md, site/tutorials/tutorials-menu.xml.inc
=> Tutorial 5 for Objective-C

site/ldap.xml
Ref: rabbitmq/rabbitmq-auth-backend-ldap#12
=> Document and update LDAP log level options, for scrubbing bind request credentials in logs.

site/dlx.xml
=> Fix dead letter cycle detection note

site/pacemaker.xml
Also note about a lazy joining for cluster members
Signed-off-by: Bogdan Dobrelya <bdobrelia@mirantis.com>
=> Note about a disposable cluster and policy file

site/devtools.xml
Changed "an" to "a" in Haskell and OCaml :)
=> Fix typos in devtools.xml

site/which-erlang.xml
Part of https://github.com/rabbitmq/rabbitmq-server/pull/798
and
https://github.com/rabbitmq/rabbitmq-server/issues/546
=> Bump minimal Erlang version to 18.3

site/pacemaker.xml
Here is the docs update related to the accepted change https://github.com/rabbitmq/rabbitmq-server/pull/794
=> Note for a Pacemaker ver and few OCF params

site/build-dotnet-client.xml
Fixes #221, https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/169, to go with: https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/170
=> update dotnet client build instructions

site/ldap.xml
Docs for https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/pull/43
https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/issues/3
=> Document in_group_nested LDAP query

site/management.xml
Part of https://github.com/rabbitmq/rabbitmq-management/issues/221
=> Document rabbitmq_management.stats_event_max_backlog

site/tutorials/tutorial-five-objectivec.md, site/tutorials/tutorial-four-objectivec.md, site/tutorials/tutorial-one-objectivec.md, site/tutorials/tutorial-three-objectivec.md, site/tutorials/tutorial-two-objectivec.md
=> Update ObjC tutorial code snippets for v0.9.0

site/configure.xml
Work in progress, please take a look and I'll update additional docs (site/networking) to reflect default options as well.
=> Updating docs to reflect omitted linger statement

site/configure.xml, site/networking.xml
Continuing work from https://github.com/rabbitmq/rabbitmq-website/pull/237
=> Updating main configuration and networking sections

site/page.xsl, wordpress-theme/footer.php
* Shorten "Privacy Policy" to "Privacy" (we're short on space)
* Use https scheme in pivotal.io links to avoid redirects
[#127911405]
=> Add Terms of Use link and adjust others

site/tutorials/tutorial-two-java.md
As suggested by @dhruvkapur91 and contributed by @ffissore.
Fixes #204
=> Clarify acknowledgment in Java tutorial 2

site/clustering.xml
=> Clustering guide: Remove missing plugin references.

site/devtools.xml
Changed link from VMware site to OSS client.
=> RabbitMQ JMS client now OSS

site/api-guide.xml
=> Document Java client AddressResolver

site/api-guide.xml
=> Document Java client metrics support

site/install-guest-localhost.xml.inc
=> Fix typo in Default user access section

site/community-plugins.xml, site/page.xsl
Testing a new Concourse job - but this may end up being the final PR anyway.
[#130355353]
=> /community-plugins.html links to Bintray uploads

site/configure.xml, site/management.xml, site/pages.xml.dat, site/web-dispatch.md
Cherry-picked the relevant doc updates for your convenience.
Part of https://github.com/rabbitmq/rabbitmq-management/issues/236
=> Update stable docs for Cowboy switch

site/java-tools.xml
=> Update Java Tools page after PerfTest and Tracer extraction

site/api-guide.xml
=> Document Java NIO

site/configure.xml
Fixes #282
References https://github.com/rabbitmq/rabbitmq-server/issues/979
=> Document configuration encryption

site/clustering.xml
=> site/clustering.xml: Document that patch release may require a cluster shutdown

site/configure.xml
Doc for https://github.com/rabbitmq/rabbitmq-server/issues/1022
=> Configure member retries on Mnesia reconnection failures

site/api-guide.xml
References https://github.com/rabbitmq/rabbitmq-java-client/issues/210
=> Enable auto recovery by default in Java Client

site/shovel.xml
Found while implementing https://github.com/rabbitmq/rabbitmq-shovel/issues/22
=> Fix 'running' status format

site/configure.xml, site/management.xml, site/production-checklist.xml
Part of: https://github.com/rabbitmq/rabbitmq-management/issues/236
=> New management plugin changes

site/tutorials/tutorial-five-swift.md, site/tutorials/tutorial-four-swift.md, site/tutorials/tutorial-one-swift.md, site/tutorials/tutorial-three-swift.md, site/tutorials/tutorial-two-swift.md, site/tutorials/tutorials-menu.xml.inc
Identical to Objective-C tutorials with converted code.
Related to https://github.com/rabbitmq/rabbitmq-tutorials/issues/102
References https://github.com/rabbitmq/rabbitmq-tutorials/pull/103
=> Swift tutorials

site/mqtt.md
Part of rabbitmq/rabbitmq-mqtt#111
=> Document port-to-vhost mapping in MQTT plugin

site/configure.xml
Doc for https://github.com/rabbitmq/rabbitmq-server/pull/1072
=> Document queue_explicit_gc_run_operation_threshold

site/passwords.xml
Part of rabbitmq/rabbitmq-server#1054.
=> Document credential validators

site/access-control.xml, site/ldap.xml
References rabbitmq/rabbitmq-server#505
=> Document topic authorisation

site/tutorials/tutorial-five-java.md, site/tutorials/tutorial-four-java.md, site/tutorials/tutorial-one-java.md, site/tutorials/tutorial-six-java.md, site/tutorials/tutorial-three-java.md, site/tutorials/tutorial-two-java.md
=> Update Java tutorials build instructions

site/tutorials/tutorial-six-java.md
I've accidently messed up branch for #327 , so here's another PR. Forked from live as @acogoluegnes asked.
=> Updated tutorial six Java code examples

site/tutorials/tutorial-six-java.md
One more step to perfection. 😄
=> Removed throws clause from fib declaration to sync with rabbitmq-tutorials

site/management.xml, site/nettick.xml
=> Document effect of partitions on management API/UI

site/access-control.xml, site/ldap.xml
Part of rabbitmq/rabbitmq-server#1085
=> Document topic authorisation for consumption

site/access-control.xml, site/ldap.xml
Docs for rabbitmq/rabbitmq-auth-backend-ldap#60
rabbitmq/rabbitmq-auth-backend-ldap#59
=> Fix LDAP plugin config prefix in docs

site/configure.xml, site/mqtt.md, site/networking.xml, site/stomp.md
Part of rabbitmq/rabbitmq-server#589
=> Document proxy protocol support

site/access-control.xml, site/ldap.xml
Part of rabbitmq/rabbitmq-server#1099
=> Document topic authorisation for queue binding

site/tutorials/tutorial-two-ruby.md
Fixed an inconsistency in the worker code when sleeping to imitate some work.
=> Minor update in Ruby Tutorial - Two

site/dotnet-api-guide.xml
@michaelklishin as we discussed, rebased against live branch
=> how to mark message as acknowledged in .NET api

site/networking.xml
Refer to http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html
Signed-off-by: Chengwei Yang <yangchengwei@qiyi.com>
=> networking.xml: fix tcp keepalive meaning

site/networking.xml
Signed-off-by: Chengwei Yang <yangchengwei@qiyi.com>
=> networking.xml: fix networking tunning link

site/management.xml
Part of https://github.com/rabbitmq/rabbitmq-management-agent/issues/41
[#143308479]
=> Clarify that all three policies are now mandatory

site/tutorials/tutorial-one-elixir.md
refer to https://github.com/rabbitmq/rabbitmq-tutorials/pull/133 for matching commit
=> elixir: use 0.2.1 now its released

site/ha.xml
In a recent discussion it became obvious that some concepts are worth reiterating in different contexts, in particular **Configuring Synchronisation**.
Made some formatting improvements while at it, just enough to make it easier to follow.
=> Clarify queue synchronisation concepts

deploy
I had to deploy recently and would have liked sensible defaults with prompts. What do you think?
=> Deploy with interactive defaults

site/nightly-builds.xml
Also, remove a trailing bar separator
[#128649497]
=> Remove links to empty dir listings

site/memory.xml, site/production-checklist.xml
This is just a first pass, it needs a few more refinements and a few
more opinions. It's already better than what we had, but not there yet.
Let's start discussing: @michaelklishin @dumbbell @Gsantomaggio
=> Improve production memory guidelines

site/jms-client.md
Part of rabbitmq/rabbitmq-jms-client#21
=> Document JNDI support in WildFly (JMS client)

site/tutorials/amqp-concepts.xml
=> Queue is only auto-deleted when it has had at least one consumer

site/access-control.xml
Part of rabbitmq/rabbitmq-server#1229
=> Cover variable expansion in topic authorisation

site/configure.xml
rabbitmq/rabbitmq-server#1259
[#145451399]
Signed-off-by: Gerhard Lazu <gerhard@rabbitmq.com>
=> Add new vm_memory_use_process_rss config value

site/tutorials/tutorial-two-dotnet.md
To clarify that it is required without having to inspect the full sample
at the bottom of the file.
Fixes: https://github.com/rabbitmq/rabbitmq-tutorials/issues/136
Not sure if this needs to go to master or stable.
=> Mention how to reference System.Threading.

site/clustering.xml
Updated link to rabbitmq-autocluster repo
=> Updated link to rabbitmq-autocluster repo

site/logging.md
Fixes #418 
Draft log configuration guide for 3.7 lager-based logging
=>  Log configuration guide.

site/cluster-formation.xml
Some small changes from reviewing the new document.
=> Cluster formation guide review

.gitignore, site/admin-guide.xml, site/how.xml, site/monitoring.xml
Please see the following story: #150650781
=> Improve monitoring documentation

site/tutorials/tutorial-six-java.md
a. Channel is final
b. Replace sleep() with wait()/notify()
=> Updated tutorial-six-java.md with as per changes in RPCServer.java

site/tutorials/tutorial-six-dotnet.md
An entry point method (static void main) has been added to the RpcClient code.
=> Merged file tutorial-six-dotnet.md from master branch

site/configure.xml
Should be merged with rabbitmq/rabbitmq-server#1366
=> Add  msg_store_credit_disc_bound  & msg_store_credit_disc_bound to https://www.rabbitmq.com/configure.html

site/tutorials/tutorial-five-python.md, site/tutorials/tutorial-four-python.md, site/tutorials/tutorial-three-python.md
ML thread: https://groups.google.com/d/topic/rabbitmq-users/YbIno7oQglg/discussion
=> Address issue from rabbitmq-users report

site/maxlength.xml
=> Wording suggestions from PR review

site/api-guide.xml
Part of rabbitmq/rabbitmq-java-client#313
=> Document Java Client support for Micrometer

site/configure.xml
See rabbitmq/rabbitmq-common#224
=> Configuration changes for rabbitmq/rabbitmq-common#224

site/ssl.xml
See michaelklishin/tls-gen#8 for details
=> Fixup certificate generation configuration

site/plugins.xml, site/protocols.xml, site/web-mqtt.md, site/web-stomp.md
Part of https://github.com/rabbitmq/rabbitmq-web-stomp/pull/79
rabbitmq/rabbitmq-web-dispatch#30
[#151681379]
=> SockJS is not supported in Web-STOMP anymore

site/memory-use.xml
Docs for https://github.com/rabbitmq/rabbitmq-management/pull/500 and https://github.com/rabbitmq/rabbitmq-server/pull/1404
rabbitmq/rabbitmq-management#499
[#151472607]
=> Explain unused memory for memory breakdown request

site/management.xml
Fixes rabbitmq/rabbitmq-management#481
=> Add path_prefix documentation

site/maxlength.xml, site/stomp.md
Require rabbitmq/rabbitmq-server#1374
Addresses rabbitmq/rabbitmq-server#995
=> Document overflow behaviour setting for queue limit

site/ssl.xml, site/uri-query-parameters.xml
PT [153560059] [153560538]
See rabbitmq/rabbitmq-erlang-client#95 and rabbitmq/rabbitmq-erlang-client#97
=> Add server_name_indication to the docs

site/uri-query-parameters.xml
[153560538] Adds an example URL for encrypted connections.
=> Add amqps:// example

site/shovel-static.xml
Fixed up whitespace, ensured term format matched up, added target_address
See https://groups.google.com/d/topic/rabbitmq-users/1vhdSx3mz7o/discussion
=> Improvements to amqp091 - amqp10 example shovel config

site/admin-guide.xml, site/backup.md, site/documentation.xml, site/pages.xml.dat, site/upgrade.md
Draft guide for upgrade and backup steps.
=> Initial Backup and Restore guide

site/upgrade.md
=> Upgrade guide: Mention memory reporting in 3.6.11

site/cli.md, site/erlang-cookie.xml.inc, site/install-windows-manual.xml, site/release-notes/README-2.8.5.txt, site/windows-quirks.xml
This makes the documentation consistent throughout the site
=> Final set of Windows-specific Erlang cookie changes

site/upgrade.md
=> Add resources check step to upgrade process

site/upgrade.md
List client libraries supporting reconnections and multiple URLs and link to docs in the upgrade guide.
=> Cover client connection recovery in the upgrade guide

site/upgrade.md
Mainly, add more details and examples to several steps.
[#153172934]
=> Address several comments around upgrades

site/networking.xml
=> Set unique name for handshake timeout section.

site/management-cli.md
Reported here: https://groups.google.com/d/topic/rabbitmq-users/4XUn4ukkZOc/discussion
=> Fix rabbitmqadmin download link

site/java-tools.xml
Message properties, queue arguments, content of messages, queue sequence, running high load.
[#154601702,#154553043,#154281436]
=> UNRELEASED FEATURE Miscellaneous updates in PerfTest page

site/configure.xml, site/list-of-ports.xml.inc, site/networking.xml
Part of rabbitmq/rabbitmq-cli#237
=> Document distribution port range for CLI tools

site/tutorials/tutorial-two-python.md
New queue name is added in code example too early
=> Fix second python tutorial

site/clients.xml
=> Changes from review

site/relocate.xml
=> Generated config and schema directory locations

site/configure.xml, site/relocate.xml
Further clarifies rabbitmq/rabbitmq-website#494
=> RABBITMQ_BASE is Windows only

site/tutorials/tutorial-five-ruby.md, site/tutorials/tutorial-four-ruby.md, site/tutorials/tutorial-one-ruby.md, site/tutorials/tutorial-six-ruby.md, site/tutorials/tutorial-three-ruby.md, site/tutorials/tutorial-two-ruby.md
Applying the changes made in [rabbitmq-tutorials PR#156](https://github.com/rabbitmq/rabbitmq-tutorials/pull/156).
=> Update ruby tutorials

site/tutorials/tutorial-six-java.md
java: local variable corrId is accessed from within inner class; needs to be declared final
=> corrId is accessed from within inner class

site/upgrade.md
- rabbitmq/rabbitmq-management#530
=> Specify Storage Cleanup on RabbitMQ/Management Plugin Upgrade

site/api-guide.xml
=> Provide guidelines on thread and channel management

site/page.xsl
This is an experiment we've discussed a few months ago. It covers most guides. I'm not sure about adding e.g. additional tracking for the links here.
Submitted for discussion with other core team members.
=> Trailing getting help section

site/configure.xml, site/erlang-client-user-guide.xml, site/networking.xml
To go with https://github.com/rabbitmq/rabbitmq-server/issues/1593.
=> Prepare for new channel_max default change

site/confirms.xml
=> Fix a typo a rephrase one sentence

site/priority.xml, site/queues.md
Documentation improvements to go with rabbitmq/rabbitmq-server#1590.
=> Priority Queues guide improvements

site/tutorials/tutorial-five-php.md, site/tutorials/tutorial-four-php.md, site/tutorials/tutorial-one-php.md, site/tutorials/tutorial-six-php.md, site/tutorials/tutorial-three-php.md, site/tutorials/tutorial-two-php.md
The code in the PHP tutorials was sometimes a bit messy.
With these changes the code conforms to standards outlined here:
https://www.php-fig.org/psr/psr-2/
=> PHP Tutorial pages conform to PSR-2 standard

site/blue-green-upgrade.md
"loosing" --> "losing", and some nitpicking.
=> Spelling & grammar

site/management.xml
Document setting added in https://github.com/rabbitmq/rabbitmq-management/pull/584
=> Document login_session_timeout setting.

site/tutorials/tutorial-one-elixir.md
Corresponding website changes for https://github.com/rabbitmq/rabbitmq-tutorials/pull/172
=> update for later versions of elixir and amqp lib

site/clustering-ssl.xml
PT [159602360]
Note: I'll add Windows instructions in my next PR
=> Add documentation for the ssl_dist_optfile argument

site/clustering-ssl.xml
Fixes #426 and [159602360]
Also see rabbitmq/rabbitmq-server#1666
=> Add distributed Erlang TLS documentation for Windows

site/tutorials/tutorial-six-java.md
See rabbitmq/rabbitmq-tutorials#175
=> Update Java tutorial six to match rabbitmq/rabbitmq-tutorials#175

site/cluster-formation.xml
https://github.com/rabbitmq/rabbitmq-peer-discovery-k8s/issues/33
=> Kubernetes hostname only works with stateful set

site/man/rabbitmqctl.8.html
"federation local_username" does not exist anymore
=> Change example to use parameter that exists

site/reliability.xml
Super minor improvement of readability ...
=> Increase readability

site/ha.xml
=> Fixup for rabbitmq-website#581

site/tutorials/tutorial-six-go.md
While reading RabbitMQ tutorial on Golang, I find and fix code typo.
=> Fix code typo

site/ha.xml
Hello,
I removed a paragraph that was duplicated. It is already written a little bit above this one.
=> Update ha.xml to delete duplicated paragraph

site/clustering.xml
=> Fixed a typo

site/devtools.xml
https://github.com/Polyconseil/aioamqp
=> [devtools] Add aioamqp (Python)

site/ssl.xml
Part of rabbitmq/rabbitmq-server#1712.
[#160792113]
=> Document cipher suite configuration in new style config format

site/ldap.xml
These are new variables introduced by rabbitmq/rabbitmq-auth-backend-ldap#98 and  rabbitmq/rabbitmq-auth-backend-ldap#102
=> Document ad_domain, ad_user and user_bind_pattern

site/production-checklist.xml
Corrections to make the documentation easier to read:
Added missing "are" and corrected spelling of "operator"
=> Grammar and spelling corrections

site/ssl.xml
Fix broken link to http://rabbitmq.github.io/rabbitmq-dotnet-client/api/RabbitMQ.Client.SslOption.html
=> Fix broken link

site/networking.xml
See rabbitmq/rabbitmq-server#1784 and rabbitmq/rabbitmq-server#1785.
=> Documentation example for rabbitmq/rabbitmq-server#1784

site/production-checklist.xml
- Fix spelling of produce on production-checklist
=> Fix spelling

site/index.xml
=> Add Visual Integrator and clean up links

site/configure.xml
Docs for https://github.com/rabbitmq/rabbitmq-server/pull/1812
=> Max msg size

site/consumers.md
[#161090309]
References rabbitmq/rabbitmq-server#1743
=> Document single active consumer feature

site/stomp.md
Part of rabbitmq/rabbitmq-stomp#94
=> Add notes about stomp.default_topic_exchange setting

site/quorum-queues.md
To go with https://github.com/rabbitmq/rabbitmq-server/pull/1834
=> Update quorum_queue.md with queue length feature

site/consumers.md
[#163298456]
References rabbitmq/rabbitmq-server#1838
=> Document active consumer flag

site/install-rpm.xml
Found and fixed a minor typo on the install-rpm page.
=> Minor typo fix in install-rpm page

site/install-debian.xml
=> Fix component in erlang repository

Makefile, site/networking.xml
Part of rabbitmq/rabbitmq-server#1881
=> Remove inet_dist_listen_min / inet_dist_listen_max from ini-style config

site/clustering.xml
=> Fix a few typos in "Clustering Guide"

site/tutorials/tutorial-two-spring-amqp.md
=> Fix typo in amqp tutorial 2

site/tutorials/amqp-concepts.xml
Just removes a duplicated line in the channels section of the amqp concepts page.
Also thanks very much for a very good tutorial! It was a good read, and helped me learn.
Cheers 
// Sebastian
=> Removes duplicate line

site/tutorials/tutorial-two-dotnet.md, site/tutorials/tutorial-two-elixir.md, site/tutorials/tutorial-two-go.md, site/tutorials/tutorial-two-java.md, site/tutorials/tutorial-two-javascript.md, site/tutorials/tutorial-two-objectivec.md, site/tutorials/tutorial-two-php.md, site/tutorials/tutorial-two-python.md, site/tutorials/tutorial-two-ruby.md, site/tutorials/tutorial-two-swift.md
=> Fix typo from customer to consumer

site/dlx.xml, site/quorum-queues.md
=> Quorum queues: Document delivery-limit

site/production-checklist.xml
Or `addressee` was intently used?
=> Fix typo in production-checklist.xml

site/install-homebrew.xml
update path to sbin directory as of brew v2.0.5 and rabbitmq v3.7.12
=> Update path to sbin directory in install-homebrew.xml

site/dotnet-api-guide.xml
Trying out Rabbit MQ and just saw this little Typo.
=> Fix a simple Typo

site/ae.md
Fixed spelling mistake in Alternative Exchange extension document
=> Fix Alternative Exchange Spelling

site/upgrade.md, site/windows-quirks.md
=> Add a note about host name case sensitivity

site/federation-reference.xml
Docs for https://github.com/rabbitmq/rabbitmq-federation/pull/92
=> Federation cusom consumer tag

site/monitoring.md
Link should now go to https://www.rabbitmq.com/monitoring.html#system-metrics
=> Fix missing #

site/tutorials/tutorial-three-javascript.md
Replacing with correct variable names
=> Fix small error in receive_logs.js

site/tutorials/tutorial-five-javascript.md, site/tutorials/tutorial-four-javascript.md, site/tutorials/tutorial-six-javascript.md, site/tutorials/tutorial-three-javascript.md, site/tutorials/tutorial-two-javascript.md
According to #743 there are some code declarations which are not up to date.
I added to missing update in this commit.
=> correct missing changes with javascript tutorial codes.

site/troubleshooting-ssl.md
See the following discussion:
https://groups.google.com/d/msg/rabbitmq-users/7322jFIfXxw/sWhqpaDQDQAJ
=> Add a couple important s_client arguments

site/clustering.xml, site/configure.md, site/memory-use.xml
Just found a few small things.
=> Fix broken links, remove duplicate variable

site/dlx.md
=> [docs] DLX minor typo

site/queues.md
corrected the link of memory alarms at queue.md
=> corrected the link of memory alarms

site/tutorials/tutorial-two-javascript.md
Ack in first block of code causes error because of noAck = true.
=> Fix premature ack in tutorial

site/maxlength.xml
See rabbitmq/rabbitmq-server#1443, rabbitmq/rabbitmq-server#2015
=> Document an option to dead-letter rejected publishes

site/ssl.xml
=> attacks can be mitigated, not migrated

site/tutorials/tutorial-four-python.md, site/tutorials/tutorial-six-python.md, site/tutorials/tutorial-three-python.md
=> Fixes #780 Some Python tutorials use queue_declare() without ... 

site/documentation.xml
=> Fixed wrong link.

site/confirms.md
(Just some arbitrary changes in passing as I was reading. Props for the very nice documentation by the way!)
=> Fix some typos and improve some phrasing in confirms.md

site/clustering.md, site/install-debian.md, site/install-generic-unix.md, site/install-rpm.md, site/install-standalone-mac.md, site/list-of-ports.xml.inc, site/networking.md
=> List Prometheus port

site/tutorials/tutorial-six-dotnet.md
Just removing a random semicolon
=> Just removing a random semicolon

site/upgrade.md
Corrected 2 typos in the upgrade documentation page
=> Corrected some typos

site/jms-client.md
References rabbitmq/rabbitmq-jms-client#115
Should be merged once JMS Client 1.13 is out (with publisher confirms support) and once the publisher confirms tutorial has been merged.
=> Add section on publisher confirms for JMS client

site/mqtt.md
References rabbitmq/rabbitmq-mqtt#206
=> Add section about Sparkplug in MQTT plugin page

site/api-guide.md
=> Document OAuth 2 support in Java client

site/management.md, site/release-notes/3.7.0.md
=> Change rawgit to githack

site/configure.md, site/css/rabbit.css
=> Configuration guide: more readable multi-column tables

site/consumer-prefetch.md
Specify that consumer prefetch is an extension to the channel prefetch and not the consumer prefetch mechanism.
=> Fix consumer prefetch description

site/monitoring.md
Added official Zabbix monitoring integrations.
=> Updated monitoring.md

site/community-plugins.xml
=> Add 3.8.x compatible download links for Tier-2 plugins

site/ldap.md
Part of rabbitmq/rabbitmq-auth-backend-ldap#114
=> Clarify correct usage of dn_lookup_bind

site/monitoring.md
=> Add Nastel solution to page

site/management.md
=> Document OAuth 2/UAA support in management plugin

site/management.md
Reported in this public RMQ slack thread: https://rabbitmq.slack.com/archives/C1EDN83PA/p1574803946089500
=> Add a note about timeouts and load balancers

site/mqtt.md
Part of https://github.com/rabbitmq/rabbitmq-mqtt/pull/195
=> Document mqtt decommission node command

site/tutorials/tutorial-one-dotnet.md
=> Add missing verb

site/api-guide.md, site/java-client.md, site/java-versions.md, site/jms-client.md
=> Create supported versions page for Java libraries

site/consumers.md
References rabbitmq/discussions#50
=> Explain why a policy cannot enable SAC

site/configure.md
=> Restore max_message_size documentation

site/monitoring.md, site/nettick.md
The grammatical error "rabbitmq-diganostics" has been corrected to "rabbitmq-diagnostics"
=> Fixed a grammatical error 

site/tutorials/tutorial-six-go.md
Please reject if I have misread this and made a mistake :D
=> Missing subject in sentence

site/devtools.md
I want add this package to the list. I think it is ready for production or at least it might be useful to someone.
=> Added aio-amqp into devtools

site/shovel-static.xml
see [advanced config example](https://github.com/rabbitmq/rabbitmq-server/blob/v3.8.3/docs/advanced.config.example)
=> "uris" parameter should be "brokers"

site/tutorials/tutorial-two-spring-amqp.md
when  if (dots.incrementAndGet() == 3)  dots.set(1), the value is 1,not 3,
so for (int i = 0; i < dots.get(); i++) { builder.append('.'); } can not println hello...   
it reality println
[x] Sent 'Hello.1'
[x] Sent 'Hello..2'
[x] Sent 'Hello.3'
[x] Sent 'Hello..4'
......
=> The output of the sender has error

site/tutorials/tutorial-one-elixir.md, site/tutorials/tutorial-one-go.md, site/tutorials/tutorial-one-java.md, site/tutorials/tutorial-one-php.md, site/tutorials/tutorial-one-ruby.md
Similar to commit e799ea068592d2cad1037ca9c2e447557cc5ff18.
=> Fixed a grammar problem and made the paragraph less confusing.

site/tutorials/tutorial-three-dotnet.md
body.ToArray() got called twice. This is a small  change.
=> [Fix] compile error in source tutorial 3 C#.

site/kubernetes/operator/operator-monitoring.md
This clarifies a few points:
* Prometheus annotations are included by default on all RabbitMQ pods
* Prometheus annotations are only automatically scraped if using config
provided by the Prometheus Helm chart
* The `prometheus` CR spec field `podMonitorNamespaceSelector` is of
type [LabelSelector](https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/types.go#L1095), and so does not support the `any: 'true'` syntax. This field will select all namespaces by default, and applying the patch does nothing, so this advice is removed.
Also added example Prometheus config for automatic scraping of RabbitMQ
pods deployed by the Operator.
=> Fix inaccuracies in operator monitoring guide

site/kubernetes/operator/using-operator.md
Missing docs for an existing feature
=> add docs for the override property

site/build-server.md, site/feature-flags.md, site/partitions.md, site/upgrade.md, site/which-erlang.md
A number of minor fixes in spelling and wording.
=> Some minor fixes

site/api-guide.md, site/dotnet-api-guide.md, site/ha.md, site/partitions.md, site/plugin-development.md, site/shovel-dynamic.md
=> Minor typo fixes

site/channels.md, site/cli.md, site/cluster-formation.md, site/clustering.md, site/connections.md, site/ec2.md, site/install-windows.md, site/management.md, site/monitoring.md, site/networking.md, site/queues.md, site/windows-quirks.md
Minor fixes and improvements in spelling, wording, grammar, and so on.
=> Typo fixes and minor improvements

site/access-control.md
'to connecting to it' should be 'to connect to it'
=> Fix grammar error in access-control.md

site/ec2.md, site/production-checklist.md, site/runtime.md
Fixed a few misspellings and a couple of incorrect link anchors.
=> Fixed typos and bad link anchors

site/alarms.md, site/blue-green-upgrade.md, site/build-dotnet-client.md, site/cli.md, site/clustering.md, site/configure.md, site/logging.md, site/mqtt.md, site/shovel-dynamic.md, site/upgrade.md
Numerous fixes and improvements on spelling and wording.
Also fixed two incorrect links.
=> Fix typos, improve wording, corrected links

site/kubernetes/operator/install-operator.md, site/prometheus.md
=> Fix 2 typos

site/tutorials/tutorial-one-python.md
Running the code and pressing Ctrl+C on Windows will result in:
```
(rabbitmq) C:\git\rabbitmq>python receive.py
[*] Waiting for messages. To exit press CTRL+C
[x] Received b'Hello World!'
[x] Received b'Hello World!'
[x] Received b'Hello World!'
Traceback (most recent call last):
File "receive.py", line 15, in <module>
channel.start_consuming()
File "C:\Users\<username>\Envs\rabbitmq\lib\site-packages\pika\adapters\blocking_connection.py",
n start_consuming
self._process_data_events(time_limit=None)
File "C:\Users\<username>\Envs\rabbitmq\lib\site-packages\pika\adapters\blocking_connection.py",
n _process_data_events
self.connection.process_data_events(time_limit=time_limit)
File "C:\Users\<username>\Envs\rabbitmq\lib\site-packages\pika\adapters\blocking_connection.py", …
```
=> Python Tutorial 1 - Handle KeyboardInterupt

site/tutorials/tutorial-two-python.md
Before:
```
(rabbitmq) C:\git\rabbitmq>python new_task.py
[x] Sent 'Hello World!'
(rabbitmq) C:\git\rabbitmq>python receive.py
[*] Waiting for messages. To exit press CTRL+C
[x] Received b'Hello World!'
```
After:
```
(rabbitmq) C:\git\rabbitmq>python worker.py
[*] Waiting for messages. To exit press CTRL+C
[x] Received 'Hello World!'
```
Goes with https://github.com/rabbitmq/rabbitmq-tutorials/pull/276
=> Use decode() to convert the string to utf-8

site/shovel.md, site/tutorials/tutorial-one-javascript.md, site/tutorials/tutorial-one-php.md, site/tutorials/tutorial-one-ruby.md, site/tutorials/tutorial-one-spring-amqp.md, site/tutorials/tutorial-seven-dotnet.md, site/tutorials/tutorial-seven-java.md, site/tutorials/tutorial-two-dotnet.md, site/tutorials/tutorial-two-elixir.md, site/tutorials/tutorial-two-objectivec.md, site/tutorials/tutorial-two-swift.md
Correct wording, fix links, improved punctuation.
=> Correct wording, links, punctuation

site/kubernetes/operator/using-operator.md
see https://github.com/rabbitmq/cluster-operator/issues/252
=> Add advanced.config

site/clustering.md, site/monitoring.md, site/upgrade.md
=> Typo fixes

site/kubernetes/operator/install-operator.md, site/kubernetes/operator/operator-overview.md
Update minimal required rmq version for cluster operator.
=> Update minimal required rmq version for cluster operator

site/access-control.md, site/api-guide.md, site/mqtt.md, site/passwords.md, site/stomp.md, site/web-mqtt.md
Minor improvements in wording, grammar, punctuation, link anchors, and code highlighting.
=> A bunch of minor improvements

site/clustering.md
=> rabbit@rabbi1 -> rabbit@rabbit1

site/kubernetes/operator/troubleshooting-operator.md, site/kubernetes/operator/using-operator.md
This closes: #1078 
Thanks @agregory999 for pointing this out.
=> Correct k8s object names

site/queues.md
Add missing closing parenthesis for a link.
=> Fix Typo - parenthesis

site/kubernetes/operator/install-operator.md
- Documented how to create a Security Context Contraint to allow creation of RabbitMQ Pods
- Examples using openshift client CLI to add a security context constraint to a user/service account
We tested the documented changes in a local OpenShift 4.6 node.
Related https://github.com/rabbitmq/cluster-operator/issues/435
Co-authored-by: David Ansari <dansari@vmware.com>
=> Security Context Contraints in OpenShift

site/kubernetes/operator/operator-overview.md
Relates to https://github.com/rabbitmq/cluster-operator/issues/440
=> Add kubectl rabbitmq docs

site/kubernetes/operator/install-operator.md, site/kubernetes/operator/operator-overview.md
Updated minimal k8s version and rabbitmq version
=> Update required k8s version

site/kubernetes/operator/using-operator.md
* Documented common labels and annotations applied by the Cluster Operator
* Added an index to faciliate the navigation of this guide.
* Updated some content to reflect the changes in Cluster Operator 1.0.
=> Document common labels in Cluster Operator

site/feature-flags.md, site/man/rabbitmqctl.8.html
The feature has been merged already
=> Document new feature: `rabbitmqctl enable_feature_flag all`

site/devtools.md
Bowler is a production ready Client abstraction for Laravel.
=> Add Bowler to PHP devtools

site/heartbeats.md
Change value of `RequestedHeartbeat` in C# example to `TimeSpan`.
Relevant commit:
https://github.com/rabbitmq/rabbitmq-dotnet-client/commit/f25ea2d3d5e51df93f6ff5f43f0f2ffac9ab002d#diff-20c8990054b1b54d305ba776f1afeeef4a173207ab5ceb3c22ee0e841c3a3a32R300
=> Update C# sample code in heartbeats.md

Pipfile, Pipfile.lock, site/configure.md, site/networking.md, site/windows-quirks.md
Reported in this rabbitmq-users discussion:
https://groups.google.com/g/rabbitmq-users/c/k8oYQEHsRfA
=> Update documentation to set non-standard dist port on Windows

site/configure.md, site/connection-blocked.md, site/connections.md, site/consumer-cancel.md, site/feature-flags.md, site/kubernetes/operator/using-operator.md, site/logging.md, site/passwords.md
* Fix dead links
* Correct spelling
* Improve wording and punctuation
=> Fix dead links and typos

site/trademark-guidelines.md
Hello, this PR fixes  an improper markup.
Signed-off-by: Hirotaka Wakabayashi <hiwkby@yahoo.com>
=> Fixes an improper markup

site/clients.md, site/cluster-formation.md, site/install-windows.md
- Fix typos and invalid link anchors.
- Remove an incomplete sentence.
=> Minor fixes

site/ssl.md
I'm confident in the fix at line 1344, 1347 ad 1355..
But I don't know what would be the correct fix at line 1373.
Pls advise
=> partially fix rabbitmq-diagnostics cipher_suites

site/install-homebrew.md
I believe the title is kind of self explanatory, I hope! 😜🎉
=> Correct a spelling mistake from "expert" to "export"

site/kubernetes/operator/install-operator.md, site/kubernetes/operator/using-operator.md
* Extended documentation on Pod Security Policies
* Extended documentation on image relocation
* Added a missing step for private image registries
* Added a link to sample manifests to get started
=> Improvements to installation and usage guides

site/monitoring.md
Add line for Dynatrace RabbitMQ monitoring to the table.
=> add Dynatrace RabbitMQ monitoring

site/kubernetes/operator/install-operator.md
Updated according to reported issue: https://github.com/rabbitmq/cluster-operator/issues/488
=> Update Openshift SecurityContextConstraints for cluster operator

site/kubernetes/operator/install-operator.md
As reported in: https://github.com/rabbitmq/cluster-operator/issues/488
=> Improve install operator in Openshift guide

site/kubernetes/operator/troubleshooting-operator.md
=> Info about operator crash on startup

site/kubernetes/operator/troubleshooting-operator.md
Fix a dead link in kubernetes/operator/troubleshooting-operator page.
=> Fix dead link

site/confirms.md, site/consumer-prefetch.md
See https://github.com/rabbitmq/rabbitmq-server/blob/17b082abeb19340eea98a9700b32a964db75dadc/deps/rabbit/docs/rabbitmqctl.8#L1051-L1054
=> Explain that prefetch of 0 is treated as infinite

site/ssl.md
=> fix variablename

site/tutorials/tutorial-two-dotnet.md
=> Update link to .NET client API reference

site/kubernetes/operator/operator-overview.md
Updated more of the day 2 operations docs to reflect the latest state of the operator.
=> Update operator overview page with current supported features

site/monitoring.md
`message_stats.deliver_get.rate` -> `message_stats.deliver_get_details.rate`
=> Fix incorrect field name

site/quorum-queues.md
fix duplicate text / link + verb
=> fix text typo

site/queues.md
Going through the *Queues* doc on the website, I found a sentence a bit hard to parse. This PR suggest a slightly different way of wording it.
=> site/queues.md: Reword "Message Ordering" sentence

site/kubernetes/operator/install-topology-operator.md, site/kubernetes/operator/tls-topology-operator.md, site/kubernetes/operator/using-topology-operator.md
More documentation on topology operator:
- how to configure topology operator to connect to RabbitmqCluster with tls
- how to use guide
=> More documentation on topology operator

site/kubernetes/operator/using-topology-operator.md
Fix table of contents to reference correct header IDs
=> Update using-topology-operator.md TOC to link properly

site/kubernetes/operator/using-topology-operator.md
Document federation and shovel for messaging topology operator.
=> Document federation and shovel for topology operator

site/dlx.md
Just making the sentence a little bit more clear :smiley_cat:
=> Update DLX docs

site/kubernetes/operator/using-topology-operator.md
Add a note about not to use queue arguments in topology operator doc.
=> Add a note about not to use queue arguments

site/release-notes/3.9.0.md
Did a few other changes, all captured as separate commits so that they can be dropped / refined.
All yours @michaelklishin 👍🏻
=> Add global counters to 3.9.0 release notes

site/tutorials/tutorial-six-dotnet.md
See discussion https://github.com/rabbitmq/rabbitmq-tutorials/issues/296.
=> Fix memory leak in tutorial six dotnet

site/prometheus.md
Document `/metrics/per-object` endpoint and refactor the per-object metrics section to make it easier to understand how the configuration affects the data returned by these endpoints
=> Document `/metrics/per-object` endpoint

site/install-debian.md
So close and yet so far....remove errand "on".
=> Fix tiny typo

site/install-debian.md
Recycled wording from https://github.com/rabbitmq/rabbitmq-website/pull/1246 into other relevant section.
=> Simplified "Modern Erlang on Debian" wording

site/install-debian.md
1. `service` -> `systemctl`
2. Re-introduce `sudo` to relevant bits
=> Small tidies

site/tutorials/tutorials-intro.xml.inc
Just making the gender neutral stuff (which I applaud) a bit less awkward.
=> Fixing some of the language a little

site/queues.md
A separate PR will document behavior in 3.10+
=> Document current exclusive queue location behavior

site/kubernetes/operator/using-operator.md
The vault configuration section was missing the configuration YAML present in other sections.
=> Add Vault configuration YAML

Makefile
This fixes it for me, but rather than pushing it and breaking it for others, it would help to have the team members that run it locally confirm that it still works for them after this change.
=> Make site preview work on macOS 10.14.6

site/install-debian.md
=> Debian guide: fix Invalid local anchors

site/streams.md
Closes https://github.com/rabbitmq/rabbitmq-server/issues/3695
=> Document interval offset in `x-stream-offset`

site/services.md
=> Update name and link for CSS Commerce

site/ha.md
Previous use next line which was not really precise enough and simply not clear.
=> Provide more precise description on ha-all mode

site/changelog.md, site/ha.md
=> Fix two links

site/getstarted.md
=> Add link to stream blog posts on tutorials page

site/devtools.md
New and fast Ruby and TypeScript/JavaScript clients
=> Additional clients

site/definitions.md
=> Document definitions.skip_if_unchanged

site/page.xsl, wordpress-theme/footer.php
Keep the year updated to ensure documentation is maintained and updted.
=> Current year update

site/tutorials/amqp-concepts.md
Docs for https://github.com/rabbitmq/rabbitmq-server/pull/4203
=> Support all-with-x in x-match binding argument

site/cluster-formation.md, site/configure.md, site/relocate.md
=> Document RABBITMQ_CONFIG_FILES (plural, a conf.d-style directory)

site/streams.md
=> Add count UI limitation

site/vhosts.md
This PR fixes typos in the vhosts page
=> Minor typo fix in vhosts page

site/mqtt.md
Closes #1385. References rabbitmq/rabbitmq-server#4254
=> Document QQ support for durable MQTT subscriptions

site/api-guide.md, site/cluster-formation.md, site/configure.md, site/dotnet-api-guide.md, site/federation-reference.md
Fixed typos and updated links where required.
=> Fixed typos

site/upgrade.md
Signed-off-by: Gabriele Santomaggio <G.santomaggio@gmail.com>
Add a link to blue green upgrade. Per conversation with @mkuratczyk
=> Add a link to blu green upgrade

site/logging.md, site/man/rabbitmqctl.8.html
I tried to avoid ambiguous "higher severity" as it sounds like "more severe/critical" but could mean "higher severity number" ie "less severe". (Although "more critical" is not perfect either as there is a "critical" level, and "emergency" is more critical than "critical" :) )
=> Update possible log levels

site/page.xsl
Hi! 👋 
I've found some errors while I was searching on RabbitMQ doc. Some links are broken, relative path was used but it is not valid in some folders so I've fixed them. 
You're able to see in this page which links are broken or inaccessible in header and footer. https://www.rabbitmq.com/tutorials/tutorial-six-java.html
=> Update page.xsl for avoiding inaccessible links

site/kubernetes/operator/using-topology-operator.md
New feature document for top op.
https://github.com/rabbitmq/messaging-topology-operator/pull/369
=> Document topology operator sync period

site/changelog.md, site/news.xml, site/versions.md, site/which-erlang.md
=> 3.8.32 release is out

site/kubernetes/operator/using-operator.md, site/kubernetes/operator/vault-topology-operator.md
Document that operators only work with vault kv 2
Issue: https://github.com/rabbitmq/messaging-topology-operator/issues/368
=> Document that operators only work with vault kv 2

site/kubernetes/operator/configure-operator-defaults.md, site/kubernetes/operator/debug-operator.md
This functionality is upcoming in the Kubernetes operators, pending a couple of PRs.
Setting this to be a Draft PR for now; I will convert to a Ready for Merging PR once the functionality is in.
=> Add documentation supporting the operator's pprof functionality

site/tutorials/tutorial-one-dotnet.md
Removed incorrect information about having to run the clients in a specific order. Added the order as a recommendation.
=> Removed incorrect information about necessary client run order.

site/tutorials/tutorial-two-dotnet.md
Removed unnecessary "dotnet restore". Run automatically by "dotnet add package".
=> Removed unnecessary "dotnet restore".

site/tutorials/tutorial-two-dotnet.md
Fixed example output from Worker.cs to correspond with what the code actually produces.
=> Fixed example output from Worker.cs

site/tutorials/tutorial-two-dotnet.md
Updated instructions for creating Worker.cs to make it complete but also more to the point.
=> Updated instructions for creating Worker.cs

site/tutorials/tutorial-one-php.md
Signed-off-by: Erdem Köse <erdemkose@gmail.com>
Fix two broken links in [Tutorial One - PHP](https://www.rabbitmq.com/tutorials/tutorial-one-php.html)
=> Fix broken links

site/definitions.md
Updating link to keep up with [folder change in sample-configs](https://github.com/rabbitmq/sample-configs/commit/e3c63ec83ffc96faae5954ebac475ef9f2530cf6)
=> Update link to githubusercontent for sample-configs

site/which-erlang.md
=> on in-> in

driver.py, site/devtools.md
* Remove some very out-of-date projects
* Indicate which projects have official support
=> Tweaks to the devtools page

site/devtools.md, site/stream.md
Add NodeJS stream client
Signed-off-by: Gabriele Santomaggio <G.santomaggio@gmail.com>
=> Add NodeJS stream client

site/quorum-queues.md
To make sure it is clear rebalancing does not modify the quorum queue membership.
=> Correct replica rebalancing workding in quorum queue doc

README.md
Signed-off-by: Gabriele Santomaggio <G.santomaggio@gmail.com>
Add the `python venv` example
=> Add venv python example

site/upgrade.md
Differentiate between rolling and full stop upgrades
Related to rabbitmq/rabbitmq-server#6036
=> Update upgrade table

site/tutorials/tutorial-one-java.md
- change `java.io.Closeable` to `java.lang.AutoCloseable`
close #1553
=> docs: update tutoria-one-java.md

site/feature-flags.md
We see users try to pick and choose feature flags. Add a note to explain this is not the right approach
=> Explain that FFs are not configuration

site/prometheus.md
Addresses #1579. I'm not sure this requires a contributor agreement, since I'm essentially copy/pasting from a different rabbitmq repo.
=> Add docs for prometheus detailed metrics endpoint

site/stream-core-plugin-comparison.md
- Fix Link
- Add Super Stream comparison
Signed-off-by: Gabriele Santomaggio <G.santomaggio@gmail.com>
=> Add Super Stream comparison

site/persistence-conf.md
=> update to say per vhost message store

site/install-debian.md
Hi,
This is a simple PR, just adding Ubuntu 22.04 Jammy code name to install guide.
Cheers,
Paul
=> Add Ubuntu 22.04 code name

site/ttl.md
=> Missing update on qq

site/download.md, site/index.xml
**Testing notes**
Ran `gmake preview` and `./drivers.py` to check that the website rendered properly on localhost.
=> Added Amazon MQ as a managed service provider of RabbitMQ

site/parameters.md
Related server PR: https://github.com/rabbitmq/rabbitmq-server/pull/7601
=> Document setting policies by queue type

site/devtools.md
Hello!
Thank you for providing such a great product!
I am the CTO of Dating.com Group, and we have been using RabbitMQ as the main communication transport for many years. I recently released an open-source Node.js client library called [ComQ](https://github.com/toa-io/comq).
I kindly request that you consider adding ComQ to your website's list of client libraries.
**Features:**
1. Dynamic topology
2. Request-reply (RPC)
3. Events (pub/sub)
4. Content encoding
5. Flow control and back pressure handling
6. Consumer acknowledgments and publisher confirms
7. Poison message handling
8. Connection tolerance and broker restart resilience
9. Sharded connection
10. Graceful shutdown
Thank you for your consideration!
=> Add ComQ Node client library reference

site/consumers.md
=> Mention new ways of setting Consumer Timeout

site/backup.md
...I pointed this typo out in a comment to kjnilsson's original commit, but maybe it was lost
=> Fix typo in backup.md

site/versions.md
Link broken at https://www.rabbitmq.com/versions.html
=> Fix link to 3.11.17 tag

site/consumers.md
Clarifications regarding what happens to in-flight messages when a consumer is cancelled.
=> Update consumers guide

site/upgrade.md
also, remove 3.6 specific bits to keep this guide shorter
=> Highlight feature flags when upgrading

site/kubernetes/operator/troubleshooting-operator.md
Document RabbitmqCluster status conditions in Cluster Operator trouble shoot guide.
=> Document RabbitmqCluster status conditions

site/streams.md
Should be merged when stream filtering (https://github.com/rabbitmq/rabbitmq-server/pull/8207) is into `rabbitmq-server` `main`.
=> Document stream filtering

site/devtools.md
Also  ordered the list alphabetically (after the most popular)
=> Added Cambion to list of .NET frameworks

site/stomp.md
=> 3.12.2: STOMP guide: mention max_frame_size

site/stream.md
Add more detailed documentation for the stream clients.
Evidence the vmware supported clients.
Add C client
=> Add more detailed documentation for the stream clients.

site/devtools.md
=> Update stream clients list

site/priority.md
Hi @mkuratczyk, can you please review the updates in the priority queues OSS RabbitMQ topic - many thanks in advance.
=> Update priority.md to clarify information further and for SEO 

site/streams.md
Hey @acogoluegnes, can you review these SEO updates in the streams topic please. Please update in my branch directly if you have any feedback to save time. Many thanks in advance.
=> Update streams.md for SEO changes 

site/plugin-development.md
Seems you need to set the env variable DIST_AS_EZS to actually produce the ez file
=> Corrected make dist cmd

site/quorum-queues.md
Following the [discussion](https://groups.google.com/g/rabbitmq-users/c/2eo3z1eZBiY)
=> Quorum Queues guide: improve the section on length limit

site/monitoring.md
Update and simplify the readiness probe section
=> `ReadinessProbe` recommendation update

site/parameters.md
List was not up-to-date with current codebase. 
Related to https://github.com/rabbitmq/rabbitmq-server/pull/9127
=> Full list of operator policies and their precedence

Pipfile, Pipfile.lock, code/diagrams.py, code/render.py, driver.py, site/dotnet-api-guide.md
Related to https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/956
=> Update .NET OAuth2 documentation

site/devtools.md
=> Add Julia AMQP client

site/access-control.md
The linked repository is archived.
=> Update HTTP link in access-control

site/streams.md
I was reading the Streams documentation and thought the changes in this PR would aid in ease of reading.
The content itself has only been slightly adjusted.
=> Update wording and arrangement in `streams.md`

site/shovel-dynamic.md
These parameters were added in 3.8
=> Add src-queue-args and dest-queue-args

site/man/rabbitmq-streams.8.html
References rabbitmq/rabbitmq-server#9924
To merge when https://github.com/rabbitmq/rabbitmq-server/pull/9924 is merged in `v3.12.x`.
=> Document --binding-keys in add_super_stream

site/ha.md
Seems a stream/qq config name made its way into the HA doc!
=> Corrected config name

site/dlx.md
=> Typo correction

site/devtools.md
It is a client library with high abstraction level with auto reconnection,  supported by [NUTES](https://nutes.uepb.edu.br/) and developed as an open source project.
=> add amqp-client-python to devtools.md

site/tutorials/tutorial-two-python.md
- To reflect changes at https://github.com/rabbitmq/rabbitmq-tutorials/pull/371
=> fix: pika version 1.3.2

site/kubernetes/operator/operator-overview.md, site/kubernetes/operator/troubleshooting-topology-operator.md
Document a known limitation in the Topology Operator. This limitation
does not happen very often, but it's hard to understand from the user
perspective when it happens.
=> Document Topology Operator known limitation

docs/install-debian.md
since direct copy/paste would result in `Syntax error: "&" unexpected`, I suggest updating the codes in docs
=> replace &lt; with <

docusaurus.config.js
https://docusaurus.io/docs/api/themes/configuration#color-mode---dark-mode
Unfortunately, this does not seem to work as documented 🤔
=> Prefer system color scheme

docs/feature-flags.md
This is a follow-up to #1840 which I didn't have a chance to review.
=> Improvements to the "Feature flags" page

docs/upgrade.md
=> upgrade.md: Fix typo in "there node cluster"

sidebarsDocs.js
- Remove duplicated `Stream Plugin` link.
=> Remove duplicated sidebar link (Stream Plugin)

docusaurus.config.js
While here, synchronize the EOS dates with what was announced in the release notes.
=> docusaurus.config.js: New RabbitMQ 3.13.1 release

release-information/index.md, src/pages/contact.md
updates for commercial support
=> Reword the commercial support offering

docs/amqp.md
This is the documentation for https://github.com/rabbitmq/rabbitmq-server/pull/10873
=> 4.x: add AMQP address v2

docs/upgrade.md
* Drop description of versions earlier than 3.8: the only realistic upgrade path for those environments is a Blue/Green deployment upgrade
* Don't use 3.6 and 3.7 in version examples
* Recommend `--formatter=pretty_table` for `rabbitmqctl list_feature_flags`
=> Further Upgrading guide updates for the 3.13 and 4.x era

versioned_docs/version-3.13/upgrade.md
=> Sync Upgrading guide: 4.0 => 3.13

docs/management/index.md, docs/oauth2-examples-okta.md, docs/oauth2.md, docs/streams.md, docs/troubleshooting-oauth2.md, docs/troubleshooting/index.md, docusaurus.config.js, package-lock.json, package.json, versioned_docs/version-3.13/management/index.md, versioned_docs/version-3.13/oauth2.md, versioned_docs/version-3.13/streams.md, versioned_docs/version-3.13/troubleshooting-oauth2.md, versioned_docs/version-3.13/troubleshooting/index.md
Add Troubleshoot section to auth2 for managment ui
=> Add Troubleshoot section to docs/management page for oauth2

docs/dlx.md
This is the docs PR for https://github.com/rabbitmq/rabbitmq-server/pull/11174
=> Add dead lettering docs for AMQP clients

docs/classic-queues.md, docs/oauth2-examples-azure/index.md, versioned_docs/version-3.13/classic-queues.md, versioned_docs/version-3.13/oauth2-examples-azure/index.md
I've found some typos in docs, this PR fixes these typos.😇
=> Fix some words in docs

docs/ldap.md
Ref to https://github.com/rabbitmq/rabbitmq-server/pull/11395
=> Fix typo in ldap.md

docs/quorum-queues/index.md, docs/runtime.md
Correct the default atom table size, add info on changing table size if needed.
=> Update QQ Atom Usage info

tutorials/tutorial-one-dotnet-stream.md, tutorials/tutorial-one-go-stream.md, tutorials/tutorial-one-javascript-stream.md, tutorials/tutorial-one-python-stream.md, tutorials/tutorial-one-rust-stream.md
Additional changes to be made.
=> Follow-up to #1885

blog/2023-03-02-quorum-queues-migration/index.md
I was looking at the flow of the entire document with the recent change, and decided that it was actually pretty unclear. This moves the future-session-compatibility concern to its own section at the end of the migration process.
I also added mention of the`quorum_queue.property_equivalence.relaxed_checks_on_redeclaration` policy, since that's what we're going to use for our own migration.
=> fix(quorum-migration): clarify docs on quorum/classic comp

docs/federation-reference.md
Hello. I found broken table.
before
after
=> Update JSON object documentation in federation reference

docs/amqp.md
to reflect the changes in https://github.com/rabbitmq/rabbitmq-server/pull/11618
=> Update RabbitMQ AMQP address v2 docs

src/components/RabbitMQServerReleaseInfo/index.js
so the yellow legend marker can go.
=> We no longer support multiple OSS series at once

docs/which-erlang.md
=> Add 3.13.{1,2,3,4}

docs/management/index.md, docs/oauth2.md, versioned_docs/version-3.13/management/index.md, versioned_docs/version-3.13/oauth2.md
Add documentation for PR https://github.com/rabbitmq/rabbitmq-server/pull/11218
=> Configure end_session_endpoint

docs/oauth2.md
match the scope code with the written documentation
=> oauth2 scope documentation/typo fix

blog/2024-08-05-native-amqp/index.md
Clarify that Apache Qpid Broker-J also supports AMQP 0.9.1 as described in https://github.com/apache/qpid-broker-j?tab=readme-ov-file#qpid-broker-j
=> Add AMQP brokers

docusaurus.config.js, release-information/index.md, src/components/RabbitMQServerReleaseInfo/index.js, src/css/custom.css, src/pages/contact.md
Per discussion with @rdbwebster.
=> Commercial service column is back

sidebarsTutorials.js, tutorials/index.md, tutorials/tutorial-two-rust-stream.md
To finalize when https://github.com/rabbitmq/rabbitmq-stream-rust-client/issues/222 fixed.
=> tutorial2_stream_rust_client_finalization

docs/quorum-queues/index.md
Also some language simplifiction and section re-org to work better with the side bar.
=> Quorum queues: updates with v4 features

docs/quorum-queues/index.md
Docs for https://github.com/rabbitmq/rabbitmq-server/pull/12061
=> Rename quorum queue priority "low" to "normal"

blog/2024-08-05-native-amqp/index.md, blog/2024-08-21-amqp-benchmarks/index.md
as described in
https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-blog#image
=> Add thumbnail

blog/authors.yml
Use Docusaurus 3.5 feature https://docusaurus.io/blog/releases/3.5#blog-social-icons
=> Add author socials

sidebarsTutorials.js, tutorials/index.md, tutorials/tutorial-one-javascript-stream.md, tutorials/tutorial-two-javascript-stream.md
Tutorial 2 for RabbitMQ streaming nodejs client
=> Node.js streams: add a tutorial on offset tracking

docs/amqp.md, docs/connections/index.md, docs/conversions.md, docs/extensions.md, docs/plugins.md, docs/protocols.md, docs/specification.md, docs/stream-core-plugin-comparison.md, sidebarsDocs.js, src/pages/index.js
Also update outdated AMQP 1.0 docs.
=> Add more AMQP 1.0 docs for RabbitMQ 4.0

docs/configure.md
Docs for https://github.com/rabbitmq/rabbitmq-server/pull/12221
=> Document session_max

docs/configure.md
Docs for https://github.com/rabbitmq/rabbitmq-server/pull/12234
=> Add docs for `link_max_per_session`

docs/quorum-queues/index.md
merge after https://github.com/rabbitmq/rabbitmq-server/pull/12250 is at least in a beta
=> QQ: add details on how to disable default delivery limit

docs/feature-flags/index.md
Plus, a missing word in khepri_db
=> Add rabbitmq_4.0.0 feature flag

docs/prometheus/index.md
should be exchange instead of queue
=> fix typo in prometheus doc

kubernetes/operator/configure-operator-defaults.md
Specifically, the example to modify the default resource requests and limits
=> link to `cluster-operator` examples

kubernetes/operator/using-topology-operator.md
Related to rabbitmq/messaging-topology-operator/pull/700. This PR was merged and it's live, but the behaviour change was never documented.
=> Update connection secret cross-ns rules in Topology Operator

docs/amqp.md, docs/oauth2.md
Docs for https://github.com/rabbitmq/rabbitmq-server/pull/12599
=> Document AMQP 1.0 token renewal

docs/local-random-exchange.md, versioned_docs/version-4.0/local-random-exchange.md
ot -> to and a small clarification
=> Typo fix and small clarification

client-libraries/dotnet-api-guide.md, docs/ssl/index.md, docusaurus.config.js, package-lock.json, package.json, tutorials/tutorial-five-dotnet.md, tutorials/tutorial-four-dotnet.md, tutorials/tutorial-one-dotnet.md, tutorials/tutorial-seven-dotnet.md, tutorials/tutorial-six-dotnet.md, tutorials/tutorial-three-dotnet.md, tutorials/tutorial-two-dotnet.md, versioned_docs/version-3.13/ssl/index.md
* Start by updating the client lib guide
Related: https://github.com/rabbitmq/rabbitmq-tutorials/pull/473
=> Update dotnet docs for upcoming 7.0.0 release

client-libraries/dotnet.md
Link to NuGet to show supported TFMs
=> Fix dotnet client lib page

docs/mqtt.md, versioned_docs/version-4.0/mqtt.md
See https://github.com/rabbitmq/rabbitmq-server/issues/12719
=> Document MQTT re-authentication limitation

client-libraries/devtools.md
These links were broken. Didn't see versioned docks for this page(?) so only one place changed.
=> Remove broken links

package-lock.json, package.json
https://github.com/rabbitmq/rabbitmq-website/security/dependabot/37.
=> Bump a vulnerable dependency

docs/direct-reply-to.md, tutorials/tutorial-six-dotnet.md, tutorials/tutorial-six-elixir.md, tutorials/tutorial-six-go.md, tutorials/tutorial-six-java.md, tutorials/tutorial-six-javascript.md, tutorials/tutorial-six-php.md, tutorials/tutorial-six-python.md, tutorials/tutorial-six-ruby.md, tutorials/tutorial-six-spring-amqp.md, versioned_docs/version-4.0/direct-reply-to.md
* Identify benefits of this feature
* Improve `Motivation` section
* Fix tutorial descriptions
=> Revise Direct Reply-To

kubernetes/operator/install-operator.md
Encountered this snafu this morning. More [information here](https://github.com/bitnami/charts/issues/30582)
=> fix: add note about installing from opentofu/terraform

tutorials/tutorial-seven-dotnet.md
=> Fixed tutorial-seven-dotnet.md reference line numbers

versioned_docs/version-4.0/vhosts.md
Same as #2155 but for `4.0.x` and thus will have to wait until the `4.0.6` release.
=> For 4.0.6: document rabbitmq/rabbitmq-server#13015

docs/stream-core-plugin-comparison.md, versioned_docs/version-4.0/stream-core-plugin-comparison.md
Add AMQP 1.0 to the stream comparison page
=> Add AMQP 1.0 to the stream comparison page

client-libraries/amqp-client-libraries.md
Add code examples for Python in amqp-client-libraries.md
=> Add Python section to AMQP 1.0 Clients

client-libraries/amqp-client-libraries.md
-  Add documentation for the [rabbitmq-amqp-go-client](https://github.com/rabbitmq/rabbitmq-amqp-go-client) 
- Update the documentation for[rabbitmq-amqp-python-client](https://github.com/rabbitmq/rabbitmq-amqp-python-client)
=> golang amqp 1.0 documentation

client-libraries/amqp-client-libraries.md
amqp 1.0 go client. The client changed the connection API on the 0.1-beta.1
=> update documentation for the

client-libraries/amqp-client-libraries.md
Updated the Python AMQP 1.0 doc section to reflect last beta release modifications
=> updating python1.0 client doc

versioned_docs/version-4.0/ldap.md
(made the PR before the issue)
Fixes #2216
=> Move LDAP } to correct position

client-libraries/dotnet-api-guide.md
Related to rabbitmq/rabbitmq-dotnet-client#1815
=> Fix .NET code example.

docs/exchanges.md
Fixed small typo. I am first time here, and I hope here is no a lot of rules to prepare PRs, and it can be easily merged due to simplicity of PR
=> Fix typo in exchanges.md

client-libraries/dotnet-api-guide.md
I think some words are missing here
=> Add missing words

docs/parameters.md, versioned_docs/version-4.0/parameters.md
See
https://github.com/rabbitmq/rabbitmq-server/blob/cb4676da8880579922c92cf8ade546a86c84cf52/deps/rabbit/src/rabbit_quorum_queue.erl#L335
=> Document overflow resolution for QQs

docs/parameters.md, versioned_docs/version-4.0/parameters.md
See
https://github.com/rabbitmq/rabbitmq-server/blob/cb4676da8880579922c92cf8ade546a86c84cf52/deps/rabbit/src/rabbit_stream_queue.erl#L1091-L1096
=> Update resolution for streams

blog/2025-04-16-amqp-websocket/index.md
Thanks to Johan for these corrections!
=> Small fixes on Web AMQP blog post

docs/cluster-formation.md, docs/install-kubernetes-diy.md, sidebarsDocs.js, versioned_docs/version-4.1/cluster-formation.md, versioned_docs/version-4.1/install-kubernetes-diy.md, versioned_sidebars/version-4.1-sidebars.json
Update k8s peer discovery to 4.1
Move Kubernetes DIY guidelines to a separate page
=> Update Kubernetes related docs

docs/http-api-reference.md, versioned_docs/version-4.1/http-api-reference.md
This is the companion change to https://github.com/rabbitmq/rabbitmq-server/pull/13871 which enables requesting multiple protocols in the health check.
Connects https://github.com/rabbitmq/rabbitmq-server/issues/13782
=> Update protocol-listener health-check docs to support multiple protocols

docs/http-api-reference.md
This is the companion change to https://github.com/rabbitmq/rabbitmq-server/pull/13872
Connects https://github.com/rabbitmq/rabbitmq-server/issues/13782
=> Document the new is-in-service health-check API call

client-libraries/amqp-client-libraries.md
Cover how to set the filter value in outbound messages and insist on stream filtering logic for inbound messages.
=> Improve stream filtering support in AMQP library page

src/pages/contact.js, src/pages/index.module.css
Add a featured partner section to the support page:
=> [RMQ-1746] Add featured partner section

package-lock.json, package.json
It's a work-in-progress [1] but our website is
large enough for us to be seriously interested in early
adoption of this initiative soon-ish.
Let's start by adding a dependency and keeping
an eye on this set of features and dependency
[configuration] updates.
1. https://github.com/facebook/docusaurus/issues/10556
=> Add a @docusaurus/faster dependency

versioned_docs/version-4.1/http-api-reference.md
Replace "aliveness-check" with "aliveness-test"
=> Update the obsolete endpoints section

src/pages/commercial-features.js, src/pages/index.module.css
We have already added support timelines to the support page. Also add this to the commercial features page per changes request doc
=> [RMQ-2107] Add support timelines to the commercial features page
