rabbitmq/rabbitmq-website

site/networking.xml

Note: I know you said it should put it to the TLS section, but there is only a general introduction, which is *before* to the timeout section. I thought it may be better to talk about TLS handshake afterwards.

On slow links the ssl_handshake_timeout may need to be increased.

---

site/clustering-hostname-issues.xml.inc

`RABBITMQ_USE_LONGNAME` documentation
https://github.com/rabbitmq/rabbitmq-website/blob/master/site/configure.xml#L228
mentions EC2, but there's no mention of it in the ec2.xml.   This fixes that.

Add reference useful environment variable USE_LONGNAME

---

site/clustering-hostname-issues.xml.inc

`RABBITMQ_USE_LONGNAME` documentation
https://github.com/rabbitmq/rabbitmq-website/blob/master/site/configure.xml#L228
mentions EC2, but there's no mention of it in the ec2.xml.   This fixes that.

Add a reference to a useful environment variable USE_LONGNAME

---

site/api-guide.xml

Use properties.getContentType() instead of properties.contentType
https://www.rabbitmq.com/releases/rabbitmq-java-client/current-javadoc/com/rabbitmq/client/AMQP.BasicProperties.html#getContentType%28%29
properties.contentType is private field and is not accessible this
way in Java.
Note:
I did not submit Contributor Agreement but I assume that this change is trivial so Contributor Agreement is not required.

fix Java sample - access to properties

---

site/which-erlang.xml

References rabbitmq/rabbitmq-server#250.

RabbitMQ 3.6.0 requires Erlang R16B03-1

---

site/pages.xml.dat

Sometime it's not easy (for me) to find a link to the right
Erlang client documentation. I'd add more links to the website
so that I don't search so long next time.

Added more 'Related Links' for Erlang client

---

site/java-client.xml

Resolve issue #75.
Remove last slash in url which break link generation.

Repair link to Java client GitHub repository

---

site/clustering.xml

Describe how to use the shipped OCF script for a
Pacemaker resource agent to configure an A/A cluster
with dynamic nodes' membership.
Signed-off-by: Bogdan Dobrelya <bdobrelia@mirantis.com>

Auto-configuration of a cluster with a Pacemaker

---

site/pacemaker.xml

* Provide precise example commands to create multi-state resource
for the RabbitMQ HA resource agent in Pacemaker.
* Provide the example commands in both pcs and crm tools notations.
* Describe the way to get meta-data parameters of the
OCF scripts via the command line (just to not duplicate
maintaning them in the guide and the script ot once)
Signed-off-by: Bogdan Dobrelya <bdobrelia@mirantis.com>

Add more details for the HA OCF resource creation

---

site/build-java-client.xml

They've become invalid after 0d1b2bd0e84b8f77b2f62d4ee90983458baef02d to
rabbitmq-java-client, which mentions that erlang.mk-layout is now used
by default.
Fixes #102

Update java client build instructions

---

site/configure.xml

Consider HiPE on erlang 17.x to be stable. https://github.com/rabbitmq/rabbitmq-server/issues/58

HIPE recomendation updated.

---

site/pacemaker.xml

* Specify that the page consist of two parts:
- A/P configuration and A/A with mirrored queues using Pacemaker OCF RA
* Describe the /usr/lib/ocf/resource.d/rabbitmq/set_rabbitmq_policy.sh
file for advanced configuration of mirrored queues
* Do not use interleaved clones in examples as there is no need for that
Signed-off-by: Bogdan Dobrelya <bdobrelia@mirantis.com>

Advanced mirrored queues configuration options

---

site/feed-atom.xsl
site/news.xml

This PR does a few things to ensure that the [currently invalid Atom feed](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.rabbitmq.com%2Fnews.atom) is made valid. The feed started out with the following list of warnings:
```sh
$ python src/demo.py http://localhost:8191/news.atom
Validating http://localhost:8191/news.atom
line 2, column 0: Use of unknown namespace: http://www.rabbitmq.com/namespaces/ad-hoc/doc
line 2, column 0: Avoid Namespace Prefix: atom
line 2, column 0: Avoid Namespace Prefix: xhtml
line 2, column 168: updated must be an RFC-3339 date-time
line 2, column 0: Missing feed element: title
line 2, column 0: Missing feed element: id
line 2, column 0: Missing atom:link with rel="self"
line 2, column 342: updated must be an RFC-3339 date-time (57 occurrences) …
```

Make the Atom feed valid

---

site/tutorials/tutorial-two-dotnet.md
site/tutorials/tutorial-two-go.md
site/tutorials/tutorial-two-java.md
site/tutorials/tutorial-two-javascript.md
site/tutorials/tutorial-two-php.md
site/tutorials/tutorial-two-python.md
site/tutorials/tutorial-two-ruby.md

Made the wording between the documentation (in semantics.xml) and tutorials regarding redelivering of messages consistent. Fixes #88.

Inconsistency between website documentation and tutorials

---

site/community-plugins.xml

Would you mind adding the CoAP plug-in to the list of community-plugins now so that there is a binary also for RabbitMQ 3.5.x?

Add reference to rabbitmq_coap_pubsub.

---

site/page.xsl

There is a bad link for example at the end of http://www.rabbitmq.com/plugins.html

Fix links to plugin README files.

---

site/plugins.xml

The filename suffix has been changed, but the change was not
reflected here.

Fix README suffix.

---

site/tutorials/tutorial-two-ruby.md

Bunny has deprecated `:ack` in favor of `:manual_ack` (https://github.com/ruby-amqp/bunny/commit/9bfd6fc33bf150cc74423e13628576cb2e102317). More importantly, we don't want the tutorial to suggest that there are different semantics for the two, so we should use one consistently.
Found this a tad confusing myself; hopefully this spares someone else the same. Cheers!

Replace `:ack => true` with `:manual_ack => true` in Ruby tutorial

---

site/confirms.xml

Accessing 
https://raw.githubusercontent.com/rabbitmq/rabbitmq-java-client/master/test/src/com/rabbitmq/examples/ConfirmDontLoseMessages.java 
returned a 404 Not Found. 
Replaced it with 
https://raw.githubusercontent.com/rabbitmq/rabbitmq-java-client/master/src/test/java/com/rabbitmq/examples/ConfirmDontLoseMessages.java
to make it work again.

Replaced broken link to Java example with working one.

---

site/clustering-hostname-issues.xml.inc
site/clustering.xml

Fixes [#158](https://github.com/rabbitmq/rabbitmq-website/issues/158).

Remove an extraneous link and add an in-page anchor to clustering-hostname-issues.

---

site/ssl.xml

This PR updates the SSL guide to use sha265 in the example openSSL config instead of sha1 as sha1 is deprecated.  As users with a weak SSL background may copy the example for production without realizing a weak cipher is in place I believe a strong cipher should be used in the example.
Using sha1 can also be a pain point if the cert is used to sign the management interface, as is the [default in the public RabbitMQ container](https://github.com/docker-library/rabbitmq/blob/d9c4635649edacf6728bd2a28aedc97c77ac47f9/docker-entrypoint.sh#L102-L112) as browsers are now rejecting SHA1 certs.

sha1 is deprecated: Use sha256 in the example OpenSSL config

---

site/install-debian.xml

* Moved `rabbitmq` APT repository to separate sources list
* Changed some installation commands into one-liners to decrease the number of required steps
* Minor instruction enhancements

Use one-liners for quick copy/paste and less traces

---

site/access-control.xml
site/configure.xml
site/disk-alarms.xml
site/how.xml
site/ldap.xml
site/management.xml
site/memory.xml
site/mqtt.md
site/nettick.xml
site/networking.xml
site/partitions.xml
site/passwords.xml
site/plugin-development.xml
site/shovel-static.xml
site/ssl.xml
site/stomp.md
site/web-dispatch.md
site/web-stomp.md

Updates the docs for http://github.com/rabbitmq/rabbitmq-server/issues/550.

Update documentation to cover both new and classic config formats

---

site/networking.xml

There is a syntax error in networking.html page (missing comma after {nodelay, true}):
```
[
{rabbit, [
{tcp_listen_options, [
{backlog,   128},
{nodelay,   true}  
{sndbuf,    196608},
{recbuf,    196608}
]}
]}
].
```

Add missing comma

---

site/networking.xml

Addresses [Issue #173](https://github.com/rabbitmq/rabbitmq-website/issues/173), and cleans up some stray whitespace.

Add comma to TCP buffer size block

---

site/tutorials/tutorial-three-python.md

There was a typo in the doc **the the** in
```
The exchange parameter is the the name of the exchange.
```
This PR fixes that only.

Tutorials: Update Part 3 Python tutorial

---

site/java-tools.xml

Added some information about difference in queues and consumers with `-u queue_name` and without it.
Fixes #185
Maybe there are something more to be added?

Difference in PerfTest topology with or without queue name

---

site/resources/specs/amqp0-9-1.extended.xml

[doc] Fix a typo in the AMQP guide

---

site/tutorials/tutorial-two-dotnet.md
site/tutorials/tutorial-two-elixir.md
site/tutorials/tutorial-two-go.md
site/tutorials/tutorial-two-javascript.md
site/tutorials/tutorial-two-php.md
site/tutorials/tutorial-two-python.md
site/tutorials/tutorial-two-ruby.md

Issue #180
Also, move ack below work in Go tutorial 2 - Issue #181
Correct prose used with node client, as this client defaults to noAck:
false (requiring manual acknowledgment).
See http://www.squaremobius.net/amqp.node/channel_api.html#channel_consume
[#117326341]
[#117326391]

Tutorial 2 corrections

---

site/tutorials/tutorial-three-php.md
site/tutorials/tutorial-three-ruby.md

also correct a spelling mistake.
Fixes #192

tutorial three - remove mention of routing keys for ruby and php

---

site/tutorials/tutorial-five-objectivec.md
site/tutorials/tutorial-four-objectivec.md
site/tutorials/tutorial-one-objectivec.md
site/tutorials/tutorial-three-objectivec.md
site/tutorials/tutorial-two-objectivec.md

Also:
- Correct a call to outdated `createChannelWithError`
- Fix a part-untranslated method name that still contained an
underscore.
[#120637007]

Update ObjC tutorials for v0.7

---

site/nightly-builds.xml

Update .NET client nightly link to point to AppVeyor NuGet feed

---

site/tutorials/tutorial-one-javascript.md

Replace deprecated `new Buffer` instantiation brought up in [#230](https://github.com/rabbitmq/rabbitmq-website/issues/230).

Fix tutorial-one-javascript. Close #230

---

site/css/rabbit.css
site/page.xsl
site/trademark-guidelines.xml
wordpress-theme/footer.php

* Move to a two line footer
* Move open source and hiring link to top line, use spring.io's
Copyright line.
[#127911299]

Add trademark guidelines, reorganise footer.

---

site/management.xml

I read the documentation and attempted to apply updated sample_retention_policies to the rabbitmq_management plugin.
Using the current documentation, I (incorrectly) made basic, detailed and global at the first level under rabbitmq_management.
I wondered why it wasn't working, and a `rabbitmqctl environment` showed:
```
{rabbitmq_management,
[{basic,[{605,5},{3600,60},{29400,600},{86400,1800}]},
{cors_allow_origins,[]},
{cors_max_age,1800},
{detailed,[{10,5}]},
{global,[{605,5},{3600,60},{29400,600},{86400,1800}]},
{http_log_dir,none},
{listener,[{port,15672}]},
{load_definitions,none},
{process_stats_gc_timeout,300000},
{rates_mode,basic},
{sample_retention_policies,
[{global,[{605,5},{3660,60},{29400,600},{86400,1800}]},
{basic,[{605,5},{3600,60}]},
{detailed,[{10,5}]}]}, …
```

Make configuration of sample_retention_policies clearer

---

site/ssl.xml

Add `domainComponent = optional` in the `[ testca_policy ]` section of the openssl.cnf. Otherwise ssl/tls connections will fail in some cases. 
See also:
* https://groups.google.com/forum/#!topic/rabbitmq-users/uwRLaKqpha0
* https://github.com/michaelklishin/tls-gen/

Fix: Add missing option in example openssl.cnf

---

site/download.xml
site/install-rpm.xml

[rabbitmq-server#932](https://github.com/rabbitmq/rabbitmq-server/pull/934) Changes required for the changes in: rabbitmq/rabbitmq-server#934) changes the name of the rpm package(s). This PR is for the website to match the changes.

website changes to change rpm package filenames

---

site/pacemaker.xml

See the following PR for the reasoning:
https://github.com/rabbitmq/rabbitmq-server/pull/942

In Pacemaker guide do not suggest to run the second monitor

---

site/uri-query-parameters.xml

It seems like a typo, or may be outdated example.

Fix example for auth parameter name in URI Query Parameters specification

---

site/tutorials/tutorial-two-javascript.md

~~When you use same queue name of the tutorial one, you get problems because the queue already exists.~~
~~See the image below to view the error that occurred when I tried to run the tutorial two with the same queue name as the tutorial one.~~
EDIT: The real issue was with the durable argument, but, I think that is better to show this line as well as the code in the tutorials repo.
https://github.com/rabbitmq/rabbitmq-tutorials/blob/master/javascript-nodejs/src/worker.js#L7
If this change is "insignificant" for a PR, just tell me and I cancel.

Adding queue name in the javascript tutorial two code example

---

site/getstarted.xml

Not sure if you're interested, but I recently went through the getstarted tutorial in Perl using a different module.

Add link to tutorial using Net::AMQP::RabbitMQ

---

site/configure.xml

Add documentation for `lazy_queue_explicit_gc_run_operation_threshold` 
( rabbitmq-server/pull/978/ )
The param name is a bit long, so it is in 2 lines

Add documentation for lazy_queue_explicit_ gc_run_operation_threshold

---

site/contact.xml
site/release-notes/README-1.1.0-alpha.txt
site/release-notes/README-1.5.0.txt
site/release-notes/README-1.5.1.txt
site/release-notes/README-1.5.2.txt
site/release-notes/README-1.5.3.txt
site/release-notes/README-1.5.4.txt
site/release-notes/README-1.5.5.txt
site/release-notes/README-1.6.0.txt
site/release-notes/README-1.7.0.txt
site/release-notes/README-1.7.1.txt
site/release-notes/README-1.7.2.txt
site/release-notes/README-1.8.0.txt
site/release-notes/README-1.8.1.txt
site/release-notes/README-2.0.0.txt
site/release-notes/README-2.1.0.txt
site/release-notes/README-2.1.1.txt
site/release-notes/README-2.2.0.txt
site/release-notes/README-2.3.0.txt
site/release-notes/README-2.3.1.txt
site/release-notes/README-2.4.0.txt
site/release-notes/README-2.4.1.txt
site/release-notes/README-2.5.0.txt
site/release-notes/README-2.5.1.txt
site/release-notes/README-2.6.0.txt
site/release-notes/README-2.6.1.txt

... by <rabbitmq-sales@pivotal.io>.
We must use a @pivotal.io address directly because the rabbitmq.com MTA is not allowed to relay emails to pivotal.io when the email sender's domain has a restrictive SPF record (`-all`).
[#131102253]

Replace <support@rabbitmq.com> and <sales@rabbitmq.com>

---

site/api-guide.xml
site/build-java-client.xml
site/download.xml
site/java-client.xml
site/rabbit.ent

Fixes #288
This PR changes Java-related links to point to Maven Central instead of the `releases/rabbitmq-java-client` directory (for binaries, Javadoc, sources).
The binary/source distribution archives (`zip`/`tar.gz`) no longer appear in the links.
Build instructions are also updated to use Maven.

Update Java Client doc after separate distribution

---

site/autoclustering.xml
site/clustering.xml
site/pages.xml.dat

Which documents automatic cluster formation procedure and
the pluggable peer discovery mechanisms introduced in 3.7.0.
Part of https://github.com/rabbitmq/rabbitmq-server/issues/988 as well as https://github.com/rabbitmq/rabbitmq-server/issues/486.

New guide: Cluster Formation

---

site/installing-plugins.xml

This PR updates the documentation for OS X user with Homebrew to reflect a current version of the software.
- Example value for the .ez files folder `/usr/local/Cellar/rabbitmq/3.6.4/plugins`

Installing Plugins page: Update location Homebrew's rabbitmq plugin folder

---

site/mqtt.md
site/parameters.xml

Part of rabbitmq/rabbitmq-mqtt#73

Document MQTT cert/vhost mapping

---

site/relocate.xml

The variable is unused because plugins are not expanded anymore. .ez files are used directly.

Remove mentions of $RABBITMQ_PLUGINS_EXPAND_DIR

---

site/tutorials/tutorial-six-elixir.md

* Fix typo in first snippet
* Adjust column width of code snippets so that it doesn't overflow

Fix elixir RPC tutorial

---

site/amqp-0-9-1-errata.xml

This was mentioned on the mailing list in the past, and the behaviour
definitely surprised me, capturing it here for posterity.

Explain when an auto-delete queue will not be deleted

---

site/ldap.xml

And worker pool size option as well.
References rabbitmq/rabbitmq-auth-backend-ldap#7

Document LDAP plugin idle timeout option

---

site/persistence-conf.xml

**What has changed:**
- updated documentation to reflect the fact that the default number of async threads is now 64 (as opposed to 30)
**Why**
- The default number of async threads was bumped to 64 from 30 in this pull requests;       
1. https://github.com/rabbitmq/rabbitmq-server/pull/212 
2. https://github.com/rabbitmq/rabbitmq-server/pull/704

fix documentation to show that the default number of async threads is 64

---

site/memory.xml

The original "blocks all connections" is a bit misleading, as it implies that the connections are blocked indiscriminately.

Clarify memory alarm description

---

site/web-stomp.md

No longer mention port option (use only the port option
in tcp_options section). Update/add links to Ranch and
Cowboy documentation.
References rabbitmq/rabbitmq-web-stomp#69

Update and polish Web Stomp plugin documentation

---

site/tutorials/tutorial-one-php.md

AMQPMessage::DELIVERY_MODE* constants used in the tutorials are not introduced in php-amqplib until 2.6.1.

Update required php-amqplib version.

---

site/dlx.xml

I wasn't sure if `x-death` entries were sorted in any way, but found the discussion at https://github.com/rabbitmq/rabbitmq-server/pull/79 and it seems they are sorted by the last time a {queue, reason} happened. This might be useful information for the website.

Explain x-death entries are sorted chronologically

---

site/build-server.xml

The previous section is therefore entirely removed. The README in the repository is up-to-date and we shouldn't duplicate the documentation, because of the risk of diverging instructions.
[#143115945]

build-server.xml: Point to rabbitmq-server-release/README.md for package building

---

site/tutorials/tutorial-three-php.md

The `routing_key` [seems to be](https://github.com/php-amqplib/php-amqplib/blob/cb0433a8d1ab2d7952ae02bc7433ad181a0f1446/PhpAmqpLib/Channel/AMQPChannel.php#L1098) the third parameter, not the second.

Fix a typo in a PHP tutorial

---

site/passwords.xml

This PR adds a "Password Generation" section with details about the algorithm to generated a correctly salted + hashed password.
Originally part of rabbitmq/rabbitmq-management#386
Screenshot of changes in Chrome 58 on Linux:

Password generation details

---

site/css/rabbit.css
site/pages.xml.dat
site/rabbitmq-echopid.8.xml
site/rabbitmq-env.conf.5.xml
site/rabbitmq-plugins.8.xml
site/rabbitmq-server.8.xml
site/rabbitmq-service.8.xml
site/rabbitmqctl.8.xml

The generated HTML manpages only have the content, not the `<head>` and `<body>` elements. We include those HTML chunks in XML files to render the final HTML pages.
This depends on rabbitmq-server#1201 which must be merged first.
[#143563295]

manpages: HTML conversion is done by rabbitmq-server/Makefile

---

site/api-guide.xml

Covers the default trust manager (which trusts every certificate)
and the risk to use it in production. Add references to
the TLS guide.
References rabbitmq/rabbitmq-java-client#229

Add TLS section in the Java client guide

---

site/configure.xml

Mention RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS as the correct environment
variable for overwriting `+K true` default flag
re rabbitmq/rabbitmq-server#1240

Update default RABBITMQ_SERVER_ERL_ARGS

---

site/uri-query-parameters.xml

And correct the tabular description of `connection_timeout`. It appears from testing and https://www.rabbitmq.com/releases/rabbitmq-erlang-client/v3.6.10/doc/amqp_connection.html that `connection_timeout` is in fact a millisecond, not second, value.

Correct the description example URI

---

Makefile

Cloning the public umbrella and running `make distclean` errors out because this Makefile does not have that target.
@michaelklishin let me know if `stable` is the correct base. I'll correct it if not.

Add distclean target

---

site/tutorials/tutorial-two-php.md

Change example code in tutorial two php in order to match the tutorial flow.
Now, the sample code is already incorporating changes/improvements that are suggested during the tutorial. So the sample codes are more complex and hard to understand for learners like me. The tutorial suggests changes that are already incorporated in the starting sample code, which makes no sense. Moreover, the sample code as it is now does not work, as it uses a queue called 'task_queue' which is not initialized (in tutorial 1 we called the queue 'hello').

Change example code in tutorial two php

---

site/resources/specs/amqp0-9-1.extended.xml
site/resources/specs/amqp0-9-1.xml

The limit imposed (especially on exchange and queue names) is quite important to know. From the type name alone one can imagine that it is short, but not the exact limit.

Add shortstr limit to domain types

---

site/install-windows.xml

If you install Erlang using a non-admin account, and then run the RabbitMQ installer, the installer will not find the expected registry key.
See rabbitmq/rabbitmq-server#1017

Install Erlang using administrative account

---

site/tutorials/tutorial-three-spring-amqp.md

It is pointing to the wrong url (To the Receiver code, instead of the Sender
code).

Fixed "typo" on Tut3Sender java code link

---

conf/www.rabbitmq.com-common

Search google for `rabbitmq-server.1.man.html` and click on some of the links. You'll be redirected. Do the same for `rabbitmq-env.conf.5.man.html`

Add redirects for manual pages

---

site/ssl.xml

On the SSL page of the website (https://www.rabbitmq.com/ssl.html), the result of a command should be commented and the next command should not be commented. I've reversed these so they are displaying correctly.

Uncomment valid command in ssl doc

---

site/admin-guide.xml
site/clustering.xml
site/css/rabbit.css
site/documentation.xml
site/pages.xml.dat
site/upgrade.md
site/which-erlang.xml

Moved upgrade instructions from clustering guide to a new page.

Rabbitmq upgrade guide

---

site/how.xml

The author of "Generating Thousands of PDFs on EC2 with Ruby" reposted it on his blog.

Replace broken link about use as a job queue

---

site/mqtt.md

Also remove note about restarting RabbitMQ after enabling the plugin.
Fixes #469

Add note about guest account and loopback_users

---

site/access-control.xml
site/authentication.xml
site/passwords.xml

This started an an attempt to document https://github.com/rabbitmq/rabbitmq-server/pull/1466 and friends but since we didn't have a lot of docs around the topic of passwordless users or x509 certificate authentication, I decided to add a couple of sections around the topic.

Document passwordless users and their upcoming limitations in 3.7.3

---

site/configure.xml

Default heartbeat is 60 since v3.5.5 (rabbitmq/rabbitmq-server@c7af785)

Default heartbeat is 60

---

site/configure.xml

Quick edit for a typo in the documentation

typo on documentation

---

site/access-control.xml
site/clustering.xml
site/css/rabbit.css
site/ec2.xml
site/install-generic-unix.xml
site/install-windows.xml
site/installing-plugins.xml
site/page.xsl

Currently there are anchors, but no links to get the anchors from.
Make it easier to link to specific sections by turning section
headings into links.

XSLT: Make all headings for named sections into links

---

site/lazy-queues.md

If message embedding is disabled, user should plan to
have more disk space and increase file size limit.
[#154284256]

Mention disk and file descriptor usage when disabling message embedding.

---

site/amqp-0-9-1-quickref.xsl
site/documentation.xml
site/dotnet.xml
site/download.xml
site/how.xml
site/pages.xml.dat
site/rabbit.ent
site/ssl.xml

Remove invalid links, and ensure API links point to https://rabbitmq.github.io/rabbitmq-dotnet-client
[154399066]
See rabbitmq/rabbitmq-dotnet-client#390

Update links for .NET client api docs

---

site/rabbit.ent

Fixes rabbitmq/rabbitmq-server-release#77

Set Erlang version to 20.2.3 for MacOS standalone package

---

site/tutorials/tutorial-one-ruby.md

Matching the variable name to the example above.

Typo on variable name - tutorial-one-ruby.md 

---

site/build-erlang-prerequisites.xml.inc

Strictly speaking at the moment the build process requires 1.6.0 or newer, but I didn't want to be over-specific (which would just require constantly updating the docs)

[Obvious Fix] Mention that the build process requires Elixir

---

site/web-mqtt.md

I used the Paho example code for the Web-MQTT plugin in a project, but in my case the code did not work well with the server's default values (Websocket timeout). If the default keep-alive interval of Paho (60 seconds) is used, the connection is closed by the server after some minutes. After some debugging I changed that interval to 30 seconds and the connection remained stable.
I added this parameter to the example Javascript code on the website in order to save others from this issue.

Added keep-alive interval to Web-MQTT Javascript demo code

---

site/queues.md

I could be wrong (please ignore if I am), but I think the second state of an enqueued message should be 'delivered **but** not yet acknowledged by consumer'.

Fixed potential typo in queue documentation

---

site/shovel-dynamic.xml

I believe this fix is warranted b/c it makes better sense that it would check for the destination queue/exchange on the destination rather than the source.

fix typo.  source -> destination

---

site/upgrade.md

Upgrade compatibility table can be confusing for people planning
the rolling upgrade. Make it clear that the table is for full-stop
upgrades only.
[#157732962]

Mention that full cluster stop is required for minor upgrades.

---

site/which-erlang.xml

Note that I now list 19.3.6.4 as the minimum required. Even though nodes will still run on 19.3 we will ask any pre-19.3.6.4 users to upgrade first since [ERL-430](https://bugs.erlang.org/browse/ERL-430) and [ERL-448](https://bugs.erlang.org/browse/ERL-448) are catastrophic and running into them on affected versions is a matter of time. So this is a strong recommendation stated as a requirement, not a breaking change.
References rabbitmq/rabbitmq-server#1616.
[#157964874]

Update Supported Erlang versions guide to mention OTP 21

---

site/man/rabbitmq-server.8.html

The flag `--detached` is ignored by `rabbitmq-server`.  The documentation should consistently use the correct `-detached` flag.  All other occurrences that I could find (including the man page) are correct.

Flag is `-detached` not `--detached`

---

site/devtools.xml

I've added a link to the rabtap tool (RabbitMQ wire tap and swiss army knife; https://github.com/jandelgado/rabtap)

Add link to rabtap cli tool

---

site/tutorials/tutorial-one-go.md

In [part 2](https://github.com/rabbitmq/rabbitmq-website/blob/live/site/tutorials/tutorial-two-go.md), the document described `In the previous part of this tutorial we sent a message containing "Hello World!".`

Fix typo in tutorials

---

site/management.xml

In the section "HTTP Request Logging" there is a note stating that RabbitMQ only logs requests to the `/api` endpoint. This is not correct as Rabbit also logs requests to static files. 
This PR also includes an example with the configuration using new and classic format.

Remove the note in Management plugin HTTP logging

---

Makefile
Pipfile
Pipfile.lock

Resolves all dependencies, tested on macOS 10.13 & Arch Linux 2018.09.01
I had this sitting in #546 for too long now, it was high time to split out and submit on its own.

Preview the website locally with a single command: make preview

---

site/api-guide.xml
site/ssl.xml

References rabbitmq/rabbitmq-java-client#394

Document hostname verification for Java client

---

site/reliability.xml

Was still referencing "unsynchronised slaves" which was renamed to "unsynchronised mirrors"
Adjusted anchor link, as well as naming in text.

reliability fix link to unsynchronised mirrors

---

site/cluster-formation.xml

References rabbitmq/rabbitmq-peer-discovery-consul#16, scheduled to be deployed life after the `3.7.9` release.
While at it, document cluster_formation.{consul,etcd}.{lock_timeout,lock_wait_time}.
This depends on
* rabbitmq/rabbitmq-peer-discovery-consul#20
* rabbitmq/rabbitmq-peer-discovery-etcd#16
[#160674959]

Document cluster_formation.consul.lock_prefix

---

site/access-control.xml

Linked from https://www.rabbitmq.com/access-control.html to https://www.rabbitmq.com/rabbitmqctl.8.html#Access_Control

Fix anchor tag reference

---

site/amqp-wireshark.xml
site/ssl.xml
site/web-mqtt.md

This focusses the cipher suite section on the OpenSSL format which is the only option for the new style config format (but can also be used with classic configs), so we want to encourage it.

TLS guide: more adaptation to rabbitmq/rabbitmq-server#1712

---

code/render.py

Not using them can make generation fail on some environments.
Happened to me on a new environment (Python 3.6.7, Python Markdown 3.0.1), got the code from [the Python Markdown documentation](https://python-markdown.github.io/reference/), tested on our staging instance.

Use keyword arguments for Markdown generation

---

site/cluster-formation.xml

According to the code of the [etcd peer discovery plugin](https://github.com/rabbitmq/rabbitmq-peer-discovery-etcd/blob/07571d1e9d714236187852f58dfcec0021272d29/priv/schema/rabbitmq_peer_discovery_etcd.schema#L74), the correct parameter is `cluster_formation.etcd.node_ttl` (not `cluster_formation.etcd.ttl`, which raises an error when used on RabbitMQ 3.7.8)
(Obvious Fix)

Fixing incorrect etcd TTL parameter

---

site/partitions.xml

Start the chapter with the info, that a cluster might be used for different purposes and therefore has to be tuned accordingly.
Introduce the word split-brain and use it where appropriate for increased clarity (i.e. recovering from a split-brain).
Use datacenter instead of AZ (availability zone), but reference it to have a well known example of the expected network reliability.
I claim that "pause_minority" prevents split-brain during network partitions. In our tests this proofed correct. Please correct me, if this claim is wrong (let's keep the "suspend" an exception, as it is not really the network partition we try to protect against in HA setups).

additional clarity for cluster_partition_handling

---

site/ssl.xml

changed "none" to "verify_none"
"none" is not a valid value for "verify" option

"none" → "verify_none"

---

site/api-guide.xml

There was a minor typo, appearing three times, in the [Java Client API Guide](https://www.rabbitmq.com/api-guide.html). An extra closing bracket was added after _AMQP.BasicProperties.Builder().build()_.

Removed wrong closing brackets

---

site/networking.xml

Reverts rabbitmq/rabbitmq-website#642 becausee it was meant to be submitted against `stable`.

Revert "Documentation example for rabbitmq/rabbitmq-server#1784"

---

site/devtools.xml

Hi! 👋 
I'm part of the team which created Bunnicula (you can [read the backstory here](https://blog.nomnominsights.com/bunnicula-asynchronous-messaging-with-rabbitmq-for-clojure/) - and I'd like to share it with the broader community. 
Internally we've been using it for over a year and lost count of how many jobs have been processed ;-)
Thanks

Add Bunnicula (a Clojure client) to devtools page

---

site/devtools.xml

Is it OK to add [Rascal](https://github.com/guidesmiths/rascal) to the list of JavaScript dev tools? Thanks.

Add Rascal to JavaScript Clients & Developer Tools

---

site/tutorials/tutorial-one-elixir.md

While going through the tutorial I noticed that the `Receive` section of the Elixir tutorial was duplicated. Furthermore, there was no explicit declaration to work on the `send.exs` script, as there is in other tutorials (see [python tutorial](https://www.rabbitmq.com/tutorials/tutorial-one-python.html)).
This simply clears out the duplication and makes the first Elixir tutorial more like the other tutorials.
---
~_I assume for this trivial change no Contributor Agreement is required, please correct me if I'm wrong and I'll follow up ASAP_~ (the PR hooks knew better :) )

Deduplication of receive paragraph

---

site/mqtt.md

These fixes are obvious copy/paste typos.
Co-authored-by: George Blue <gblue@pivotal.io>

Fix copy/paste typos in MQTT plugin doc

---

site/tutorials/tutorial-one-ruby.md

Why: so it makes sense grammatically. 
Part of the explanation was missing

Fix explanation of consumer

---

site/ssl.xml

I suggest we change this wording about certificate format requirements for .NET clients accessing a RabbitMQ server using TLS. This makes it sounds like the certificate on any server that a .NET client will access cannot be PEM, which is not the case. I was able to connect to a .NET client to a RabbitMQ server running on Linux using a PEM certificate. I'm not sure if this current wording means that the *client* certificate on .NET clients (for peer verification going the other way, server authenticating client) can't be PEM, or in the case of the server being a .NET server using mono, then the server certificate can't use PEM. I assumed the former and made the change accordingly. If it is the latter, then I suggest we break out a separate "Setting up a .NET/Mono server for TLS" section …

Fixing wording about certificates on a .NET client for TLS

---

site/access-control.xml

Obvious fix.
Replace ```and but``` with ```and``` on 
> "use LDAP backend for authentication **and but** internal backend for authorisation"

Fix typo on access-control.xml

---

site/install-debian.xml

- The repository definition line example is misleading: the right component name for rabbitmq-erlang is "erlang".
The example is also missing RabbitMQ repository definition.
- In order for apt to be able to download RabbitMQ and Erlang packages from Bintray, the *apt-transport-https* package must be installed.

Fix for repository definition, apt https transport

---

site/devtools.xml

We just released our RabbitMQ broker definition visualization tool and would like to add it the list of dev tools on the website.

Add link to rabbit viz dev tool

---

site/confirms.xml

"but doesn't yet ack it," -> means it is in confirms mode

fix documentation

---

site/tutorials/tutorial-two-elixir.md
site/tutorials/tutorial-two-python.md

Change other occurrences of 'customer' to 'consumer'.
Note: There's a merge and another commit, because I used tilda (`) in the commit message the first time and it turned into a space.

Fix typo from 'customer' to 'consumer'

---

site/clustering.xml

The documentation randomly switches from `rabbit1` to `mcnulty` and then back. Let's clean up that inconsistency.
This is a pretty trivial change, so I don't _think_ a contributor agreement is necessary.

Use consistent example host names in clustering guide

---

site/tutorials/amqp-concepts.xml

`x-*` headers are not used for matching.
Fixes #701

Add note about x- headers

---

site/how.xml
site/logging.md
site/management.xml
site/memory.xml
site/ssl.xml
site/tutorials/amqp-concepts.xml
site/tutorials/tutorial-three-dotnet.md
site/tutorials/tutorial-three-elixir.md
site/tutorials/tutorial-three-java.md

Reading through the docs and came across instances where "the the" was used.

Removing duplicate "the the" occurrences.

---

site/install-rpm.xml

Sorry for all these PR(s), but I didn't know about `obs://`. 
`obs://` extracts the http url for the matching distro.
So it is not necessary to specify the distro, this make the life
easier also for automated tools as chef, ansible etc

Change http to obs for repositories URL

---

site/tutorials/tutorial-two-spring-amqp.md

A couple of documentation updates:
- To simulate round-robin behaviour for AMQP `prefetchCount` must be = 1 but not 0.
- Even there is a default still `prefetchCount` can be changed.

(documentation): set prefetch count = 1 to force round-robin behaviour

---

site/community-plugins.xml

Released v0.3.0 today. May as well use GitHub releases instead of bintray

Update release URLs for rabbitmq_email

---

site/devtools.xml

Hi! I'm the author of amiquip, and was wondering if it could be added to the devtools list of third-party clients. The biggest difference between it and lapin is that lapin is written for futures, and amiquip is not; there are several other less significant differences, of course.
Thanks!

Add amiquip Rust client to devtools

---

site/tutorials/tutorial-two-python.md

The tutorial missed parenthesis and had a typo, I added back the parentheses

Add Parenthesis and Fix typos

---

site/tutorials/tutorial-five-javascript.md
site/tutorials/tutorial-four-javascript.md
site/tutorials/tutorial-one-javascript.md
site/tutorials/tutorial-six-javascript.md
site/tutorials/tutorial-three-javascript.md
site/tutorials/tutorial-two-javascript.md

In order to understand more when learning RabbitMQ, we could enhance the variables' names to get a clear vision about different element and the relation between them.
So, instead of declaring `q` we could name it `queue` which is more expressive and helps a person to get the info and understand the principle faster.

Update the example code

---

site/prometheus.md

This adds a note regarding the path for the metrics endpoint when using a custom `mgmt` path prefix.

Prometheus exporter docs: Add mgmt prefix note

---

site/confirms.xml

Stumbled upon what I think is a typo regarding the prefetching window.
In the example the next unacknowledged index is `5` and not `8` (which is the last) and I assume the intention is to exemplify using `delivery_tag` set to `5`?
“Obvious Fix”

Clarifies delivery_tag index

---

site/tutorials/tutorial-five-go.md
site/tutorials/tutorial-four-go.md
site/tutorials/tutorial-one-go.md
site/tutorials/tutorial-six-go.md
site/tutorials/tutorial-three-go.md
site/tutorials/tutorial-two-go.md

In golang, if the import is not used, the code will not compile successfully.
So the "fmt" in the golang sample code must be removed, then it can be compiled successfully.

MOD: fix build error in golang tutorial code

---

site/queues.md

Update an incorrect link to the _Message Ordering_ section in the queues.md page.
Reading briefly about the master -> stable -> live branch hierarchy, it seems the master branch was the correct branch to merge into. If there are any problems with my PR I would be glad to close this and create a new one.
Thanks!

Update incorrect link to Message Ordering

---

site/connections.md

This corrects "In for" => "In order for" on the connections page of the docs site

fix typo on connections page

---

site/tutorials/tutorial-two-javascript.md

This PR adds minor change in NodeJS example. To keep up with the tutorial parameters naming and to be more easier for beginners, the sendToQueue `q` parameter is renamed to follow the naming `queue` as in the whole tutorial.

Use queue name as a parameter in sendToQueue

---

site/tutorials/tutorial-two-javascript.md

Maintains consistency with Part1 and uses current Buffer API instead of `new Buffer`, which is deprecated

replace `new Buffer` with `Buffer.from`

---

site/ssl.xml

The CA certificate name specified in openssl.cnf was different from the one in the openssl commands and thus led to errors.

Fix wrong CA certificate name in ssl manual certificate generation guide

---

site/configure.md
site/ldap.xml
site/logging.md
site/management.xml
site/mqtt.md
site/release-notes/3.7.9.md
site/ssl.xml
site/stomp.md
site/uri-query-parameters.xml
site/web-mqtt.md
site/web-stomp.md

Consistently use file names that would be generated by https://github.com/michaelklishin/tls-gen.git
[166742920]
See #785 too

Review x509 file names used in docs

---

site/interoperability.xml

Trivial changes, fix a broken link about the python testing suite in the QPid documentation

Fix a broken link in the QPid documentation

---

site/management-cli.md

As mentioned in this discussion:
https://github.com/rabbitmq/rabbitmq-management/issues/521#issuecomment-504917401
By the way, are there any (separate) docs for the rabbitmqadmin python app? Have you considered releasing the app to pypi.org; and maintaining documentation on e.g read-the-docs?

Docs: Correct syntax to get a message with no requeue

---

site/install-debian.xml

Avoid using keyserver in shell snippet (as already done in https://github.com/rabbitmq/rabbitmq-website/commit/399453e29fa192fa6d2d3e545b55534db5ac3f3a).

Avoid using keyserver in shell snippet

---

site/ec2.xml

Fix typo in Amazon EC2 guide

---

site/tutorials/tutorial-five-php.md
site/tutorials/tutorial-four-php.md
site/tutorials/tutorial-one-php.md
site/tutorials/tutorial-six-php.md
site/tutorials/tutorial-three-php.md
site/tutorials/tutorial-two-php.md

AMQPChannel::$callbacks was marked as @Internal in php-amqplib/php-amqplib@f30adba and AMQPChannel::is_consuming() public API was introduced to replace it.

remove deprecated stuff in php tutorial

---

site/clustering.md

The ports '5672, 5671' were not visible in a line of their own. This may cause users skimming over the content to miss it.

Minor fix to layout in the section Port Access

---

site/tutorials/tutorial-one-python.md

Prefer to use pip as a module, it's avoid error and mistakes during
package installation. With this approach we are always sure to
to install dependencies in the right python environment.

Ensure to always use pip as a module of a given version of python

---

site/css/tutorial.css
site/tutorials/tutorial-seven-java.md
site/tutorials/tutorials-menu.xml.inc

Goes with https://github.com/rabbitmq/rabbitmq-tutorials/pull/238.

Add publisher confirms tutorial for Java

---

site/ssl.md

I've seen in other SSL implementations that when no certificate verification depth is specified, it means "unlimited", and I was wrongly assuming this is a standard behaviour. Some long troubleshooting experience taught me that for Erlang, [the default maximum depth is 1](http://erlang.org/doc/man/ssl.html#type-allowed_cert_chain_length).
I suggest extending this paragraph of the documentation taken from Erlang to also include the default value, hoping it will save time for others.
Thanks!

Document default TLS verification depth

---

site/devtools.md

A simple change to add Brighter to the list of .NET Client libraries for RabbitMQ

Add Brighter to list of .NET Client Libraries and Developer Tools

---

site/ssl.md

Some parts of the doc still mention ca_certificate_bundle.pem whereas the rest refers to ca_certificate.pem.
Updated all references to ca_certificate_bundle.pem to make it coherent.

Replace ca_certificate_bundle by ca_certificate

---

site/ldap.md

The LDAP refers to the additional.config file whereas the rest of the doc refers to the advanced.config.

Replace additional.config by advanced.config

---

site/cli.md
site/man/rabbitmq-diagnostics.8.html
site/man/rabbitmq-env.conf.5.html
site/man/rabbitmq-queues.8.html
site/man/rabbitmq-server.8.html
site/man/rabbitmq-service.8.html
site/man/rabbitmq-upgrade.8.html
site/man/rabbitmqctl.8.html
site/manpages.md
site/pages.xml.dat
site/rabbitmq-queues.8.xml
site/rabbitmq-upgrade.8.xml
site/upgrade.md

Document new cli commands and man pages for `rabbitmq-queues`, `rabbitmq-update`
Add diagnostics commands: `consume_event_stream`, `command_line_arguments`
Man pages in https://github.com/rabbitmq/rabbitmq-server/pull/2121

Man pages: rabbitmq-queues, rabbitmq-upgrade and diagnostics updates

---

site/prometheus.md

Replace "close" to "clone".  I believe these are typos.

Fix prometheus.md documentation typos

---

site/cluster-formation.md

Part of rabbitmq/rabbitmq-peer-discovery-consul#34, will tentatively ship with `3.7.20` and `3.8.1`.

Cluster Formation guide: document Consul service metadata

---

site/tutorials/tutorial-two-go.md

When following the tutorial, we are asked to make some edits and then to run and test the changes, before been shown all the code needed. A call to the bodyFrom function is added, but not mentioned right until the bottom of the page. Including it here will help follow the tutorial as we go along. It will make line 144 actually work :-)

Update tutorial-two-go: include code needed to run

---

site/tutorials/tutorial-three-spring-amqp.md

In Spring AMQP Tutorial 3, made minor punctuation and wording changes for greater clarity.

Clarified punctuation and wording

---

site/download.xml
site/getstarted.xml

An attempt to make people use the Docker image to get started, at least on their workstation. I would have liked to have the Docker command to run a one-time RabbitMQ container on each tutorial page, but it seems too pushy.
[#169621594]

Mention Docker to get started

---

site/memory.md

There is an extra backtick in this line:
in this page: https://www.rabbitmq.com/memory.html

docs(memory): Remove extra backtick from memory docs

---

site/which-erlang.md

Based on the release notes, Erlang OTP 19.3.x should still be compatible with 3.7.7 through 3.7.10.
https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.7.7
https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.7.10
Support for Erlang OTP 21.x starts with 3.7.7.
I'm not sure what to put for the notes besides the compatibility notes from rabbitmq-users google group.
@pivotal-issuemaster This is an Obvious Fix

Correct minimum required Erlang version for 3.7.7-3.7.10 releases

---

site/tutorials/tutorial-five-go.md
site/tutorials/tutorial-four-go.md
site/tutorials/tutorial-one-go.md
site/tutorials/tutorial-six-go.md
site/tutorials/tutorial-three-go.md

Fixed typos in golang code examples

Typo fix. usused=>unused

---

site/relocate.md

No longer applies after merge of rabbitmq/rabbitmq-server#2180
See https://github.com/rabbitmq/rabbitmq-common/pull/345

Remove RABBITMQ_GENERATED_CONFIG_DIR

---

site/dotnet-api-guide.xml

At the start of the documentation you see that the **Channel** of type **IModel** is called ```channel``` so it's disturbing to see it called ```model``` just after.

Update dotnet-api-guide.xml, channel should be called channel and not model

---

site/resources/specs/amqp0-9-1.extended.xml

- Add the `no-route` constant for `NO-ROUTE`, `312` soft-error
- Add a doc string for the `Connection.Blocked` `reason` argument
- Change `Confirm.Select` `nowait` to use the `no-wait` domain, removing the need for the duplicated documentation

Minor updates for correctness and missing info

---

site/connection-blocked.md

In the Connection Blocked documentation, the .NET example seems to have an incorrect signature for `HandleBlocked` and `HandleUnblocked`. I'm not sure whether this was intentional so raising this PR in case it was not.
In the case of `HandleBlocked` it was:
```csharp
public void HandleBlocked(IConnection sender, ConnectionBlockedEventArgs args)
```
instead of 
```csharp
public void HandleBlocked(object sender, ConnectionBlockedEventArgs args)
```
Similariy it for `HandleUnblocked` the signature was:
```csharp
public void HandleUnblocked(IConnection sender)
```
instead of
```csharp
public void HandleUnblocked(object sender, EventArgs args)
```

Connection Blocked updates for .NET Client example

---

site/nettick.md

change 'unavilable' to 'unavailable'

Fix typo for 'unavilable'

---

site/tutorials/tutorial-two-dotnet.md

When sending the ack, we should use the channel provided to us by the callback mechanism, not capture it from the outer scope. This lets use e.g. to extract the callback to a separate method.

Use callback arg for acks in worker

---

.gitignore
site/install-windows-manual.md
site/install-windows.md
site/windows-quirks.md

This addresses the uncommon scenario where a user has multiple versions of Erlang installed, and the sort order of the version causes an old version to be used.
https://github.com/rabbitmq/rabbitmq-server-release/issues/117
https://github.com/rabbitmq/rabbitmq-server/issues/1969#issuecomment-583469093
It is not possible to change the behavior in NSIS.
[171866390]

Add note about multiple Erlang versions on Windows

---

site/dotnet.md

On [.NET/C# RabbitMQ Client Library — RabbitMQ](https://www.rabbitmq.com/dotnet.html) page H2 markup was not indented properly causing it to display incorrectly.

Fix  H2 indentation on dotnet client library page

---

site/prometheus.md

I have fixed four typos in the prometheus.md docs at lines 42, 61, 286 and 440

fix typos in prometheus.md

---

site/tutorials/tutorial-one-java.md

This section describes how imports of `Recv.java` differ from imports of `Send.java`. 
> The extra `DefaultConsumer` is a class implementing the `Consumer` interface we'll use to buffer the messages pushed to us by the server.
Imports don't include `DefaultConsumer`, but they include `DeliverCallback`. So there is a typo.

Typo in tutorial-one-java: Replaced DefaultConsumer to DeliverCallback

---

site/install-homebrew.md

* Links are properly created in `/usr/local/sbin/` in current homebrew recipes
* Add info about shell startup and brew services

Update homebrew info

---

site/publishers.md

Remove duplicated point, "Restore connection listeners", from automatic recovery process.

Remove duplicate from automatic recovery process

---

site/clustering.md

There is a general recommendation in the docs to use stateful sets for deploying RabbitMQ on Kubernetes. 
The linked example in the `rabbitmq-peer-discovery-k8s` repository also defines a statefulset (although the file right now is called deployment.yaml).

Kubernetes clustering: refer to statefulset instead of deployment

---

site/access-control.md

It seems the text of the subsection was copied from the "Granting
Permissions to a User" and was still referring to granting
permissions, instead of revoking them.

Fix Revoking Permissions subsection

---

site/tutorials/tutorial-five-dotnet.md

It's been called twice `.toArray()` (above line) method

typo: tutorial five dotnet

---

site/clustering-ssl.md

to use the cli tools with activate TLS the variable environment variable `CTL_ERL_ARGS` has to be changed to `RABBITMQ_CTL_ERL_ARGS`.

update variable for using CLI tools with TLS

---

site/kubernetes/operator/using-operator.md

The example manifest is missing a required field `spec.replicas`.

Fix override example manifest

---

site/parameters.md

Fixed an inconsistency in one of the examples for defining a policy in "Parameters and Policies"

Fixed inconsistency in example in "Parameters and Policies"

---

site/kubernetes/operator/using-operator.md

Follow on PR from https://github.com/rabbitmq/cluster-operator/pull/232
This PR adds in the missing documentation for mTLS configuration in the Kubernetes operator.

Add operator documentation for mTLS configuration

---

site/clustering-ssl.md

In the case that the private keyfile is encrypted, the CLI tools fail to connect unless the password is passed in via the environment file.  I added some examples in the documentation for this (probably unusual) scenario.
Note that it appears that only SERVER_ADDITIONAL_ERL_ARGS is necessary for rabbitmqctl and others to connect, but I added examples for RABBITMQ_CTL_ERL_ARGS also.

Add examples for encrypted keyfiles

---

site/prometheus.md

Added a couple basic examples showing how to enable TLS for the prometheus metrics.

Add examples for enabling TLS in the Prometheus plugin

---

site/kubernetes/operator/install-operator.md
site/kubernetes/operator/operator-overview.md

* delete helm chart method
* remove unnecessary steps (thanks to https://github.com/rabbitmq/cluster-operator/pull/250)
* group all commands together so that you can just copy-pasting all
commands at once should work for most people
* move image relocation and private registries to the bottom of the page
as most people don't need them
This PR assumes https://github.com/rabbitmq/cluster-operator/pull/250 is merged (it should be today). Until it is, you can test the installation steps by adding `git co simplified-installation` after cloning `cluster-operator` repo

Simplified installation process for the Kubernetes Operator

---

site/tutorials/tutorial-six-python.md

It would be better to just have a general explanation like other guides without these line numbers. it seems website code highlighter doesn't support line numbers.

Removed line numbers from tutorial-six-python.md

---

site/mqtt.md
site/stomp.md
site/web-mqtt.md
site/web-stomp.md

since it confused me in https://github.com/rabbitmq/cluster-operator/pull/292#discussion_r478462942 🙂

Replace "this" with "listener port"

---

site/configure.md

Leaving the extension off is old behavior that is no longer supported.

Add extension for configuration files

---

site/kubernetes/operator/install-operator.md

After https://github.com/rabbitmq/cluster-operator/pull/303 was merged, the steps in this PR are the only manual steps required for running the cluster operator on OpenShift.

Add required OpenShift manual installation steps

---

site/kubernetes/operator/install-operator.md
site/kubernetes/operator/operator-overview.md

k8s `1.18` is currently supported.

Update support k8s versions for cluster operator

---

site/definitions.md

The definitions page has a broken reference to a section of the page. The reference `[...] and then [imported](#imported) into another cluster [...]` should be `[...] and then [imported](#import) into another cluster [...]`.

Correct typo in reference link

---

site/kubernetes/operator/install-operator.md

We have a new 1-step installation method that simplifies the process of installing the Operator. We also added an alternative installation method levaraging the kubectl rabbitmq plugin.
The required RabbitMQ version is 3.8.4+ (it was 3.8.8) because 3.8.4 allows the configuration through `conf.d` style. There is no reason to require 3.8.8 as minimum version.

Update installation guide of Cluster Operator

---

site/kubernetes/operator/operator-overview.md

Fixed typo -  future to feature in "RabbitMQ clusters is a future that will be provided in later versions."

Fixed typo

---

site/tutorials/tutorial-seven-php.md

php seven tutorial differ from java because of `php-amqplib` handle deliver tags under the hood, so there's no need in a few last steps here

Add tutorial seven for php

---

site/upgrade.md

* I think (certainly hope!) we don't need to mention RabbitMQ 2.x anymore
* in a similar vain, I mentioned that Erlang 19 is very old

Do not mention RabbitMQ 2.x

---

site/shovel-dynamic.md

A small issue I found while reading documentation about dynamic shovels. The parameter in the sample should be named `src-queue` instead of `source-queue`.

Update the parameter name in the sample of dynamic shovel

---

site/tutorials/tutorial-seven-java.md
site/tutorials/tutorial-seven-php.md
site/tutorials/tutorials-menu.xml.inc

- Add PHP tutorial seven to the tutorials menu.
- Minor grammar fixes.

Add PHP tutorial seven to tutorials menu; fix grammar

---

site/configure.md
site/networking.md
site/runtime.md

Part of rabbitmq/rabbitmq-server#2473

Remove all mentions of setting IO thread pool size

---

site/kubernetes/operator/install-operator.md

Since https://github.com/rabbitmq/cluster-operator/pull/447 is merged, the service account name is `<instance-name>-server`.

Fix service account name to have suffix '-server'

---

site/documentation.md
site/download.md
site/kubernetes/operator/install-operator.md
site/kubernetes/operator/operator-overview.md

In the documentation landing page, there is now a link to the overview of Cluster Operator. This should make Cluster Operator docs more accessible and easier to find.
An alternative path is "Docs" -> "Installation and provisioning" -> "Kubernetes". This path takes the user to the installation guide.
Related to https://github.com/rabbitmq/cluster-operator/issues/456

Link RabbitMQ Cluster Operator overview in docs landing page

---

site/dlx.md

The documentation around DLX guarantees has not been correct since [this](https://github.com/rabbitmq/rabbitmq-server/commit/c6ac0edbe633990b46c3440e184aadee9e6d47d0) 2013 commit.

Correction around DLX guarantees

---

site/dlx.md

Correct link anchor (was duplicated with the one on line 158).

Fix anchor in dlx.md

---

site/services.md

Remove bad link.
See  https://github.com/rabbitmq/rabbitmq-website/issues/1103

Remove  bad link on service page to Open Source Architect

---

site/monitoring.md

We have integrations for both metrics and logs, so I added both links.

Added Sematext to the list of monitoring tools

---

site/documentation.md
site/dotnet-api-guide.md
site/dotnet.md
site/erlang-distribution-compression.md
site/rabbit.ent
site/ssl.md

- Fix a few typos
- Turn rabbitmq.github.io links into https

Fix typos, use https links

---

site/web-stomp.md

Fixes the schema of a WebSocket URL to use `ws` instead of `http`.

Fix schema in WebSocket connection string

---

site/tutorials/tutorial-six-php.md
site/tutorials/tutorial-two-php.md

As of php-amqplib version 2.12.0 (see PR: https://github.com/php-amqplib/php-amqplib/pull/799) we should use method `ack()` on the message directly.

Replace deprecated php-amqplib API

---

site/kubernetes/operator/using-operator.md

Document 2 new features of the k8s operator:
- ability to pause reconciliation for RabbitmqCluster
- support for tls certs rotation without manually restarting the server

Document some new features of the k8s operator

---

site/tutorials/tutorial-two-php.md

I'd rather prefer to use named parameters if it wasn't such a young feature in PHP (introduced just a month ago):
```php
$channel->basic_consume($queueName, no_ack: true, callback: $callback);
```
But since it's so young, maybe it's better to use an old syntax. But it's yet worth to fix the false statement that `no_ack` is turned off by default.
@pivotal-issuemaster This is an Obvious Fix

acknowledgements are actually turned _on_ by default

---

site/how.xml

Hi,
I found at least 2 broken links in the how to section.
I switch one to the archived version of the article and removed the second as it was never archived.

Remove broken links from the website

---

site/access-control.md
site/parameters.md

There were some regexes that weren't being displayed correctly. More specifically, the escaped `.`s were being shown unescaped:
(I find that specific case rather dangerous, as the regex works, but also gives more permissions that intended)
I changed it so it displays the dots correctly escaped:
---
Although I did search the repo for similar cases of unescaped `.`s, I did not look for other possibly unescaped characters. So it is possible that more cases exist.

Fix regex escaping

---

site/kubernetes/operator/operator-overview.md
site/kubernetes/operator/quickstart-operator.md
site/kubernetes/operator/using-operator.md

Quickstart that covers - 
- installing the cluster operator
- deploying a simple rabbitmq cluster using the operator
- accessing management ui on the deployed cluster
- viewing rabbitmq logs on the deployed cluster
- links to next steps
It also 
- breaks down the kubernetes resources that get created as a result of both installing the operator and creating a rabbitmq cluster using the operator
- promotes the examples on the cluster operator github repo

Add quickstart guide

---

site/kubernetes/operator/quickstart-operator.md
site/kubernetes/operator/using-operator.md
site/troubleshooting-networking.md
site/uri-query-parameters.md

- Lots of fixes on grammar, formatting, punctuation, capitalization, and dead links.
- In particular, corrected the code formatting in [the kubernetes/operator/quickstart-operator.html page](https://www.rabbitmq.com/kubernetes/operator/quickstart-operator.html).

Fix grammar, formatting, dead links, etc

---

site/runtime.md

The anchor link doesn't go anywhere since the section has been removed.

Remove topic header that is not included anymore

---

site/tutorials/tutorial-two-go.md

According to [Effective Go](https://golang.org/doc/effective_go.html#mixed-caps), the convention is to use MixedCaps or mixedCaps rather than underscores to write multiword names. 
In this PR I corrected an instance where a variable was defined using snake case.

Correct Go variable casing

---

site/ha.md
site/kubernetes/operator/kubectl-plugin.md
site/kubernetes/operator/operator-overview.md
site/kubernetes/operator/quickstart-operator.md

This commit adds a dedicated page for installation and usage
of the rabbitmq kubectl plugin.

RabbitMQ plugin for kubectl

---

site/cli.md

The github links are 404s due to some repo re-organization.

Fix typo and broken links around rabbitmqadmin

---

site/troubleshooting-ssl.md

The stunnel example does not work for stunnel versions >= 4, but there is a perl-script wrapper provided that allows for usage of older commandline options. I've created this pull request to reflect this in the docs.
BR,
Thomas

Use stunnel3 wrapper in stunnel example.

---

site/feature-flags.md

Update the feature flags table to list all current feature flags.
Document how to configure the initial feature flags to enable on a blank node, required for some upgrades.
See https://groups.google.com/g/rabbitmq-users/c/L-4MH5NXZq8/m/I5hM9A2wAwAJ

Update feature flags documentation

---

site/kubernetes/operator/quickstart-operator.md

Currently quickstart does not cover a local provisioner.
This might lead to bad user experiences, as nowhere in the docs there's a mention of the need of a Volume provisioner :)
So the idea here is, if the user is stuck because of PVC, add a local path provisioner just to make sure he can follow with the quickstart guide :D

Add local-host provisioner in kubernetes quickstart

---

site/kubernetes/operator/using-operator.md

This feature was not documented, and has confused a user: rabbitmq/cluster-operator#670.
A followup from PR: #1171, the previous PR contains many typos.

Add documentation on memory headroom for cluster operator

---

Makefile
site/kubernetes/operator/install-operator.md
site/kubernetes/operator/operator-monitoring.md
site/kubernetes/operator/quickstart-operator.md

This PR adds docs on how to integrate RabbitMQ scrape targets,
alerting rules, and Grafana dashboards with an existing Prometheus.
We describe the integration for a Prometheus installed by Prometheus
Operator (i.e. CRDs ServiceMonitor, PodMonitor, PrometheusRule are available)
and for a Prometheus not installed by Prometheus Operator.
Remove the section to scrape RabbitMQ by annotations since that approach
is not recommended anymore.
This PR tries to remove duplicate YAML definitions from the docs
and instead links to the YAML definitions already present in the
cluster-operator repo.
Relates to https://github.com/rabbitmq/cluster-operator/pull/667 and https://github.com/rabbitmq/cluster-operator/pull/676.

Update Monitoring RabbitMQ in Kubernetes

---

site/install-debian.md

I wasn't sure where the empty link was intended to point to, so I picked a likely destination. Feel free to propose an alternative, or I can revert the link to point back to the top of this doc.

Fix typo & missing link in debian install doc

---

site/kubernetes/operator/install-topology-operator.md
site/kubernetes/operator/troubleshooting-topology-operator.md

A TLS guide and general usage guide for topology operator will be added next. In addition to that, we need to link to messaging topology operator in this page: https://www.rabbitmq.com/kubernetes/operator/operator-overview.html
Relates to: https://github.com/rabbitmq/messaging-topology-operator/issues/128

Add installation and troubleshoot guide for topology operator

---

site/tutorials/tutorial-one-spring-amqp.md

While following the first tutorial for hello-world in spring boot, I noticed that a package name was missing 'tut1' at the end.

added .tut1 to package in rabbitmq springboot tutorial

---

site/kubernetes/operator/operator-overview.md

Include topology operator in operator landing page and restructures the kubernetes operators overview page.

Include topology operator in operator landing page

---

site/ha.md

I never remember what the default value is, I use a search engine and can't find it on this page. This should fix that :)
I considered fully removing the "Earlier versions"-sentence as 3.5.x is now a relatively rare sighting.

Include detail about "mirroring_sync_batch_size"

---

site/install-rpm.md

- binary repos with gpgcheck=1 and including the rabbitmq package signing key
- source repos with gpgcheck=0
Besides the [path issues](https://groups.google.com/g/rabbitmq-users/c/yPl0whVvOXo/m/u10Z-vgeBQAJ) in the rabbitmq-server repository, official docs are not constant regarding package signatures

Fix: proper docs with gpg signatures for EL 7/8

---

site/kubernetes/operator/operator-overview.md

- document the fact that cluster operator always enables all available feature flags in a cluster (a user has reported this: https://github.com/rabbitmq/cluster-operator/issues/688)
- add reference links to operator titles

Document cluster operator feature flag limitations

---

site/kubernetes/operator/using-operator.md

Fix typo RabbitMQ Operator Cluster spec according to [spec](https://github.com/rabbitmq/cluster-operator/blob/3cc96f2e77d0325db193571ba0cc7ff33da95aaa/api/v1beta1/rabbitmqcluster_types.go#L63)

fix-typo-operator-spec-resources

---

site/kubernetes/operator/using-topology-operator.md

In the documentation for using the topology operator, the Vhost example has a `kind: Queue` instead of a `kind: Vhost` in the yaml example. This PR fixes that, according to the example in https://github.com/rabbitmq/messaging-topology-operator/blob/main/docs/examples/vhosts/vhost.yaml

Fix Vhost kind in yaml example for topology operator documentation

---

site/download.md
site/kubernetes/operator/install-operator.md
site/kubernetes/tanzu/installation.md

This adds a new page rabbitmq.com/kubernetes/tanzu/installation.html for this installation procedure.

Add installation documentation for Tanzu RabbitMQ for K8s

---

site/tutorials/tutorial-three-dotnet.md

Hey!
I just started learning rabbitmq and I'm reading the documentation and found a broken link in dotnet tutorial three.
When you click on the "queues guide" link at https://www.rabbitmq.com/tutorials/tutorial-three-dotnet.html it goes to https://www.rabbitmq.com/tutorials/queues.html which displays a page not found.

Broken link fixed in tutorial three of dotnet.

---

site/kubernetes/operator/operator-overview.md

Reading up on the k8s operator I noticed that this link is broken.
Instead of linking to https://kubernetes.io/docs/concepts/extend-kubernetes/operator/ it links to https://www.rabbitmq.com/kubernetes/operator/(https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) which is a broken link.

Fixed broken kubernetes operator link

---

site/kubernetes/operator/operator-overview.md

Based on issue https://github.com/rabbitmq/cluster-operator/issues/712, I noticed we don't have any written reference of our design principles, and this can cause confusion, as there isn't an standarised behaviour in the Operator ecosystem.
These ideas/principles have been present in our decisions since the beginning, however there were not written anywhere. This PR flushes them in the Operator Overview page.

Document design principles of Cluster Operator

---

site/cluster-formation.md

This is the doc change for https://github.com/rabbitmq/rabbitmq-server/pull/3075 (i.e relevant for `>= 3.8.18`)
In K8s, the cluster-operator nowadays uses Parallel (instead of OrderedReady)
pod management policy. Therefore, we delete some sentences on
recommending OrderedReady.
There is no need to document the new config value
`cluster_formation.internal_lock_retries` since it's too much
implementation detail for this doc and we don't expect users to change
this value.

Remove randomized startup delays

---

README.md

README was still referencing `master` branch, which is now `main`

Update README master references to main

---

site/ha.md
site/quorum-queues.md

Fix incorrect wording concerning the original name of "queue leader".

Fix incorrect wording

---

site/maxlength.md

This is the same change as in #774, expect that Markdown is used.
See rabbitmq/rabbitmq-server#1443, rabbitmq/rabbitmq-server#2015.
Closes #1217.

Restore documentation on `reject-publish-dlx` overflow setting

---

site/consumer-prefetch.md

This was introduced in https://github.com/rabbitmq/rabbitmq-server/pull/1408, but never documented.

Document default_consumer_prefetch

---

site/consumers.md

With 3.8.17 the default was changed to 30 minutes instead of 15. This updates the docs accordingly.
https://github.com/rabbitmq/rabbitmq-server/pull/3033
https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.8.17

Update default consumer_timeout in docs to 30 minutes

---

site/versions.md

This calendar captures what was discussed during this week's 3.9.0 release check-in meeting.
Announce in these places after this gets merged:
cc @dcarwin-pivotal, @MirahImage, @edbyford, @yaronp68

Add 3.9.0 release calendar

---

site/consumers.md

30 minutes in milliseconds is 1800,000,
not 180,000.
:)

Fix wrong time value

---

site/logging.md

We recently received a question on how to configure logging to a file in the Cluster Operator:
https://github.com/rabbitmq/cluster-operator/issues/771
The conclusion was that the Docker image sets RABBITMQ_LOGS environment variable, therefore any configurations like `log.file` were simply ignored. To me, it was not clear that the environment variable is not additive. A user could think that setting `RABBITMQ_LOGS` to `-` and `log.file` to a path would log to both, standard output and a file. This is not true and we can be explicitly clear about it in the docs.

Make explicitly clear the precedence of RABBITMQ_LOGS

---

site/changelog.md

Update release date of RabbitMQ 3.9.0 from `236July 2021` to `23 July 2021`.

Fix typo in changelog page

---

site/install-debian.md

As per https://wiki.debian.org/DebianRepository/UseThirdParty
"The key MUST be downloaded over a secure mechanism like HTTPS to a location only writable by root, which SHOULD be /usr/share/keyrings. The key MUST NOT be placed in /etc/apt/trusted.gpg.d or loaded by apt-key add. A sources.list entry SHOULD have the signed-by option set. The signed-by entry MUST point to a file, and not a fingerprint."
Should you require further background beyond the above Debian wiki link, see also:
[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861695
[2] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=877012

Update Debian GPG instructions to bring inline with best practice

---

site/signatures.md

1. Remove all references to SKS which is now dead (https://code.firstlook.media/the-death-of-sks-pgp-keyservers-and-how-first-look-media-is-handling-it)
2. Debian best-practice as per https://github.com/rabbitmq/rabbitmq-website/pull/1240

Remove SKS + Add Debian Best Practices

---

site/install-debian.md

1. Debian best-practice as per https://github.com/rabbitmq/rabbitmq-website/pull/1240
2. Make a start on removing some of the excessive verbosity on the page (e.g. one example for `$distribution` substitution is sufficient)

Debian best-practice + reduce verbosity

---

site/install-debian.md

Remove verbose discussion of OpenSSL versions etc. in favour of the easier to understand "current and previous distro version".
Also add note re: PackageCloud one liner.

Simplify wording re: Supported Distributions + PackageCloud one-liner note

---

site/install-debian.md

I don't believe there is a dependency on `debian-keyring` `debian-archive-keyring` here since we are pulling in relevant keys, also:
1. `debian-archive-keyring` seems to be provided in a basic Debian install anyway:
```
$ dpkg-query -W --showformat='${Package}\t${Priority}\n' | grep "debian-archive-keyring" 
debian-archive-keyring	important
```
2.  Debian doesn't exactly have encouraging words to say about `debian-keyring`:
>  "this package is provided for convenience, it is not necessarily kept updated with the latest changes" 
(https://packages.debian.org/buster/debian-keyring) so probably best to play safe !

Remove debian-keyring debian-archive-keyring

---

site/install-debian.md

Missed a couple of references to `apt-key`, now replaced.

Missed references to apt-key

---

site/install-debian.md
site/signatures.md

1. Removed "Without systemd (Older Linux Distributions)"
2. Tweak PackageCloud section ordering
3. Tweak Cloudsmith ordering
4. Remove `apt-key` references from signatures page

Ordering tweaks + remove "older linux distributions"

---

site/install-debian.md

Debian Bullseye Release Notes 5.3.2:
> The historical justifications for the filesystem layout with /bin, /sbin, and /lib directories separate from their equivalents under /usr no longer apply today; see the Freedesktop.org summary. Debian bullseye will be the last Debian release that supports the non-merged-usr layout; for systems with a legacy layout that have been upgraded without a reinstall, the usrmerge package exists to do the conversion if desired. 
I have checked on a random Buster instance and /usr/bin/sh is present and points to the same place, so the change is non-breaking for Buster:
```
$ ls -l /usr/bin/sh
lrwxrwxrwx 1 root root 4 Jul  3 18:59 /usr/bin/sh -> dash
$ ls -l /bin/sh
lrwxrwxrwx 1 root root 4 Jul  3 18:59 /bin/sh -> dash
```

/bin/sh -> /usr/bin/sh

---

site/kubernetes/operator/operator-overview.md
site/kubernetes/operator/upgrade-operator.md

Upgrading the operator is definitely supported, and information stating otherwise is legacy from pre-GA.

Replace outdated upgrade documentation

---

site/cluster-formation.md

in headless service for K8s peer discovery to work with parallel pod management policy.
Example:
```
apiVersion: v1
kind: Service
spec:
publishNotReadyAddresses: true
```
If NOT set, K8s peer discovery will determine the peers correctly (i.e.
both ready and not-ready pods in
https://github.com/rabbitmq/rabbitmq-server/blob/513a643e9123c7bb3b3059a127a103ad0d99c205/deps/rabbitmq_peer_discovery_k8s/src/rabbit_peer_discovery_k8s.erl#L79 ).
However, when setting the lock in
https://github.com/rabbitmq/rabbitmq-server/blob/513a643e9123c7bb3b3059a127a103ad0d99c205/deps/rabbitmq_peer_discovery_k8s/src/rabbit_peer_discovery_k8s.erl#L82
the headless service will route traffic to only ready pods
resulting in the locking mechanism not to work with podManagementPolicy
set to parallel. This will result …

Require field publishNotReadyAddresses to be set

---

site/kubernetes/operator/using-topology-operator.md

This PR documents the feature delivered in https://github.com/rabbitmq/messaging-topology-operator/pull/201
We should publish this after releasing a new version of the Topology Operator. Current available versions of the top-op do not have this feature. This feature is backwards compatible with previous versions of Cluster Operator.
Closes #1256

Document x-namespace feature in Topology Operator

---

site/dotnet-api-guide.md

The `Uri` property is a `Uri` object, not a `string`, so the old code didn't compile.
See https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/5ab37c795d8e333d84d245ed0e25e310c26feadb/projects/RabbitMQ.Client/client/api/ConnectionFactory.cs#L323

Correct code example in .NET/C# Client API Guide

---

site/tutorials/tutorial-two-dotnet.md
site/tutorials/tutorial-two-elixir.md
site/tutorials/tutorial-two-go.md
site/tutorials/tutorial-two-java.md
site/tutorials/tutorial-two-javascript.md
site/tutorials/tutorial-two-objectivec.md
site/tutorials/tutorial-two-php.md
site/tutorials/tutorial-two-python.md
site/tutorials/tutorial-two-ruby.md
site/tutorials/tutorial-two-swift.md

It seems that no consumer timeout was the default a while ago.
Relates https://github.com/rabbitmq/rabbitmq-server/pull/2990

Correct consumer timeout

---

site/queues.md

Exclusive queues are now always client-local

---

site/dotnet-api-guide.md

Fix 2 things in .NET/C# Client API Guide (https://www.rabbitmq.com/dotnet-api-guide.html#basic-get)
1. Rename `noAck` to `autoAck`
Reference: https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/297
2. Fix the wording
`noAck` = `false`
⇒ no manual acknowledgements = `false`
⇒ manual acknowledgements = `true`
Reference: https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/255#issuecomment-323133972
For reference, same guide for Java: https://www.rabbitmq.com/api-guide.html#getting

Fix wording about ack in .NET/C# Client API Guide

---

site/kubernetes/operator/using-operator.md

mainly pointing to the cluster-operator examples since they contain the
source of truth on how to configure everything correctly.
~~Draft PR because we merge after https://github.com/rabbitmq/cluster-operator/pull/846 has been merged.~~

Add Vault docs

---

site/kubernetes/operator/using-operator.md

~Draft: blocked on https://github.com/rabbitmq/cluster-operator/pull/859~
Addresses https://github.com/rabbitmq/cluster-operator/issues/835
This PR links to the cluster-operator docs for Network Policies in Kubernetes.

Add documentation for Kubernetes Network Policies

---

site/install-debian.md

There is error 'Permission denied' at least when install rabbitmq on Ubuntu 20.04. If we use 'tee' all works fine.
(thanks to https://stackoverflow.com/a/82553/9252162)

Using 'tee' command instead of '>'

---

site/tutorials/tutorial-seven-dotnet.md

In [.NET tutorial seven][1], in code samples, replace `BasicProperties` by `IBasicProperties`.
This is because `BasicProperties` is `internal`, not `public`.
https://github.com/rabbitmq/rabbitmq-dotnet-client/commit/267bae75b217dd32bd4c116dd3cdf25a3e3b70f1#diff-a63ad46e4c793acbad8d98e9ac01d886fc968bc31115eef609f5111bd888a027
[1]: https://www.rabbitmq.com/tutorials/tutorial-seven-dotnet.html

Fix code samples in .NET tutorial 7

---

site/dotnet-api-guide.md
site/ttl.md
site/tutorials/tutorial-six-dotnet.md

1. Add missing semicolons.
2. Fix code indentation.

Minor improvements in C# code samples

---

site/dlx.md

If a message is dead-lettered after it has been returned more times than the limit, the `reason` field of the `x-death` header will be "delivery-limit".

Add Delivery-Limit Dead-Lettered Reason

---

site/tutorials/tutorial-two-python.md

Tix typo in python-two tutorial descriptions.
This commit replace string and add bytes to time.sleep body in 'Message
acknowledgment' part.

Fix typo in tutorial-two-python. Bytes instead string

---

site/access-control.md

In page "[Authentication, Authorisation, Access Control](https://www.rabbitmq.com/access-control.html#authorisation)",
section "Authorisation: How Permissions Work",
the links in the table were not properly formatted.
I fixed the link formatting.

Fix invalid links in access-control.md

---

site/tutorials/tutorial-two-python.md

Use `pika.spec.PERSISTENT_DELIVERY_MODE` instead of `2`.

Use named constant in the Python tutorial

---

site/erlang-client-user-guide.md

| Before | After |
| ------ | ------ |
| ![image](https://user-images.githubusercontent.com/31410892/144876649-9d8594b6-ff02-4f89-b5c4-6a0f0aab3752.png) | ![image](https://user-images.githubusercontent.com/31410892/144876935-96fa5c89-f067-4164-bdce-f35b2525f5c3.png)  |

doc: fix typos for Erlang guide

---

site/cluster-formation.md

Fix an incorrect reference to RABBITMQ_USE_LONGNAME environment variable in cluster-formation.md file.

Fix typo in cluster-formation.md

---

site/kubernetes/operator/install-operator.md
site/kubernetes/operator/install-topology-operator.md
site/kubernetes/operator/quickstart-operator.md

This is to compliment https://github.com/rabbitmq/cluster-operator/pull/931

Document drop of k8s 1.18 support in operator

---

site/install-debian.md

Installation on Debian Bullseye with `buster` as a name of RabbitMQ apt repository on PackageCloud breaking the deployment and rabbitmq-server can't be loaded. I decided to deploy RabbitMQ adding to /etc/apt/sources.list.d/rabbitmq.list `bullseye`:
```
#
deb [signed-by=/usr/share/keyrings/io.packagecloud.rabbitmq.gpg] https://packagecloud.io/rabbitmq/rabbitmq-server/debian/ bullseye main
deb-src [signed-by=/usr/share/keyrings/io.packagecloud.rabbitmq.gpg] https://packagecloud.io/rabbitmq/rabbitmq-server/debian/ bullseye main
```
And finally, my RabbitMQ started to work. 
That would definitely save us time if this information was already available in your documentation. Thank you in advance!

Change distro name for Debian Bullseye release

---

site/index.xml

Northflank has added RabbitMQ to its DBaaS offering [here](https://northflank.com/changelog/introducing-managed-rabbit-mq-build-and-scale-with-queues-and-message-brokers). Adds it to the Support + Hosting section.

adds Northflank to Support + Hosting section

---

site/connections.md

Just fix a few typos and broken links on the Connection page.

Fix typos on the Connection page

---

site/networking.md

Describe RabbitMQ's use of TCP port 15671 (the TLS-enabled management port).

Add port 15671 to networking document

---

site/queues.md

Nothing critical, just a missing comma between link references.

Added missing comma for separating links

---

site/devtools.md

The link to https://github.com/cloudamqp/amqp-client.js is included several times in the documentation. This pull request removed the second place.

remove duplicate Link to https://github.com/cloudamqp/amqp-client.js

---

site/kubernetes/operator/install-topology-operator.md

Documenting the feature in the Topology Operator to append a specific domain name to the connection strings used to contact RabbitMQ, delivered in this PR https://github.com/rabbitmq/messaging-topology-operator/pull/310
This enables users to create star certificates for RabbitMQ, and "hint" the Topology Operator how to construct a connection string correctly.

Topology Operator support for custom domains

---

site/confirms.md

The `Consumer Acknowledgements and Publisher Confirms` page only mentioned the behaviour when the `requeue` parameter is set to `true`, and implied that the message will always be discarded otherwise. This PR added details about dead lettering to make it clearer what happens when it is set to `false`.
I personally got confused by this while initially integrating, since I wasn't looking into DLX docs at that time.

Specified behaviour on consumer nack with requeue set to false

---

site/which-erlang.md

If 3.9.15 is the first to support Erlang 24.3 than it can't be supported by 3.8.x.
Maybe it should say 24.2.x (as 24.2.2 is supported but not 24.3)?

24.2 for 3.8.x too

---

site/kubernetes/operator/using-topology-operator.md

Currently, docs state cluster operator is a pre-req. This is no longer the case, but the topology operator is a prereq. [This has led to confusion](https://github.com/rabbitmq/cluster-operator/issues/1022).

Topology Operator docs should require topology operator

---

site/configure.md

Adding context to tcp_listen_options on options keepalive & exit_on_close
https://www.rabbitmq.com/configure.html 
from issue https://github.com/rabbitmq/rabbitmq-website/issues/1412
proposed changes look:

Adding context to tcp_listen_options on keepalives & exit_on_close on configure page

---

site/tutorials/tutorial-six-python.md

Calling `connection.process_data_events` in loop, uses 100% CPU until response is returned, and this makes problem if server does not response.
Passing None to `process_data_events`, blocks until I/O produces actionable events.

`time_limit` of `process_data_events` is set to `None`

---

site/tutorials/tutorial-one-dotnet.md

Removed two instances of unnecessary "dotnet restore" from C# tutorial one. Restore is run by the preceding "dotnet add package".

Removed unnecessary restore from C# tutorial one

---

site/tutorials/tutorial-one-dotnet.md

- Removed advice to close client with CTRL-C, as it closes on "enter" as printed by the client.
- Simplified advice on sending several messages, as there is not need for yet another terminal instance.

Simplified recommendations on running clients

---

site/admin-guide.md
site/erlang-client-user-guide.md
site/memory-use.md
site/oauth2-examples.md
site/plugins.md
site/shovel.md
site/vhosts.md

Markdown files had a number of empty xrefs (both markdown format and html format) that were causing problems. This PR adds targets to the empty links.

Fix broken (empty) xrefs in markdown source files

---

site/tutorials/tutorial-five-go.md
site/tutorials/tutorial-four-go.md
site/tutorials/tutorial-one-go.md
site/tutorials/tutorial-six-go.md
site/tutorials/tutorial-three-go.md
site/tutorials/tutorial-two-go.md
site/upgrade.md

Signed-off-by: Erdem Köse <erdemkose@gmail.com>
Code examples in the tutorials do not match the latest version of the source code. The changes in the three commits below are now reflected in the tutorials.
Besides, links to godoc.org are replaced with the current ones in pkg.go.dev since [they are already redirected to pkg.go.dev](https://go.dev/blog/godoc.org-redirect).
- https://github.com/rabbitmq/rabbitmq-tutorials/commit/52ca462906a6cd10e387e39074cee468f6bd2b47
- https://github.com/rabbitmq/rabbitmq-tutorials/commit/bd2c06f28f88cbc4a1ef85e7adaf95743110d83a
- https://github.com/rabbitmq/rabbitmq-tutorials/commit/98a3ff7c1f6a410e93533296a1f3327476cf1319

Update Go code examples to match the source code

---

site/monitoring.md

We have a change for collectd github link.

Fixed 'collectd' github link for monitoring

---

site/jms-client.md

For JMS client 2.5.
References rabbitmq/rabbitmq-jms-client#178, rabbitmq/rabbitmq-jms-client#175
To merge when JMS client 2.5.0.RC1 is out.

Document keepTextMessageType and queueDeclareArguments options

---

site/kubernetes/operator/using-topology-operator.md

Document the limitation of updating `users.rabbitmq.com`.
We have one user asking about this: https://github.com/rabbitmq/messaging-topology-operator/issues/414

Add top op user object update limitation

---

site/ttl.md

The hyperlink pointed to `.md` extension of the file. For hyperlinks to work on live page we need to use `.html` extension
see first hyperlink under https://www.rabbitmq.com/ttl.html#per-message-ttl-in-publishers

Fixed relative hyperlink

---

site/monitoring.md

- "Prometheus" was used instead of "management" when referring to installing the management plugin
- Several spelling errors (e.g. "second" instead of "seconds")
- Grammar fixes (e.g. "is" instead of "are")

Spelling, grammar, and typo fixes

---

site/resources/specs/amqp0-9-1.stripped.extended.xml

It has missing the constant for 'no-route' code 312. This constant is
present in the extended non-stripped version and it is supported by
RabbitMQ.

Update stripped extended spec

---

site/tutorials/tutorial-five-go.md
site/tutorials/tutorial-four-go.md
site/tutorials/tutorial-one-go.md
site/tutorials/tutorial-six-go.md
site/tutorials/tutorial-three-go.md
site/tutorials/tutorial-two-go.md

Using `Channel.Publish` is deprecated. Tutorials should use updated API
`Channel.PublishWithContext`.

Update Go tutorials

---

site/windows-quirks.md

I've added a section on what ANSI sequence clutter look like, and how to configure Windows to display colors, rather than gobbledygook.
The contribution guidelines said to offer "why" for a contribution, so here's my why:
The reason is I want to save people the trouble of seeing something really strange (ANSI escape sequences), wondering why they are seeing it, getting discouraged, figuring out how to formulate what they are seeing in such a way that they can find the issue on the Internet, digging through bug trackers, seeing that the "bug" is fixed (?), wondering why it was "fixed" in 2019 but they're still seeing it, searching further, finding articles on ANSI escape sequences and how they relate to PowerShell, studying the mitigations, applying the mitigations, and then feeling guilty …

+"CLI Tools Show ANSI Character Sequences"

---

site/streams.md

Reverts rabbitmq/rabbitmq-website#1478 as it was mean to go into a different branch (`main` for now).

Revert "Document stream SAC and super streams"

---

site/quorum-queues.md

Per 3.8.10 release notes:
> [Quorum queues](https://www.rabbitmq.com/quorum-queues.html) now support [consumer priority](https://www.rabbitmq.com/consumers.html#priority).
> GitHub issue: https://github.com/rabbitmq/rabbitmq-server/pull/2451

Correct that QQ support customer priority

---

site/plugins.md

The links for the following plugins were outdated:
* rabbitmq_amqp
* rabbitmq_auth_backend_http
* rabbitmq_auth_mechanism_ssl 
* rabbitmq_consistent_hash_exchange
I added a link to the coresponding README.md files in the `/deps/` folder of the main repository.

Update links for RabbitMQ plugins

---

site/devtools.md

It looks like that the original link for `amqp.node` redirects to `amqplib`. I was a bit confused at first, cause I didn't see `amqplib` mentioned on this page, even though the tutorials used it.

Renames amqp.node to amqplib

---

site/monitoring.md

Hey Team
There is a problem with this redirecting links so I am updating this.
We’d love to provide a smooth experience for RabbitMQ users who need to use monitoring solutions, such as New Relic.
Thank you for your consideration.

Updating the redirecting links

---

site/monitoring.md

Hey Team 
I just need to update the name of the rabbitMQ monitoring i.e, New Relic tool name as per the Official website guidelines
Thank you for the consideration

Updating the RabbitMQ monitoring tool name

---

site/amqp-0-9-1-errata.xml
site/how.xml

@michaelklishin FYI, replacing references to "he" in the docs as it is one of the words that needs to be changed, see here: https://source.vmware.com/portal/pages/global-marketing/terminology-changes

Replacing "He" references in docs

---

site/devtools.md

This Client doesn't seem official since its copyrights and organization don't seem to be related with RabbitMQ.
Discussion: https://github.com/rabbitmq/rabbitmq-website/pull/1473/files#r1013075477

Remove check mark from unofficial client

---

site/ha.md
site/man/README.md
site/man/rabbitmqctl.8.html
site/upgrade.md

Amended several mentions of `slave_pids`, updated build instructions to refer to bazel
Regenerated rabbitmqctl man-page. Opted to do it only for one page since my `mandoc` apparently produces a significantly different result. Subject to discussion.

update rabbitmqctl to use inclusive info keys

---

site/install-homebrew.md

Added alternative paths to homebrew installations for Apple Silicon according to https://www.rabbitmq.com/install-homebrew.html

Added alternative paths for Apple Silicon

---

site/cli.md

The 4 examples are the same, between the "status" and the "shutdown" parts. Probably a copy/paste error.

Typo in the "Getting node status" chapter

---

site/definitions.md

Add missing header "Content-Type : application/json" to import definitions using rest api with curl. Without it I receive an error code ...

add Content-Type header to import definitions using curl

---

site/install-rpm.md

Because of the hash algorithm in use (SHA1) for the Erlang and RabbitMQ server repository, the appropriate rpm import commands will fail. A possible workaround is to switch the crypto policies to legacy.

Added a hint for the key import commands

---

site/management.md
site/oauth2-examples-azure.md
site/oauth2-examples-keycloak.md
site/oauth2-examples-oauth0.md
site/oauth2-examples.md
site/oauth2.md

Update management ui documentation:
- added new setting : `oauth_initiated_logon_type` 
- `oauth_client_secret` setting is now optional
Update oauth2 documentation:
- added new setting : `preferred_username_claims`

OAuth2 doc changes 

---

site/consumers.md

From time to time, we receive a message in RabbitMQ Slack, from people trying to
enable Single Active Consumer on a stream queue type, using an AMQP client. This
does not work, as expected, because SAC in streams requires coordination with
the client; a coordination that is not built-in the AMQP client, and the
AMQP-Stream bridge.
This PR updates the consumers guide, to clarify that SAC, in this section, is
specific to AMQP protocol.

Clarification on AMQP single active consumer

---

site/tutorials/tutorial-five-dotnet.md
site/tutorials/tutorial-four-dotnet.md
site/tutorials/tutorial-one-dotnet.md
site/tutorials/tutorial-seven-dotnet.md
site/tutorials/tutorial-six-dotnet.md
site/tutorials/tutorial-three-dotnet.md
site/tutorials/tutorial-two-dotnet.md

Hi 👋 
I'm in the process of updating the RabbitMQ examples for dotnet to dotnet7: https://github.com/rabbitmq/rabbitmq-tutorials/pull/350
The purpose of this PR is to update the website tutorials for dotnet to match the updated examples.

Update dotnet tutorials to match dotnet 7 examples

---

site/prometheus.md

I noticed there were some details missing on how to construct queries to the detailed endpoint.
These docs are almost verbatim copy/paste from the plugin `README` in the server repo, I will remove those in a follow-up PR.

Expand documentation for `/metrics/detailed` endpoint

---

site/prometheus.md

The full list is now included directly in the page.

Remove link do removed page

---

site/devtools.md

In my search for a RabbitMQ Node.js library that meets these criteria:
- TypeScript support
- Allows specifying multiple nodes in a cluster
- Await-able components
- Good docs
- Few dependencies
I found https://github.com/cody-greene/node-rabbitmq-client
This PR adds it to the docs list of Node.js client libraries.

Add node-rabbitmq-client to Node.js client libraries

---

site/dotnet-api-guide.md

Related to https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1299
We have agreed to not support ulong values, and document
this as a limitation instead.

Document .NET client limitation

---

site/passwords.md

See rabbitmq/rabbitmq-server#7432

Add rabbitmqctl / HTTP API docs for hashing password

---

site/which-erlang.md

RabbitMQ version 3.9.28 requires Erlang 24.3 as minimum version
At the moment, the which-erlang.md states 24.2 as minimum version while the deb package and release notes states that it requires 24.3. 
Added a new section for RabbitMQ version 3.9.28 with notes copied from the 3.10 versions with the same Erlang requirements.
I am however, unsure of the maximum version that 3.9.28 supports.

Add new section in which-erlang.md for version 3.9.28

---

site/oauth2.md

Very recently there has been a number of queries/issues reported around using topic exchanges in the context of Oauth2. 
This PR adds a section that explains what scopes are required to operate on a topic exchange. This information was already in the docs but clearly it was not very obvious to most of the users.

Add section for topic exchanges in Oauth2.md

---

site/install-homebrew.md

- Added semicolons before bash snippets for consistency
- Fixed the typo in the command `brew services start`
- Corrected the description of the behavior when stopping a node that is not running (the command issues a warning instead of an error)
@pivotal-cla This is an Obvious fix

Fix some typos in the homebrew installation page

---

site/configure.md

We link to other plugin configuration guides, so adding OAuth2 configuration link here as well.

Add link to OAuth2 config.

---

site/admin-guide.md
site/classic-queues.md
site/lazy-queues.md
site/persistence-conf.md
site/queues.md

It has updated information about classic queues and aims
to replace persistence-conf and lazy-queues ultimately.

3.12: add a classic-queues page to the documentation

---

site/clustering.md

In the clustering md the section about the node logging out the home dir of the effective user and default cookie location is duplicated under the ###Troubleshooting header and the ###Troubleshooting Cookie-based Authentication headers.
Removed the second dupe and moved the anchor link header to replace the first ###Troubleshooting header.
I can't quite tell what the methodology was with linking and not linking headers; took my best guess.

Remove duplicated cookie section and fix section header

---

site/kubernetes/operator/using-operator.md

Related to rabbitmq/cluster-operator/issues/1336
Local path provisioner, mainly used in Rancher and Rancher Desktop installations,
creates a folder in the Kubernetes node hosting the Pod. As a side-effect, the
Persistent Disk (PV) cannot enforce a limit on disk size, causing RabbitMQ to
detect the Kubernetes Node storage as available storage.

Document limitation with local-path provisioner

---

site/kubernetes/operator/operator-monitoring.md

We have a comment in our examples to deploy `PodMonitor` and `ServiceMonitor` to
warn about a caveat in the examples, see:
https://github.com/rabbitmq/cluster-operator/blob/ad59bc756637792e461a0e85524fe4f670f103ef/observability/prometheus/monitors/rabbitmq-cluster-operator-podmonitor.yml#L4-L7
https://github.com/rabbitmq/cluster-operator/blob/ad59bc756637792e461a0e85524fe4f670f103ef/observability/prometheus/monitors/rabbitmq-servicemonitor.yml#L2-L7
The YAML manifest is not very visible since we ask our users to `kubectl apply` from
a URL to the GitHub repo.
Related to rabbitmq/cluster-operator/issues/1331

Document caveat in Operator monitoring

---

site/devtools.md
site/download.md

This is a [Kurtosis Starlark Package](https://docs.kurtosis.com/quickstart) allowing you to spin up an n node RabbitMQ Cluster.

Add Kurtosis Starlark RabbitMQ package to the list of operations tools

---

site/devtools.md

Two of the lists on the devtools page show on one line instead of bullet points like the other lists.  This PR fixes the format.

Fix devtools page bullet points format

---

site/ha.md

Start documenting `mirroring_sync_max_throughput`. Added in https://github.com/rabbitmq/rabbitmq-server/pull/3925 (`3.10`)

Include "mirroring_sync_max_throughput"

---

site/management.md
site/oauth2-examples-azure.md
site/oauth2-examples-proxy.md
site/oauth2-examples.md

This PR updates the management ui section and oauth2 examples in order to introduce a new capability added to the Oauth2 support in the management ui.
This PR is linked to the [PR](https://github.com/rabbitmq/rabbitmq-server/pull/7365) on the rabbitmq-server.

Oauth2 login with authorization header

---

site/devtools.md

MassTransit, the most downloaded open-source service bus for .NET, was somehow missing from the documentation. This PR adds it.

Added MassTransit under .NET Developer Tools.

---

site/install-debian.md
site/install-generic-unix.md
site/install-rpm.md
site/networking.md

RabbitMQ Prometheus supports TLS endpoint: https://www.rabbitmq.com/prometheus.html#tls. But this is not mentioned in the Networking Guide. This PR adds that.
I also update the installation guides to refer to networking.html#ports page to avoid duplication.

Mention Prometheus TLS port (15691) in Networking page 

---

link-local-manpages
site/kubernetes/operator/install-topology-operator.md

- Document sync period feature in Topology Operator
- Small change to `link-local-manpages` since public umbrella is archived in favour of mono-repo 🐒

Document Top-Op sync period feature

---

site/feature-flags.md

with RabbitMQ versions when they reached `stable` and `required` states.
Prior to this commit it was very confusing for users to know what feature flags need to be enabled before upgrading to 3.12.0: https://groups.google.com/g/rabbitmq-users/c/154pIy2DXPI/m/u5nFdo1TBQAJ
This list should be kept up to date whenever a new feature flag is added or its state changes (at least until feature flags get auto-enabled, see https://github.com/rabbitmq/rabbitmq-server/issues/5212).

Update list of feature flags

---

site/kubernetes/operator/using-topology-operator.md

Document operator connection URI annotation. 
Release published: https://github.com/rabbitmq/messaging-topology-operator/releases/tag/v1.12.0
Ready to be merged

Document operator connection URI annotation

---

site/parameters.md

Document how modification of operator policies via the HTTP API and Web UI can be disabled with configuration.
* https://github.com/rabbitmq/rabbitmq-server/pull/7165

document disabling modification of operator policies in HTTP API and Web UI

---

site/parameters.md

`ha-mode`, `ha-sync-mode`, and `ha-params` were added as valid argument in operator policies. This PR updates the documentation to reflect those changes.
* https://github.com/rabbitmq/rabbitmq-server/pull/7368
* https://github.com/rabbitmq/rabbitmq-server/pull/8043
Now that not all arguments are numeric, I decided the use a table to describe the conflict resolution for each argument. Please provide feedback if this makes it easy for the reader to understand how conflict resolution works.
Question: Do the docs normally state if something is new or what version support starts in? Or just treat everything as it applies to the latest version? Support for `ha-*` in operator policies was introduced in 3.11.15.

add ha-* arguments to operator policies documentation

---

site/clustering-ssl.md

OTP 26 no longer ignores `fail_if_no_peer_cert` for a `client` setting.
See the following issue:
https://github.com/erlang/otp/issues/7497

Remove invalid TLS settings

---

site/feature-flags.md

Remaining MQTT 5.0 docs will follow at some later point before releasing 3.13

Document feature flag mqtt_v5

---

site/plugins.md

Fix broken links. Links to trust store and web stomp examples are broken. Link to web mqtt example points to archived repo.

Update plugins tier 1 table links

---

site/monitoring.md

- The older link was returning a 404 for the HTTP API reference.

docs: correct link added for Management API

---

site/tutorials/tutorial-six-php.md

PHP amqplib delivery_info property marked as deprecated
See:
php-amqplib/php-amqplib#799
https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Message/AMQPMessage.php#LL57C11-L57C11

Update tutorial-six-php.md replaced deprecated property

---

site/connections.md
site/heartbeats.md
site/man/rabbitmqctl.8.html
site/mqtt.md
site/plugins.md
site/protocols.md
site/publishers.md

Also, add sections for
* scalability check list
* MQTT QoS queue type that got added in 3.12
* metrics
Delete outdated documentation, e.g. client ID tracking in Ra.

Add MQTT 5.0 docs

---

site/news.xml

Fix the broken link in https://www.rabbitmq.com/news.html 
`<a href="/intall-rpm.html">dnf (yum) repositories</a>` -->  https://www.rabbitmq.com/intall-rpm.html  ❌ 
to
`<a href="/install-rpm.html">dnf (yum) repositories</a>` -->  https://www.rabbitmq.com/install-rpm.html  ✅ 
@pivotal-cla This is an Obvious Fix

Fix broken rpm html link

---

site/tutorials/tutorial-one-elixir.md

Using the 1.0 client in the example leads to connection errors.

update elixir client 1.0 -> 3.3

---

site/lazy-queues.md

Hi @acogoluegnes,
Can you please review this PR. The main of this PR is to do the following: 
1. Provide a clear crisp title (returned in search engine result pages (SERPs)
2. Define a classic queue in "lazy" queue mode (otherwise known as a lazy queue) - do this is the first few sentences (this is what readers will see in the SERPs)
3. Make crystal clear the recommendation is to use quorum queues instead 
4. Next is a "Deeper Dive" into lazy queues
I didn't change any other information in this topic.
Question on this content: 
_By default, queues keep an in-memory cache of messages that is filled up as messages are published into RabbitMQ. The idea of this cache is to be able to deliver messages to consumers as fast as possible. Note that persistent messages can be written to disk as …

SEO updates in lazy queue content

---

site/queues.md

@michaelklishin and @dyozie can you please review this 1st PR for SEO updates in the OSS content just so you can see the approach that I am taking to these updates and the logic behind it. 
If you both agree with the approach etc, I will continue along this route for the other topics I need to update. @michaelklishin I will include you in all PR reviews, it is optional whether you want to review or not (perhaps a quick scan would be great), @dyozie, I will include you in the review of the first PR to get your feedback - many thanks.
SEO updates in Queues topic:
I approached it this way:
- Used the product-name; constant in the H1 title
- Used product-name; constant in the next H2 title (it is the most important heading in this topic - What is a RabbitMQ Queue?)
- Then used product-name; …

SEO updates in Queue topics - The approach I am taking

---

site/networking.md
site/streams.md

We consulted the documentation, but only found later during testing that for stream replication requires specific stream replication ports. Since AMQP ports are used for the core stream it was unexpected that another port range was added for stream replication. Next time we will check the network guide for sure.
May not concern all developers, but usually network ports have to be explicitly enabled. So hoping that entry makes the requirement more obvious for people that use and support the product.

Add stream replication port info

---

site/feature-flags.md

Feature flags are never removed. Thus, this patch reworks sections which talk about removed feature flags to instead explain required feature flags.
Also, use the notion of "stable feature flags" instead of "supported feature flags". They are not the same. Experimental feature flags are supported too, but they are not enabled by default.
Finally, rework the section about `$RABBITMQ_FEATURE_FLAGS` to explain when it is useful and that required feature flags are still enabled.

Clarify feature flags documentation

---

site/tutorials/tutorial-four-go.md

I followed the tutorial on the page below, but the logs were not written to the file. In the case of Golang, `log.Printf()` outputs to stderr, so I suggest changing the redirect to stderr.
https://www.rabbitmq.com/tutorials/tutorial-four-go.html
>
> If you want to save only 'warning' and 'error' (and not 'info') log messages to a file, just open a console and type:
> ~~~
> go run receive_logs_direct.go warning error > logs_from_rabbit.log
> ~~~

change redirect to stderr because golang log outputs stderr.

---

site/tutorials/tutorial-five-php.md
site/tutorials/tutorial-four-php.md
site/tutorials/tutorial-one-php.md
site/tutorials/tutorial-six-php.md
site/tutorials/tutorial-three-php.md
site/tutorials/tutorial-two-php.md

A few small fixes in PHP tutorial:
* fix wrong argument type `basic_qos`
* recommended method for consuming messages
* object orientied way to get message properties
* require more recent library version

fix: wrong argument types and recommended consume method in php tutorial

---

site/management.md

Path is required for ProxyPass directive and ProxyPassReverse directive in Apache configuration unless inside a <Location> section which rabbitmq management example is not.
https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypass
Further down the rabbitmq management page, in a different section, the correct syntax is used https://www.rabbitmq.com/management.html#proxy
Also added that both mod_proxy and mod_proxy_http are required to be enabled for this to work.

Path is required for ProxyPass directive in Apache configuration

---

site/tutorials/tutorial-four-python.md

Remove extra `"` in on of the last source code examples

Fix small typo in pyhon tutorial four

---

site/networking.md

Added example how to restrict the listener to specified IPv4 on TLS.

doc: restricting TLS to specific IPv4

---

site/kubernetes/operator/using-operator.md

Document how to use the feature introduced in https://github.com/rabbitmq/cluster-operator/pull/1474
that allows to configure Erlang INET in the cluster operator.
This feature was released in Cluster Operator v2.6.0

Document Cluster Operator feature to configure Erlang INET

---

site/specification.xml
site/tutorials/amqp-concepts.md

RabbitMQ does not allow binding operations on the default exchange. Such
operations result in a 403 - Not Allowed error, at the time of this
writing.
We conform with the spec in the creation of the default exchange, and
default bindings i.e. every queue is implicitly bound to the default
exchange with routing key equal to queue name.

Update default exchange restrictions

---

site/relocate.md

While reading through the relocate docs, I noticed that a word seemed to be missing from the `RABBITMQ_MNESIA_DIR` description.  A quick `git grep` showed what the missing word should be from a similar description in the configure docs.  This change makes the description for this environment variable internally consistent.
This PR is submitted in the hope that it is useful. If you wish for any changes, please let me know and I'll be happy to update as necessary and resubmit.

Fix RABBITMQ_MNESIA_DIR description in relocate docs

---

site/access-control.md

When refering to each instance of a list of things, the individual instance is singular.  Hence one should write "each virtual host" rather than "each virtual hosts".  This change fixes this issue.
This PR is intended to be helpful. If there's anything you'd like changed, please let me know and I'll be more than happy to update and resubmit.

Fix plural in access control docs

---

README.md

While reading the project README I noticed that there was a leading dot `.` missing from the commands to use when running the driver in a python virtual environment.  With this change, the commands can be used as-is from the README.
This PR is intended to be helpful.  If there's anything you'd like changed, please let me know and I'll be more than happy to update and resubmit.

Add missing leading dot to driver cmd in README

---

site/quorum-queues.md

Add missing point to advanced.config example so it can be copied and pasted.

Fix advanced.config example on quorum queue page

---

site/download.md

Pointing to the correct URL for the RabbitMQ Docker image

Fix Docker Image Url

---

docs/streams.md

when configured as a policy.
Related: https://github.com/rabbitmq/rabbitmq-server/pull/10502

Clarify behaviour of stream-max-segment-size-bytes

---

site/production-checklist.md

Hi RabbitMQ 👋🏻 
I was going through the [production checklist](https://www.rabbitmq.com/production-checklist.html)–this is awesome!–and I think the network throughput units are slightly wrong. I think this corrects & clarifies the units.
Changes:
- Use KB (1000 bytes) instead of kiB (1024 bytes). Example source: https://en.wikipedia.org/wiki/Kilobyte

Update production-checklist.md: bit/byte units

---

tutorials/tutorial-one-go.md

The goal is to improve the instructions by adding how to init a mod with Go, creating the `main` function, and adding a note to create a new directory for the receiver. This is necessary because, in GoLang, we cannot have two files with the same function name in the same directory. We cannot create two files with the same `func main(){}` name in this case.
It can improve the tutorial's clarity and prevent the reader from having problems with the module and the package. Because you need to be inside a module to run `go get`.

doc(tutorials): improve go instructions

---

docs/mqtt.md

Ran into the removal of this value while upgrading to 3.13 last night and it confused me that it was still mentioned in the documentation. While the change log clarified that with it present RabbitMQ refuses to start up.

Replace the last reference of subscription_ttl with max_session_expiry_interval_seconds

---

docusaurus.config.js

We don't have a need to publish docs for the future of version RabbitMQ yet. We also have a quite some work planned to reorganize the 3.13 docs. So let's name the current version as 3.13 and branch the docs later when everything settles.

docusaurus.config.js: Name current version as "3.13"

---

tutorials/tutorial-five-dotnet.md
tutorials/tutorial-five-elixir.md
tutorials/tutorial-five-go.md
tutorials/tutorial-five-java.md
tutorials/tutorial-four-dotnet.md
tutorials/tutorial-four-elixir.md
tutorials/tutorial-four-go.md
tutorials/tutorial-four-java.md
tutorials/tutorial-one-go.md
tutorials/tutorial-seven-dotnet.md
tutorials/tutorial-seven-java.md
tutorials/tutorial-six-dotnet.md
tutorials/tutorial-six-go.md
tutorials/tutorial-three-go.md
tutorials/tutorial-three-java.md
tutorials/tutorial-three-spring-amqp.md
tutorials/tutorial-two-go.md

Some tutorials contained example code that used the html character entities `&lt;` and `&gt;` instead of `< >`.
Similarly to #1807 this PR aims to fix some of these issues.
Other possible erronous files that I was not sure about and therefore did not edit:
- tutorial-five-javascript.md
- Many php tutorials
- Many objective-C tutorials
- Other Markdown files containing &lt; and &gt;

Fixed Markdown formatting issue with html character entities

---

docusaurus.config.js

The link points to the announcement on the blog.
The colors are the ones used by the "contrasty" blocks on the homepage. This allows to distinguish the announcement bar from the main menu, without dragging too much attention to it (because it is displayed on all pages by default).

docusaurus.config.js: Mention RabbitMQ 3.13.0 in the announcement bar

---

tutorials/tutorial-five-javascript.md
tutorials/tutorial-five-objectivec.md
tutorials/tutorial-five-php.md
tutorials/tutorial-four-go.md
tutorials/tutorial-four-objectivec.md
tutorials/tutorial-four-php.md
tutorials/tutorial-one-objectivec.md
tutorials/tutorial-six-php.md
tutorials/tutorial-three-go.md
tutorials/tutorial-three-objectivec.md
tutorials/tutorial-three-php.md
tutorials/tutorial-two-objectivec.md
tutorials/tutorial-two-php.md

Fix HTML entities in tutorials

---

src/pages/commercial-offerings.md

Request from @HowardTwine to add these companies as providers of both training and consulting, slack conversation below:
@dumbbell can you please review and merge if all ok, thanks.

Add more training and consulting providers

---

docs/index.md
src/components/RabbitMQServer/index.js
src/css/custom.css
static/img/arrow-left.svg
static/img/arrow-up-right.svg

Why:
The [current introduction page ](https://www.rabbitmq.com/docs/documentation) is a table of contents, now that we have a doc table of contents on the new site, we don't need to list links to all the docs on this page. Updating now to provide users with a docs welcome page to help them navigate around this new versioned documentation site.

Changing the Introduction

---

README.md
src/css/custom.css
src/pages/trademark-guidelines.md

Mainly, the blog is not covered by the APL 2.0 and the MPL 2.0 licenses. It remains the intellectual property of Broadcom and can't be redistributed.

README.md: Clarify how the licenses are applied to the content

---

docs/manage-rabbitmq.md
docs/use-rabbitmq.md
sidebarsDocs.js

This will allow external links pointing directly to those sections. Otherwise, the links would have to point to e.g. the first entry in each section.

Add introduction pages behind all top-level sections

---

sidebarsDocs.js

* Move out of `Clustering`, since there's more to managing RabbitMQ on Kubernetes than just clustering
* Link to the Operator installation guide in the `Install and Upgrade` section

Move/add links to the Kubernetes Operator

---

docs/configure.md

Follow up to: https://github.com/rabbitmq/rabbitmq-server/pull/10880 
The deprecated config notes are misleading for users on 3.12.x or later.

Remove deprecated queue_explicit_gc_run_operation_threshold config notes

---

docs/federation-reference.md

* queue-type is a new field added in 3.13.1
* resource-cleanup-mode has been there for a long time but was not documented

Federation: queue-type and resource-cleanup-mode

---

docs/monitoring/index.md

It seems there is a typo on this page: https://www.rabbitmq.com/docs/monitoring#readiness-probes
`rabbitmq-diagnistics` -> `rabbitmq-diagnostics`

Fix `rabbitmq-diagnostics` typo

---

docs/backup.md
docs/clustering.md
docs/definitions.md
docs/download.md
docs/networking.md
docs/plugins.md
kubernetes/operator/using-on-openshift.md
kubernetes/tanzu/installation.md
src/pages/commercial-offerings.md

A) Rebranding updates: Update all references of "VMware RabbitMQ" to "VMware Tanzu RabbitMQ". After the first instance of "VMware Tanzu RabbitMQ" in a topic, you can then use "Tanzu RabbitMQ" in all subsequent instances in that topic except in offering names where I kept the full name "VMware Tanzu RabbitMQ". Once these updates are merged into main, I will do another search to ensure I have missed none. 
B) Adding information about the VMware Tanzu  RabbitMQ OVA and OCI commercial offerings to OSS docs.

rebranding and updates to add OVA and OCI commercial offerings

---

docusaurus.config.js
package-lock.json
package.json

This patch also fixes our usage of `headTags`. The documentation for `headTags` was fixed in Docusaurus 3.2.1 (facebook/docusaurus#10014). The fact that they didn't work for us was not related to a problem in Docusuaurs (#facebook/docusaurus#9792), but an incorrect use on our side.

Upgrade to Docusaurus 3.2.1

---

tutorials/amqp-concepts/index.md

This change improves readability by aligning the wording in [AMQP 0-9-1 Model Explained](https://www.rabbitmq.com/tutorials/amqp-concepts) with the language used in `rabbitmq-website/docs/queues.md`.
https://github.com/rabbitmq/rabbitmq-website/blob/a15004b47e6d0f1c116dbdab738c54437b3fe26f/docs/queues.md?plain=1#L218-L219

Fix wording in amqp-concepts tutorial

---

versioned_docs/version-3.13/plugins.md

There are two `rabbitmq_mqtt` in the list and I think it's good to remove the second one which has less information.
- https://github.com/rabbitmq/rabbitmq-website/blob/main/versioned_docs/version-3.13/plugins.md?plain=1#L471-L479
- https://github.com/rabbitmq/rabbitmq-website/blob/main/versioned_docs/version-3.13/plugins.md?plain=1#L526-L531

Remove duplicate item

---

docs/mqtt.md

While setting up a new user following the documentation at the section "Users and Authentication" in the following [link](https://www.rabbitmq.com/docs/mqtt#authentication). I encountered an error when executing the command `rabbitmqctl set_permissions -p / mqtt-test ".*" ".*" ".*"`. The error presented was "Error (argument validation): too many arguments".
To fix this issue, I added double quotes around the "/" character. This change resolves the error and allows the command to be executed as expected.

Fix: Add double quotes in CLI command in the "Users and Authentication" section

---

docs/management/index.md
versioned_docs/version-3.13/management/index.md

This documentation update is accompanied by this [other](https://github.com/rabbitmq/rabbitmq-server/pull/11064) PR.
It explains two modes on which the logout action works depending on the IDP configuration.

3.13.2: Update to the OAuth 2 logout procedure

---

docs/install-rpm.md
versioned_docs/version-3.13/install-rpm.md

as we currently do not provide openSUSE packages. Around the time of the 3.13.0 release,
there were no compatible Erlang 26.x packages for Leap 15.4 and 15.5.
openSUSE Factory [1] now provides Erlang 26.2.x builds, so this can be reverted once we re-introduce openSUSE flavor RPMs after the final openSUSE Leap 15.6 release.
1. https://download.opensuse.org/repositories/devel:/languages:/erlang:/Factory/openSUSE_Factory/x86_64/

RPM guide: remove mentions of openSUSE (for now)

---

docs/which-erlang.md
versioned_docs/version-3.13/which-erlang.md

`compatible wtih Erlang` should be `compatible with Erlang`.

Fix typo: wtih should be with

---

docs/oauth2-examples-keycloak.md
docs/upgrade.md
versioned_docs/version-3.13/oauth2-examples-keycloak.md
versioned_docs/version-3.13/upgrade.md

Similar to https://github.com/rabbitmq/rabbitmq-website/pull/1916, I've found two more typos 🤣
managament -> management
maintenence -> maintenance

Fix typos: managament to management, maintenence to maintenance

---

docs/classic-queues.md
docs/cli.md
docs/plugins.md

Hi it's me again 🤣, I've found this additional typo.

Typo fix: overriden should be overridden

---

client-libraries/devtools.md

The URL for Spring Integration documentation has been updated to point to the correct reference link. The old URL was pointing to a non-existent page, and it has now been corrected.

Update Spring Integration URL in devtools.md

---

docs/uri-query-parameters.md

Remove fail_if_no_peer_cert from amqp_client options as it is no longer valid with Erlang 26 and will stop the connection from working

remove fail_if_no_peer_cert

---

docs/clustering.md
docs/definitions.md
docs/download.md
docs/networking.md
kubernetes/operator/using-on-openshift.md
src/pages/index.js
versioned_docs/version-3.13/clustering.md
versioned_docs/version-3.13/definitions.md
versioned_docs/version-3.13/download.md
versioned_docs/version-3.13/networking.md

**Why?**
The current links to commercial VMware Tanzu RabbitMQ docs are pointing to the 1.5 docs. We are about to release the commercial 3.13 releases so the doc URLs have now changed (both for rebranding and to include the new version number in the URLs). 
**This PR is not to be merged until the 3.13 VMware Tanzu RabbitMQ commercial docs are live, I will include an update here when that happens.**
Thanks

Updating commercial doc links, making them point to the 3.13 commercial docs

---

blog/2023-03-02-quorum-queues-migration/index.md

This caused issues for me attempting to follow these instructions.
Actual log message:
```
{"@timestamp":"2024-06-05T10:21:54.700488885-07:00","app.name":"rabbitmq-monitor","app.version":"v1.0.1-7-g8248984","deployment.namespace":"rabbitmq-monitor--bento1a","error.error":"Exception (406) Reason: \"PRECONDITION_FAILED - inequivalent arg 'x-queue-type' for queue 'rabbitmq-monitor-round-trip' in vhost 'development': received none but current is the value 'quorum' of type 'longstr'\"","error.kind":"error","error.message":"Exception (406) Reason: \"PRECONDITION_FAILED - inequivalent arg 'x-queue-type' for queue 'rabbitmq-monitor-round-trip' in vhost 'development': received none but current is the value 'quorum' of type 'longstr'\"","level":"ERROR","message":"service down …
```

fix: add instruction to specify queue type explicitly

---

blog/2022-07-22-oidc-integration/index.md
docs/oauth2-examples-keycloak.md
docs/oauth2-examples/index.md
versioned_docs/version-3.13/oauth2-examples-keycloak.md
versioned_docs/version-3.13/oauth2-examples/index.md

- Replacing "KeyCloak" with "Keycloak"
- Replacing "Key Cloak" with "Keycloak"

Fixing Keycloak Spelling

---

.gitignore
sidebarsTutorials.js
src/components/Tutorials/T1DiagramStreamToC.md
src/components/Tutorials/TutorialsStreamHelp.md
src/components/Tutorials/TutorialsStreamIntro.md
tutorials/index.md
tutorials/tutorial-one-dotnet-stream.md
tutorials/tutorial-one-dotnet.md
tutorials/tutorial-one-elixir.md
tutorials/tutorial-one-go-stream.md
tutorials/tutorial-one-go.md
tutorials/tutorial-one-java-stream.md
tutorials/tutorial-one-java.md
tutorials/tutorial-one-javascript-stream.md
tutorials/tutorial-one-javascript.md
tutorials/tutorial-one-php.md
tutorials/tutorial-one-python-stream.md
tutorials/tutorial-one-python.md
tutorials/tutorial-one-ruby.md
tutorials/tutorial-one-rust-stream.md
tutorials/tutorial-one-spring-amqp.md

Stream Tutorial
related to: https://github.com/rabbitmq/rabbitmq-tutorials/pull/382

Stream tutorials

---

src/pages/contact.md

* Make commercial support the first item on the page.
* Add a sub-section explaining how to fill out the support form correctly.
* Add a sub-section with instructions if you do not get prompt support.

Make commercial support more prominent

---

docs/prometheus/index.md
versioned_docs/version-3.13/prometheus/index.md

Segment file count added under queue metrics in PR https://github.com/rabbitmq/rabbitmq-server/pull/11245
This change will reflect that in the documentation

added documentation on segment count under detailed queue_metrics

---

docs/confirms.md

Changed "acknolwedgements" to  "acknowledgements"

Fixed "acknolwedgements" typo in docs/confirms

---

docs/management/index.md
versioned_docs/version-3.13/management/index.md

Contents within backticks are interpreted literally so the `<i>` tag renders rather than controlling italics. We can use `<code>` tags rather than backticks to allow the `<i>` tags to be parsed as HTML.
| Before | After |
|---|---|
| ![before](https://github.com/rabbitmq/rabbitmq-website/assets/21230295/e5937adc-7f98-4533-b423-291bccd6db12) | ![after](https://github.com/rabbitmq/rabbitmq-website/assets/21230295/effe0c25-2ed3-4f41-919f-7c2e172e7261) |

Management plugin: Fix formatting of italics within inline code

---

src/pages/contact.md

Removing the note about the sales contact form as this form is now redundant, it is now a link, FYI @HowardTwine

removing note about sales contact form as this form is now redundant

---

release-information/index.md
src/components/RabbitMQServerReleaseInfo/index.js
src/css/custom.css

Request from product management to remove "End of Extended Commercial Support info from the Release Information topic. @HowardTwine, can you please provide more information here. 
@michael-k or @dumbbell can one of you please complete further updates to delete the dates (computation) and the display of the column, my commit is only deleting the header, many thanks.

Request from product management to remove End of Extended Commercial Support info from the Release Information topic

---

docs/install-debian.md

On ubuntu 22.04 after following these instructions, I was getting: 
```
Err:11 https://ppa1.novemberain.com/rabbitmq/rabbitmq-server/deb/ubuntu jammy/main i386 Packages
404  Not Found [IP: XXXX 443]
```
and
```
E: Failed to fetch https://ppa1.novemberain.com/rabbitmq/rabbitmq-erlang/deb/ubuntu/dists/jammy/main/binary-i386/Packages  404  Not Found [IP: XXXXX 443]
```
Someone mentioned that in discussions:
https://github.com/rabbitmq/rabbitmq-server/discussions/8934
The answer was to use a 64-bit machine and I am using a 64 bit machine. I suspect this happens on Ubuntu if you have it setup to bring in 32 bit libraries for some things, but I've not checked out if this is true.
I think that since the PPA only provides AMD64 packages, adding the filter shouldn't mess anyone up.

Added architecture filter to deb examples.

---

kubernetes/operator/using-topology-operator.md

Based on discussion https://github.com/rabbitmq/messaging-topology-operator/issues/851

Docs on rabbitmqClusterReference.namespace if using non operator managed RabbitMQ

---

src/rehype/img-rendering.js

The Rehype plugin used to render images with a caption from the alt attribute must unescape the caption value as the alt attribute value can contain escaped characters.

Unescape image caption

---

blog/2022-03-29-at-least-once-dead-lettering/index.md
blog/2023-05-17-rabbitmq-3.12-performance-improvements/index.md
docs/amqp.md
docs/clustering.md
docs/install-debian.md
docs/quorum-queues/index.md
docs/shovel-dynamic.md
docs/shovel-static.md
docusaurus.config.js
src/css/custom.css
src/rehype/img-rendering.js
versioned_docs/version-3.13/clustering.md
versioned_docs/version-3.13/install-debian.md
versioned_docs/version-3.13/quorum-queues/index.md

Documents the feature implemented by https://github.com/rabbitmq/rabbitmq-server/pull/11793

Configure shovels to wait until all sources and destinations are declared

---

docs/install-debian.md
versioned_docs/version-3.13/install-debian.md

The Debian Bookworm install steps had you adding mirrors for bullseye and the Debian Bullseye install steps had you adding mirrors for bookworm, I have switched these around.

Update install-debian.md to correct debian mirrors

---

sidebarsTutorials.js
tutorials/index.md
tutorials/tutorial-one-python-stream.md
tutorials/tutorial-two-python-stream.md
tutorials/tutorial-two-rust-stream.md

Tutorial two for RabbitMQ streams for Python and Rust clients.
It fixes a small thing on the Python tutorial1 as we don't need to install the type_extension dependency.

streaming tutorial_2 for python and rust

---

docs/quorum-queues/index.md
versioned_docs/version-3.13/quorum-queues/index.md

Add row about server-named queues in QQ feature matrix, since it's not implemented for quorum queues.

Add row about server-named queues in QQ feature matrix

---

docs/federation-reference.md

The code example shows escaped html tags. Fixes it and quotes parameters to align style with other commands.

Fix typo in federation code example

---

tutorials/tutorial-four-go.md

Fix an indent issue in go example code.
before:
after:

Fix indent issue in go tutorial.

---

docs/channels/index.md
docs/consumers.md
versioned_docs/version-3.13/channels/index.md
versioned_docs/version-3.13/consumers.md

These were added to the server in https://github.com/rabbitmq/rabbitmq-server/commit/d7374cb244af961331f24e060e77f721edb2b6d1 but never documented.

Document two 'new' features: channel_max_per_node and consumer_max_per_channel

---

docs/mqtt.md

This commit is a follow-up of https://github.com/rabbitmq/rabbitmq-website/pull/2017

Update MQTT docs to use new anonymous_login_user

---

blog/2024-03-11-rabbitmq-3.13.0-announcement/index.md

Video was lost, reported in #2014, this adds it again after Erlang Solutions (Code Beam organizers) made the video public today.

Re-add Khepri video, fix typo

---

docs/configure.md
docs/memory-use/index.md
docs/memory.md
docs/production-checklist.md
docs/upgrade.md

Additionaly, some edits around memory usage docs.

In 4.0, the default memory watermark increased to 0.6

---

docs/quorum-queues/index.md
versioned_docs/version-3.13/quorum-queues/index.md

It seems `quorum_queue.continuous_membership_reconciliation.enabled` default value is `false` in `main` and `v3.13.x`, hence this correction.
From `rabbitmq-server` `main`: https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit/src/rabbit_quorum_queue_periodic_membership_reconciliation.erl#L64
From `rabbitmq-server` `v3.13.x`:  https://github.com/rabbitmq/rabbitmq-server/blob/v3.13.x/deps/rabbit/src/rabbit_quorum_queue_periodic_membership_reconciliation.erl#L64

Change continuous membership reconciliation default to be false.

---

docs/oauth2.md

Since 3.10/[rabbitmq/rabbitmq-server#7458](https://github.com/rabbitmq/rabbitmq-server/pull/7458), preferred_username_claims has accepted a list of claim names rather than a comma-separated string.

Correct description of OAuth2 preferred username claims config

---

docs/amqp.md

As described in https://docusaurus.io/docs/markdown-features/admonitions#usage-with-prettier
> If you use Prettier to format your Markdown files, Prettier might auto-format your code to invalid admonition syntax.
> To avoid this problem, add empty lines around the starting and ending directives. This is also why the examples we
> show here all have empty lines around the content.

Avoid invalid admonition syntax

---

docs/mqtt.md
versioned_docs/version-3.13/mqtt.md

Implements feature request https://github.com/rabbitmq/rabbitmq-server/issues/9323

MQTT plugin authenticate using client_id from client certificate

---

tutorials/tutorial-five-dotnet.md
tutorials/tutorial-five-elixir.md
tutorials/tutorial-five-go.md
tutorials/tutorial-five-java.md
tutorials/tutorial-five-javascript.md
tutorials/tutorial-five-objectivec.md
tutorials/tutorial-five-php.md
tutorials/tutorial-five-python.md
tutorials/tutorial-five-ruby.md
tutorials/tutorial-five-spring-amqp.md
tutorials/tutorial-five-swift.md
tutorials/tutorial-four-dotnet.md
tutorials/tutorial-four-elixir.md
tutorials/tutorial-four-go.md
tutorials/tutorial-four-java.md
tutorials/tutorial-four-javascript.md
tutorials/tutorial-four-objectivec.md
tutorials/tutorial-four-php.md
tutorials/tutorial-four-python.md
tutorials/tutorial-four-ruby.md
tutorials/tutorial-four-swift.md

For some reason, double quotes can be found surrounding many strings that are formatted with backticks.

Remove extra double quotes

---

kubernetes/operator/quickstart-operator.md

Link from cluster-operator quickstart to KubeCon talk for the users who prefer a more visual demo in a video. The talk demonstrates what's described in this quickstart guide.

Link from cluster-operator quickstart to demo

---

docs/metadata-store/daily-use.md
src/css/custom.css

The section was copied from the RabbitMQ 3.13.0 release notes.

docs/metadata-store: Document Khepri visibility guarantees

---

docs/blue-green-upgrade.md
docs/feature-flags/index.md
docs/grow-then-shrink-upgrade.md
docs/rolling-upgrade.md
docs/upgrade.md
docs/which-erlang.md
docs/windows-configuration.md
sidebarsDocs.js

* split the `upgrade` page into multiple pages
* each upgrade strategy has a dedicated page
* right-hand side table of contents should outline the main steps
* remove references to full-stop upgrades - there has been no need for a full stop upgrade since feature flags were introduced
* remove other notes that are no longer relevant

Refresh upgrade-related documentation

---

docs/clustering.md
docs/feature-flags/index.md
docs/grow-then-shrink-upgrade.md
docs/upgrade.md
docusaurus.config.js

Fix several link anchors broken by #2068. This went unnoticed because Docusaurus emitted warnings only, not errors.
While here, consider broker anchors as errors, si that it doesn’t pass CI in the future.

Fix several broken link anchors

---

blog/2024-03-11-rabbitmq-3.13.0-announcement/index.md
client-libraries/erlang-client-user-guide.md
docs/quorum-queues/index.md
docs/shovel-dynamic.md
docs/shovel-static.md
src/pages/plugin-development.md
versioned_docs/version-3.13/quorum-queues/index.md
versioned_docs/version-3.13/shovel-dynamic.md
versioned_docs/version-3.13/shovel-static.md
versioned_docs/version-3.13/specification.md
versioned_docs/version-4.0/quorum-queues/index.md
versioned_docs/version-4.0/shovel-dynamic.md
versioned_docs/version-4.0/shovel-static.md

They were all reported by the Algolia crawler because they use the HTML syntax and are skipped by the Docusaurus link checker.

Fix even more broken links and trailing slashes

---

docs/federation-reference.md
docs/shovel-dynamic.md
docs/shovel-static.md

The message may be lost if there are network failures between shovel worker and destination broker.

Fix docs for on-publish

---

docs/prometheus/index.md
versioned_docs/version-4.0/prometheus/index.md

This PR adds documentation for Prometheus metrics introduced by https://github.com/rabbitmq/rabbitmq-server/pull/11559

Document per exchange and per queue metrics

---

versioned_docs/version-4.0/download.md

Changed the name of image to rabbitmq:4.0.2-management
because the page describes the version 4 of RabbitMQ and not the version 3

docs: Change rabbitmq:3.13-management by rabbitmq:4.0.2-management

---

docs/oauth2-examples-auth0.md
docs/oauth2-examples-entra-id/index.md
docs/oauth2-examples-keycloak.md
docs/oauth2-examples-multiresource.md
docs/oauth2-examples-okta.md
docs/oauth2-examples-proxy.md
docs/oauth2-examples/index.md
docs/oauth2.md
versioned_docs/version-3.13/oauth2-examples-auth0.md
versioned_docs/version-3.13/oauth2-examples-entra-id/index.md
versioned_docs/version-3.13/oauth2-examples-keycloak.md
versioned_docs/version-3.13/oauth2-examples-multiresource.md
versioned_docs/version-3.13/oauth2-examples-okta.md
versioned_docs/version-3.13/oauth2-examples-proxy.md
versioned_docs/version-3.13/oauth2-examples/index.md
versioned_docs/version-3.13/oauth2.md
versioned_docs/version-4.0/oauth2-examples-auth0.md
versioned_docs/version-4.0/oauth2-examples-entra-id/index.md
versioned_docs/version-4.0/oauth2-examples-keycloak.md
versioned_docs/version-4.0/oauth2-examples-multiresource.md
versioned_docs/version-4.0/oauth2-examples-okta.md
versioned_docs/version-4.0/oauth2-examples-proxy.md
versioned_docs/version-4.0/oauth2-examples/index.md
versioned_docs/version-4.0/oauth2.md

Update multi-resource example 
This PR required another [PR](https://github.com/rabbitmq/rabbitmq-oauth2-tutorial/pull/28) in the rabbitmq-oauth2-tutorial which is now merged.
Tasks: 
This change applies to all versions: 3.13.x , 4.0.x and main.

Update multi-resource example

---

docs/management/index.md
docs/oauth2-examples-auth0.md
docs/oauth2-examples-entra-id/index.md
docs/oauth2-examples-okta.md
docs/oauth2-examples/index.md
docs/oauth2.md
versioned_docs/version-3.13/oauth2.md
versioned_docs/version-4.0/oauth2.md

Implements these two features:
- https://github.com/rabbitmq/rabbitmq-server/issues/12239
- https://github.com/rabbitmq/rabbitmq-server/issues/12237
Only for 4.1.x
**This PR should only be merged after this [PR](https://github.com/rabbitmq/rabbitmq-server/pull/12399) has been merged.** and this PR has been rebased too.

4.1: Deprecate two OAuth 2 settings

---

kubernetes/operator/using-topology-operator.md

Another feature that was implemented and released, but never documented.
Related to rabbitmq/messaging-topology-operator/pull/886

Document password hash in Topology Operator

---

docs/oauth2-examples-keycloak.md
docs/oauth2-examples-multiresource.md
docs/oauth2-examples-proxy.md
docs/oauth2-examples/index.md
versioned_docs/version-3.13/oauth2-examples-keycloak.md
versioned_docs/version-3.13/oauth2-examples-proxy.md
versioned_docs/version-3.13/oauth2-examples/index.md
versioned_docs/version-4.0/oauth2-examples-keycloak.md
versioned_docs/version-4.0/oauth2-examples-proxy.md
versioned_docs/version-4.0/oauth2-examples/index.md

All the examples that affected uaa or keycloak or oauth2-proxy did not use tls. 
The scripts and configuration files referenced by the examples are already in the main branch of the rabbitmq-oauth2-tutorial.

Configure keycloak, uaa and oauth2-proxy with TLS

---

versioned_docs/version-3.13/oauth2-examples-okta.md
versioned_docs/version-4.0/oauth2-examples-okta.md

This link to `rabbitmq.conf` at this page is broken:
https://www.rabbitmq.com/docs/oauth2-examples-okta#configure-rabbitmq-to-use-okta-as-oauth-20-authentication-backend
This PR attempts to fix that broken link by point to the rabbitmq.conf.tmpl file that does exist in that location.

Fix the link to rabbitmq.conf link to point to the file the does exist

---

docs/sender-selected.md

Document the new `x-cc` message annotation as introduced in RabbitMQ 4.1 via https://github.com/rabbitmq/rabbitmq-server/pull/12559
Rewrite AMQP 0.9.1 docs since they didn't make sense.

Document `x-cc` message annotation

---

docs/configure.md
versioned_docs/version-3.13/configure.md
versioned_docs/version-4.0/configure.md

As described in #2114 , the config option has an incorrect name on the website.

[docs/configure] rename `management_db_cache_multiplier` option to `management.db_cache_multiplier`

---

docs/deprecated-features/index.md
release-information/deprecated-features-list.md
sidebarsDocs.js
sidebarsReleaseInfo.js
versioned_docs/version-3.13/deprecated-features/index.md
versioned_docs/version-4.0/deprecated-features/index.md
versioned_sidebars/version-3.13-sidebars.json
versioned_sidebars/version-4.0-sidebars.json

The list of deprecated features is also documented in the release information section.

deprecated-features: Document the Deprecated features subsystem

---

docs/upgrade.md
versioned_docs/version-4.0/upgrade.md

The docs recommended to enable all feature flags before an upgrade. This is incorrect: only stable feature flags should be enabled, not experimental ones.
Specify that only stable feature flags should be enabled.
While here, remove the important admonition from the "next" version because we will use soft require feature flags from now on.

upgrade: Clarify which feature flags to enable on upgrade

---

docs/event-exchange.md
docs/logging.md

This is the docs PR for
https://github.com/rabbitmq/rabbitmq-server/pull/12714 and applies to RabbitMQ >= 4.1
Note that the internal event types were documented previously at three different places:
1. https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbitmq_event_exchange/README.md
2. https://www.rabbitmq.com/docs/event-exchange
3. https://www.rabbitmq.com/docs/logging#internal-events
All of them listed different and/or outdated event types. From now on, we use the 3rd place as only place and single source of truth for documenting internal events.

Update Event Exchange Plugin docs

---

client-libraries/devtools.md

This pull request includes a small change to the `client-libraries/devtools.md` file. The change adds a new RabbitMQ stream client for C++ to the list of miscellaneous projects.

Add Hareflow, a stream client for C++, in devtools

---

kubernetes/operator/install-topology-operator.md

Documented default behaviour is incorrect. Based on the docs from
controller-runtime library, the default sync period is 10 hours. Adding
how to disable this mechanism, as it may not be trivial to deduce.

Fix topology operator docs: sync period

---

docs/stream.md

This pull request includes a small change to the `docs/stream.md` file. The change adds a new RabbitMQ stream client for C++.

Add a stream client for C++ in stream.md

---

src/plugins/configure-svgo.js

The `src/plugins/configure-svgo.js` file has code that depends on the current path separator. This removes the hard-coded `/` separator and uses the `path.sep` value, instead.
Follow-up to acb4b1852ea3fd272f55901202173ba434bc68ea

Fix `npm start` on Windows

---

docs/vhosts.md

the 4.0 version will be submitted separately
because it'd have to wait for `4.0.6` to ship first.

4.1 doc updates for rabbitmq/rabbitmq-server#13015

---

blog/2024-12-18-epmd-public-exposure/index.md
blog/authors.yml

Add blog entry with link to https://erlef.org/blog/eef/epmd-public-exposure

Add EEF EPMD Exposure Blog Reference

---

docs/oauth2.md
versioned_docs/version-3.13/oauth2.md
versioned_docs/version-4.0/oauth2.md

Fixing a small typo in the OAuth 2.0 docs

Fix typo in OAuth 2.0 docs from 'uess' to 'uses'

---

blog/2024-09-02-amqp-flow-control/index.md

See https://github.com/rabbitmq/rabbitmq-website/pull/2037#discussion_r1905343470
https://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#doc-flow-control
> The delivery-count is initialized by the sender when a link endpoint is created, and is incremented whenever a message is sent.

Fix delivery-count description

---

docs/consumers.md

Note that exclusive consumers is a Classic Queues only feature to reflect the same info on the feature matrix.

Update consumers.md exclusivity

---

docs/streams.md

I noticed the example for setting the x-stream-filter-size-bytes didn't actually set the value, so i updated it to do so.

correct stream bloom filter example

---

docs/access-control.md
versioned_docs/version-3.13/access-control.md
versioned_docs/version-4.0/access-control.md

Saw that `oauth` and `oauth2` aliases were added for auth backends configuration since `3.13`. Updating the docs to reflect so.
Relevant commit: https://github.com/rabbitmq/rabbitmq-server/commit/16f49d336f8a3975922ff1b370c10fe9ae1a89e3

Add oauth2 alias for configuring auth backend in documentation

---

tutorials/amqp-concepts/index.md

Fix typo in 'AMQP 0-9-1 Model Explained' article

---

blog/2024-08-05-native-amqp/index.md

Link to RabbitMQ Summit 2024 talk and update docker image from 4.0 RC to 4.0.

Link to talk and update docker image

---

docs/oauth2-examples-forward-proxy.md
docs/oauth2-examples-keycloak.md
docs/oauth2-examples/index.md
docs/oauth2.md

Add commercial-only setting that supports explicit forward proxy and an example that demonstrates it.
Feature meant for 4.1.x.

Support forward proxy in oauth2

---

versioned_docs/version-4.0/ssl/index.md

Small typo fix in versioned_docs/version-4.0/ssl/index.md.

Fix typo in ssl example code

---

blog/2025-02-07-rabbitmq-3.13.8-is-released/index.md

for those holding a commercial license.
4.0.x is still distributed via GitHub and
package repositories until the release of 4.1.0.

New blog post: RabbitMQ 3.13.8 is released

---

docs/logging.md
versioned_docs/version-3.13/logging.md
versioned_docs/version-4.0/logging.md

Fixes a typo in the [docs/logging.md](docs/logging.md).

fix: typo in logging

---

docs/cluster-formation.md

Documentation for [PR 13194 @ rabbitmq-server](https://github.com/rabbitmq/rabbitmq-server/pull/13194). The config option `cluster_formation.registration` allows to opt-out of registration for peer discovery backends that support it.

4.0.6: Peer discovery: document how to opt-out of registration

---

docs/amqp.md

`dynamic` is implemented by https://github.com/rabbitmq/rabbitmq-server/pull/13231

Remove `dynamic` AMQP limitation

---

docs/amqp.md
versioned_docs/version-4.0/amqp.md

Relates to https://github.com/rabbitmq/rabbitmq-server/pull/13307

Add Message Annotations section

---

docs/access-control.md
docs/auth-cache-backend.md
sidebarsDocs.js
versioned_docs/version-4.0/access-control.md
versioned_docs/version-4.0/auth-cache-backend.md
versioned_sidebars/version-4.0-sidebars.json

When the docs wanted to reference the cache authz backend, it used to link to the Readme in the source code. 
Since this plugin now has a rabbitmqctl command and to keep the docs consistent, this PR adds a docs page dedicated to this plugin.

Add docs for cache auth backend

---

client-libraries/amqp-client-libraries.md

Instead of exchangeDeletion and queueDeletion, which are deprecated.
References rabbitmq/rabbitmq-amqp-java-client#137
To merge when AMQP Java client 0.4.0 is release.

Document exchangeDelete and queueDelete for AMQP Java client

---

kubernetes/operator/install-topology-operator.md
kubernetes/operator/tls-topology-operator.md

Nearly 2 years ago this issue was raised: https://github.com/rabbitmq/messaging-topology-operator/issues/621
With the following PR addressing it: https://github.com/rabbitmq/messaging-topology-operator/pull/622
This enabled the Messaging Topology Operator to communicate to RabbitMQ clusters via HTTP, even if the cluster had TLS enabled. The PR added in a new environment variable called `CONNECT_USING_PLAIN_HTTP`.
I don't believe that this was documented anywhere?
Furthermore, it also [addresses this limitation](https://www.rabbitmq.com/kubernetes/operator/tls-topology-operator#limitations):
> Messaging Topology Operator will not attempt to connect to the RabbitmqCluster over HTTP if HTTPS is available (even if the certificate is not trusted)
The need to remove this was also mentioned in …

CONNECT_USING_PLAIN_HTTP Env Variable for the Messaging Topology Operator

---

blog/2015-04-16-scheduling-messages-with-rabbitmq/index.md

An existing link in the blog "scheduling messages with RabbitMQ" is broken, which could be confusing for users looking for a working implementation of delayed messaging with RabbitMQ.  This PR updates the link to point to the NServiceBus implementation, which is actively maintained and is widely used by our customers.  This should provide a more reliable reference for users choosing to implement delayed delivery themselves.

Update Link to Working Delayed Messaging Implementation 

---

docs/oauth2-examples-idp-initiated.md
docs/oauth2-examples/index.md
versioned_docs/version-3.13/oauth2-examples-idp-initiated.md
versioned_docs/version-3.13/oauth2-examples/index.md
versioned_docs/version-4.0/oauth2-examples-idp-initiated.md
versioned_docs/version-4.0/oauth2-examples/index.md

The proposed changes add a new Oauth2 example that demonstrates the Idp-initiated logon via a web portal. 
I have added it to all versions : next, 4.0 and 3.13. This example was mainly added for a customer expecting the next 3.13.x release.
This PR depends on another [PR](https://github.com/rabbitmq/rabbitmq-oauth2-tutorial/pull/45) on the rabbitmq-oauth2-tutorial repo for next version (4.1) and [PR](https://github.com/rabbitmq/rabbitmq-oauth2-tutorial/pull/46) for 4.1 and 3.13 versions. These two PRs are now merged.

Add idp-initiated login  example

---

docs/ssl/index.md
versioned_docs/version-4.0/ssl/index.md

Reading the documentation and following the flow in order, you are led into error by not setting the password for the server certificate key right away, which is set following the example in the Using tls-gen's Basic Profile paragraph.
Usually it is rare to have a server certificate key without a password even for test/development environments.

Highlighted the use of the ssl_options.password option.

---

versioned_docs/version-4.0/exchanges.md

I beleave there is still typo in 4.0 version.  Also I have checked version 3.13 and did not find such typo there

Fix typo in exchanges.md 4.0

---

docs/channels/index.md
versioned_docs/version-3.13/channels/index.md
versioned_docs/version-4.0/channels/index.md

Fix confusing grammar around long-lived channels

---

docusaurus.config.js

Fixes #2222 
Apparently it was defined through presets for the docs/blog but not through the plugins section for tutorial, kubernetes and client-libraries.
I have not added it to "release-information" as that seemed to not per-se apply

Add editUrl to tutorial, kubernetes and client-libraries

---

docs/clustering.md
docs/quorum-queues/index.md
docs/streams.md
versioned_docs/version-3.13/clustering.md
versioned_docs/version-3.13/quorum-queues/index.md
versioned_docs/version-3.13/streams.md
versioned_docs/version-4.0/clustering.md
versioned_docs/version-4.0/quorum-queues/index.md
versioned_docs/version-4.0/streams.md
versioned_docs/version-4.1/clustering.md
versioned_docs/version-4.1/quorum-queues/index.md
versioned_docs/version-4.1/streams.md

To clarify it operates on the number of _configured_ members _not_ the number of _online_ members.
Also settle the latest QQ doc version to use the word "member" instead of the ambiguous "replica"

Fix incorrect QQ CMR documentation

---

client-libraries/amqp-client-libraries.md

based on: https://github.com/rabbitmq/rabbitmq-amqp-python-client/pull/63

update python documentation

---

docs/http-api-reference.md

This is the companion PR adding the health checks in https://github.com/rabbitmq/rabbitmq-server/pull/13879 to the API reference doc
Connects https://github.com/rabbitmq/rabbitmq-server/issues/13782

Document health checks for testing readiness to serve clients

---

src/pages/plugin-development.md

For some time now, it has been a requirement to clone plugin repositories into the `deps` directory of a `rabbitmq/rabbitmq-server` repository for the plugin build process to work.
This PR updates the documentation to reflect that requirement.

Update plugin development guide

---

docs/oauth2.md
versioned_docs/version-3.13/oauth2.md
versioned_docs/version-4.0/oauth2.md
versioned_docs/version-4.1/oauth2.md

Add variable expansion section to oauth2 docs in main and 4.1.x versions.
And slightly rename the section that explains step by step how to configure oauth2 in all versions.
This PR cannot be merged until https://github.com/rabbitmq/rabbitmq-server/pull/13941 is merged.

Add variable expansion section to oauth2 docs 

---

blog/2025-07-04-go-stream-client-1.5.8-critical-fix/index.md
blog/authors.yml

Blog post about the Go stream [client 1.5.8](https://github.com/rabbitmq/rabbitmq-stream-go-client/releases/tag/v1.5.8) released.

GO stream client 1.5.8 released with a critical fix

---

src/pages/contact.js

Allow AceMQ to track referral traffic from RabbitMQ.com via UTM parameters or referral headers.
`Link` has the default ref="noopener noreferrer" and needs to be overridden.

[RMQ-1746] Remove noreferrer from links to AceMQ

---

src/pages/contact.js

- Move the 'Community' subsection to the right, after 'Commercial' and 'Consulting & Training'
- Update the content under 'Community'
- Update the description and buttons of 'Partner Spotlight'

[RMQ-1746] Update support page content

---

docs/prometheus/index.md

PR https://github.com/rabbitmq/rabbitmq-server/pull/13895 switches from exposing `ra_metrics` ETS table values as Prometheus metrics, to exposing Ra counters from seshat. There's many more metrics available with this change.
A few metrics are the same but have a slightly different name. Since the old name was incorrect, we don't maintain compatibility but use this opportunity to fix the name:
These metrics lost the `_log` part, since they are not log related:
* rabbitmq_detailed_raft_log_snapshot_index  -> rabbitmq_detailed_raft_commit_index
* rabbitmq_detailed_raft_log_last_applied_index -> rabbitmq_detailed_raft_last_applied_index
* rabbitmq_detailed_raft_log_commit_index -> rabbitmq_detailed_raft_commit_index
rabbitmq_detailed_raft_term_total is now rabbitmq_detailed_raft_term. It was …

Update ra_metrics family for Ra counters

---

src/pages/contact.js
src/pages/index.js
src/pages/index.module.css

1. Move “What about the license?” section to the top of the page. Delete the “What about the license?” title to save space
2. Alternate background colors from white to `primary-contrast-background` separating each section. Start with white for the section we moved to the top. After making this change, the license section on the home page should use a white background, while the license section on the support page should not. Therefore, rename the `license` class to `⁠tanzu_license` on the support page
3. Update the description under the deleted title
4. Change title from “Commercial offerings” (plural) to “Commercial offering” (singular), update content under the title

Update home page content

---

docs/stream-core-plugin-comparison.md
docs/stream.md
docs/streams.md
versioned_docs/version-3.13/stream-core-plugin-comparison.md
versioned_docs/version-3.13/stream.md
versioned_docs/version-3.13/streams.md
versioned_docs/version-4.0/stream-core-plugin-comparison.md
versioned_docs/version-4.0/stream.md
versioned_docs/version-4.0/streams.md
versioned_docs/version-4.1/stream-core-plugin-comparison.md
versioned_docs/version-4.1/stream.md
versioned_docs/version-4.1/streams.md

Documentation for clients' sub-entry batching compressions.
The compression happens client-side. Here we document the clients' implementations.
@michaelklishin @acogoluegnes if it is ok with you, I will copy it for the other versions. ( If necessary )

Add clients compressions implementations

---

client-libraries/devtools.md

Hello!
I just added a Kotlin client under the Other JVM languages. Note that this client is compatible with Kotlin Multiplatform, so it also runs outside of JVM (maybe we should make a dedicated section for Kotlin?)

Adding Kourier, a Kotlin client

---

kubernetes/operator/install-operator.md

The Bitnami charts are no longer open source, and as such, no longer a viable method for installation of OSS RabbitMQ.

Remove Bitnami chart from operator installation instructions.

---

docs/http-api-reference.md
versioned_docs/version-4.0/http-api-reference.md
versioned_docs/version-4.1/http-api-reference.md

The protocol-listener health check accepts protocol names with 's' for the encrypted listeners like `amqps` and `mqtts`. The health check distinguishes between encrypted and non-encrypted so to get a 200 when running AMQPS but not AMQP you need to query for `amqps`.
This change mentions the encrypted protocol names. I've also combined `amqp091` and `amqp10` as `amqp` which is what the health check translates these into.
Also see https://github.com/rabbitmq/rabbitmq-server/blob/c7f6cad331443df0eaad668c2f1ca62410259c3a/deps/rabbitmq_management/src/rabbit_mgmt_wm_health_check_protocol_listener.erl#L71-L135. The health check normalizes the protocol names so it can accept quite a large range

Mention encrypted listeners in protocol-listener API reference

---

docs/configure.md

https://github.com/rabbitmq/rabbitmq-server/pull/14410

Document RABBITMQ_MAX_OPEN_FILES

---

docs/access-control.md
versioned_docs/version-3.13/access-control.md
versioned_docs/version-4.0/access-control.md
versioned_docs/version-4.1/access-control.md

**Still a work in progress. Please do NOT merge.**
STOMP guide does not have any mention to permissions. I could guess what is requires but 🤷‍♂️

Document access control in additional protocols

---

docs/deprecated-features/index.md
versioned_docs/version-3.13/deprecated-features/index.md
versioned_docs/version-4.0/deprecated-features/index.md
versioned_docs/version-4.1/deprecated-features/index.md

Noticed a typo when reading the docs, so figured I would do a quick PR.

Fix typo (decied -> decide) in Deprecated Features section

---

kubernetes/operator/using-topology-operator.md

Knowing the Secret name before it is generated is required for some
workflows.
For instance, if you need to refer to the Secret to mount it in a Pod,
and you're not deploying your User object before writing your Pod spec
(common in gitops workflows), you need to have the Secret name
beforehand.
The Secret name is already fixed in code, but this is currently not
documented.
Update the documenation in accordance with the code.
Fixes rabbitmq/cluster-operator#1946

Document the name of the credentials Secret generated for User objects

---

docusaurus.config.js
src/components/CommercialSupportTimelines/index.js
src/components/CommercialSupportTimelines/index.module.css
src/pages/contact.js

- On the support page, under the VMware Tanzu RabbitMQ section, change `Enterprise Support` to `Commercial Support`
- Add a third tab titled `Support Timelines` and place it between `Commercial Support` and `Enterprise Features`, and set this tab as default tab

[RMQ-2053] Add support timelines to support page as a new tab

---

docs/stream-filtering.md

Update amq 1.0 filter-expressions documentation for:
- c#
- go
- python
See: https://amqp-filter-update-languages.rabbitmq-website.pages.dev/docs/next/stream-filtering#stage-2-amqp-filter-expressions

Filters documentation for amqp 1.0 clients 

---

src/pages/commercial-features.js

Add a CTA after a space under Longer Support Timelines section of the commercial features that says, “See your support timelines”, and have it take the user to the bottom of the page to see the support timeline table.

[RMQ-2158] Add an anchor to timelines table under Longer Support Timelines
